const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
const check=require('../target/tests/navigation-controls-browser-check'),base='http://127.0.0.1:18880',url=base+'/wp-admin/themes.php?page=vf-theme-modules&tab=navigation';
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage(),errors=[],functional={};global.proofPage=page;page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill('admin');await page.locator('#user_pass').fill('Synthetic-Only-Update-54!');await Promise.all([page.waitForURL(/wp-admin/),page.locator('#wp-submit').click()]);
 const root=page.locator('[data-vf-navigation-page]'),tab=key=>root.locator('[data-vf-navigation-workflow-step='+key+']'),cta=root.locator('[data-vf-navigation-i18n-panel=header]:visible input').first(),save=root.locator('[data-vf-navigation-save]');
 const go=async()=>{await page.goto(url);await root.waitFor();await page.waitForFunction(()=>document.querySelector('[data-vf-navigation-page]').dataset.vfNavigationDirty==='0');};
 const settled=()=>page.waitForFunction(()=>document.querySelector('[data-vf-navigation-form]').dataset.vfSubmitting!=='1');
 const snapshot=()=>root.locator('form').evaluate(n=>[...n.querySelectorAll('[name^="navigation["]')].map(c=>({name:c.name,type:c.type,value:c.value,checked:['checkbox','radio'].includes(c.type)?c.checked:null})));
 const send=async(p=page)=>{const resp=p.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST');const b=p.locator('[data-vf-navigation-save]');if(await b.isVisible())await b.click();else {await p.locator('[data-vf-navigation-workflow-step=verify]').click();await p.locator('[data-vf-navigation-verify]').click();}const result=await (await resp).json();await p.waitForFunction(()=>document.querySelector('[data-vf-navigation-form]').dataset.vfSubmitting!=='1');return result;};
 const confirmed=async()=>{const p=await send();assert(p.success&&p.data.ok&&p.data.readback,JSON.stringify(p));await page.waitForFunction(()=>document.querySelector('[data-vf-navigation-page]').dataset.vfNavigationDirty==='0');assert.equal(await root.getAttribute('data-vf-navigation-save-result'),'confirmed');assert(!await save.isVisible());assert(Object.values(p.data.runtimeVerification.checks).every(c=>c.ok));return p;};
 await go();await page.setViewportSize({width:1440,height:1000});
 if(process.env.BASELINE==='1'){
  await tab('header').click();await cta.fill('Synthetic baseline draft');let release;const held=new Promise(r=>release=r);await page.route('**/admin-ajax.php',async r=>{await held;await r.fulfill({json:{success:true,data:{}}});});const requested=page.waitForRequest(r=>r.url().includes('admin-ajax.php'));await save.click();await requested;assert(await cta.isEnabled(),'old save lock defect no longer reproduced');release();await settled();assert.equal(await root.getAttribute('data-vf-navigation-dirty'),'0','old incomplete response defect no longer reproduced');await page.screenshot({path:'proof/baseline-header.png',fullPage:true});fs.writeFileSync('proof/baseline.json',JSON.stringify({version:process.env.SOURCE_VERSION,busy_controls_editable:'REPRODUCED',incomplete_response_false_success:'REPRODUCED'},null,2));await browser.close();return;
 }
 const checks=[];for(const width of [1920,1440,1319,1024,768,390]){await page.setViewportSize({width,height:1000});await go();assert.equal(await root.locator('.vf-navigation-status-dot').getAttribute('data-status'),'pass');checks.push(await check(page,{width,out:require('path').resolve('proof'),screenshots:true}));}
 await page.setViewportSize({width:1440,height:1000});await go();const visited=new Set();
 for(const key of ['menus','header','footer']){
  await tab(key).click();
  if(key==='menus')for(const b of await root.locator('[data-vf-navigation-binding-target]').all()){await b.click();const c=root.locator('[data-vf-navigation-menu]:visible');const opts=await c.locator('option').evaluateAll(ns=>ns.map(n=>n.value).filter(v=>Number(v)>0));const v=await c.inputValue();await c.selectOption(opts.find(x=>x!==v)||v);visited.add(await c.getAttribute('name'));}
  else{
   for(const c of await root.locator('[data-vf-navigation-workflow-section='+key+'] input:not([type=hidden]):visible,[data-vf-navigation-workflow-section='+key+'] select[name]:visible').all()){
    const m=await c.evaluate(n=>({name:n.name,type:n.tagName==='SELECT'?'select':n.type,value:n.value,min:n.min,max:n.max,checked:n.checked}));if(m.name.includes('[i18n]')||m.type==='radio')continue;
    if(m.type==='checkbox')await c.setChecked(!m.checked);else if(m.type==='select'){const opts=await c.locator('option').evaluateAll(ns=>ns.map(n=>n.value));await c.selectOption(opts.find(v=>v!==m.value)||m.value);}else if(m.type==='number')await c.fill(String(Math.min(Number(m.max)||1000,Number(m.value)+1)));visited.add(m.name);
   }
   if(key==='footer'){const radios=root.locator('[name="navigation[footerColumns]"]');for(const c of await radios.all()){await c.check();assert(await c.isChecked());visited.add(await c.getAttribute('name'));}await radios.first().check();}
   const picker=root.locator('[data-vf-navigation-copy-language='+key+']');for(const option of await picker.locator('option').all()){
    await picker.selectOption(await option.getAttribute('value'));for(const c of await root.locator('[data-vf-navigation-i18n-panel='+key+']:visible input').all()){const name=await c.getAttribute('name');await c.fill(name.endsWith('[ctaUrl]')?'/synthetic/cta/':'Synthetic '+name);visited.add(name);}
   }
  }
 }
 const expected=await snapshot();const saved=await confirmed();await go();assert.deepEqual(await snapshot(),expected,'saved controls differ after reload');functional.all_controls_save_reload='PASS';functional.all_five_frontend_consumers='PASS';
 // Check public HTML consumes the canonical menu bindings and responsive variables.
 const front=await context.newPage();await front.goto(base+'/');const attrs=await front.locator('#vf-site-header').evaluate(n=>({...n.dataset}));assert.equal(Number(attrs.vfHeaderMenuId),saved.data.navigation.headerMenu);assert.equal(Number(attrs.vfMobileBreakpoint),saved.data.navigation.mobileBreakpoint);assert.equal(await front.locator('#vf-mobile-nav').getAttribute('data-vf-mobile-menu-id'),String(saved.data.navigation.mobileMenu));const css=await front.locator('html').evaluate(n=>({height:getComputedStyle(n).getPropertyValue('--vf-header-height').trim(),columns:getComputedStyle(n).getPropertyValue('--vf-footer-columns').trim()}));assert.equal(parseInt(css.height),saved.data.navigation.shell.header.height);assert.equal(parseInt(css.columns),saved.data.navigation.footerColumns);await front.close();functional.public_html_consumers='PASS';
 await confirmed();functional.idempotent_verify='PASS';await go();await tab('header').click();const before=await snapshot();await cta.fill('Synthetic discard');await root.locator('[data-vf-navigation-discard]').click();assert.deepEqual(await snapshot(),before);assert(!await save.isVisible());functional.discard_draft='PASS';
 await cta.fill('Synthetic isolated save');let release;const held=new Promise(r=>release=r);let requests=0;await page.route('**/admin-ajax.php',async r=>{requests++;const response=await r.fetch();await held;await r.fulfill({response});});const requested=page.waitForRequest(r=>r.url().includes('admin-ajax.php'));await save.click();await requested;
 assert(await root.locator('input,select,textarea,button').evaluateAll(ns=>ns.every(n=>n.disabled)),'busy editor is not isolated');assert(await root.locator('a').evaluateAll(ns=>ns.every(n=>n.getAttribute('aria-disabled')==='true')));await root.locator('form').evaluate(n=>n.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.equal(requests,1);release();await settled();await page.unroute('**/admin-ajax.php');assert(!await save.isVisible());functional.busy_controls_and_double_submit='PASS';
 for(const scenario of ['network','invalid_json','incomplete','missing_navigation','missing_revision','missing_stage','missing_consumer','http','timeout']){
  await go();await tab('header').click();await cta.fill('Synthetic retained '+scenario);const draft=await snapshot(),revision=await root.locator('[data-vf-navigation-revision]').inputValue(),baseCopy=await root.locator('[data-vf-navigation-base]').inputValue();
  if(scenario==='timeout')await page.evaluate(()=>{const original=window.setTimeout;window.syntheticTimeoutOriginal=original;window.setTimeout=(fn,delay,...args)=>original(fn,delay===20000?50:delay,...args);});
  await page.route('**/admin-ajax.php',async r=>{
   if(scenario==='network')return r.abort('failed');if(scenario==='invalid_json')return r.fulfill({body:'<html>invalid</html>'});if(scenario==='timeout'){await new Promise(resolve=>setTimeout(resolve,200));return r.abort('timedout').catch(()=>{});}
   if(scenario==='http'||scenario==='incomplete')return r.fulfill({status:scenario==='http'?503:200,json:{success:true,data:{}}});
   // Use a real idempotent readback as a seed, then remove one required field.
   const params=new URLSearchParams(r.request().postData());const cfg=await page.evaluate(()=>VF_THEME_NAVIGATION);const fields=await root.locator('[data-vf-navigation-base]').inputValue();const nav=JSON.parse(fields);
   const payload={success:true,data:{ok:true,readback:true,revision,stages:{validate:'passed',execute:'skipped',readback:'passed',verify:'passed'},navigation:nav,runtimeVerification:cfg.runtimeVerification}};
   if(scenario==='missing_navigation')delete payload.data.navigation.shell.footer.partnerArea;if(scenario==='missing_revision')delete payload.data.revision;if(scenario==='missing_stage')delete payload.data.stages.readback;if(scenario==='missing_consumer')delete payload.data.runtimeVerification.checks.mobile;
   await r.fulfill({json:payload});
  });await save.click();await root.locator('[data-vf-navigation-error-summary]').waitFor();await settled();assert.deepEqual(await snapshot(),draft);assert.equal(await root.locator('[data-vf-navigation-revision]').inputValue(),revision);assert.equal(await root.locator('[data-vf-navigation-base]').inputValue(),baseCopy);assert.equal(await root.getAttribute('data-vf-navigation-save-result'),'unknown');assert.equal(await root.getAttribute('data-vf-navigation-dirty'),'1');assert(await cta.isEnabled());assert((await root.locator('[data-vf-navigation-runtime-summary]').innerText()).includes('尚未确认'));await page.unroute('**/admin-ajax.php');if(scenario==='timeout')await page.evaluate(()=>window.setTimeout=window.syntheticTimeoutOriginal);await confirmed();functional[scenario+'_retained_retry']='PASS';
 }
 await go();const other=await context.newPage();other.on('dialog',d=>d.accept());await other.goto(url);const revision=await root.locator('[data-vf-navigation-revision]').inputValue();await other.locator('[data-vf-navigation-workflow-step=header]').click();await other.locator('[data-vf-navigation-i18n-panel=header]:visible input').first().fill('Synthetic concurrent winner');assert((await send(other)).success);await tab('header').click();await cta.fill('Synthetic conflicting draft');for(let i=0;i<2;i++){const p=await send();assert(!p.success&&p.data.failureCode==='REVISION_CONFLICT');assert.equal(await root.locator('[data-vf-navigation-revision]').inputValue(),revision);assert.equal(await cta.inputValue(),'Synthetic conflicting draft');}await other.reload();await other.locator('[data-vf-navigation-workflow-step=header]').click();assert.equal(await other.locator('[data-vf-navigation-i18n-panel=header]:visible input').first().inputValue(),'Synthetic concurrent winner');functional.repeated_conflict_no_overwrite='PASS';
 await go();await other.goto(url);const oldMenu=await root.locator('[data-vf-navigation-menu=headerMenu]').inputValue();const options=await other.locator('[data-vf-navigation-menu=headerMenu] option').evaluateAll(ns=>ns.map(n=>n.value).filter(v=>Number(v)>0));const newMenu=options.find(v=>v!==oldMenu);assert(newMenu);await other.locator('[data-vf-navigation-menu=headerMenu]').selectOption(newMenu);assert((await send(other)).success);await tab('footer').click();const copy=root.locator('[data-vf-navigation-i18n-panel=footer]:visible input').last();await copy.fill('Synthetic safe rebase');const rebased=await confirmed();assert.equal(rebased.data.navigation.headerMenu,Number(newMenu));assert.equal(await root.locator('[data-vf-navigation-menu=headerMenu]').inputValue(),newMenu);await go();assert.equal(await root.locator('[data-vf-navigation-menu=headerMenu]').inputValue(),newMenu);await other.close();functional.safe_rebase_projects_readback='PASS';
 await tab('header').click();const ctaUrl=root.locator('[data-vf-navigation-i18n-panel=header]:visible [data-vf-navigation-cta-url]');await ctaUrl.fill('javascript:alert(1)');let network=0;const listener=r=>{if(r.url().includes('admin-ajax.php'))network++;};page.on('request',listener);await save.click();assert(await root.locator('[data-vf-navigation-error-summary]').isVisible());assert.equal(network,0);page.off('request',listener);functional.invalid_url_blocked='PASS';await go();
 const cfg=await page.evaluate(()=>({url:VF_THEME_NAVIGATION.ajaxUrl,nonce:VF_THEME_NAVIGATION.nonce})),fields=await root.locator('form').evaluate(n=>Object.fromEntries(new FormData(n)));fields.action='vf_theme_navigation_save';fields.nonce=cfg.nonce;const denied=await context.request.post(cfg.url,{form:{...fields,nonce:'invalid-synthetic'}});assert.equal(denied.status(),403);assert.equal((await denied.json()).data.failureCode,'NONCE_INVALID');const guest=await browser.newContext();const out=await guest.request.post(cfg.url,{form:fields});assert(out.status()>=400||(await out.text()).trim()==='0');await guest.close();functional.nonce_guest_rejected='PASS';
 const nativeFields=await root.locator('form').evaluate(n=>new URLSearchParams([...new FormData(n)]).toString());const native=await context.request.post(base+'/wp-admin/admin-post.php',{data:nativeFields,headers:{'content-type':'application/x-www-form-urlencoded'},maxRedirects:0});assert.equal(native.status(),302);assert(native.headers().location.includes('navigation-saved'));functional.native_post='PASS';
 assert.deepEqual(errors,[]);fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'PASS',checks,functional,editable_fields:visited.size,visited:[...visited],errors},null,2));await browser.close();console.log('NAVIGATION_NATIVE_BROWSER=PASS fields='+visited.size);
})().catch(async e=>{fs.writeFileSync('proof/failure.json',JSON.stringify({status:'FAIL',message:String(e)},null,2));if(global.proofPage)await global.proofPage.screenshot({path:'proof/navigation-failure.png',fullPage:true}).catch(()=>{});console.error(e);process.exit(1);});
