'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const check=require('../target/tests/seo-controls-browser-check'),base='http://127.0.0.1:18880',url=base+'/wp-admin/themes.php?page=vf-theme-modules&tab=seo';
const cli=php=>execFileSync('docker',['exec','--user','www-data','vf-v8-'+process.env.GITHUB_RUN_ID+'-wp','php','/usr/local/bin/wp','eval',php,'--path=/var/www/html'],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
let page;
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext();page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill('admin');await page.locator('#user_pass').fill('Synthetic-Only-Update-54!');await Promise.all([page.waitForURL(/wp-admin/),page.locator('#wp-submit').click()]);
 const checks=[];for(const width of [1920,1440,1319,1024,768,390]){await page.setViewportSize({width,height:1000});await page.goto(url);await page.evaluate(()=>document.fonts.ready);checks.push(await check(page,{width,out:path.resolve('proof')}));}
 await page.setViewportSize({width:1440,height:1000});await page.goto(url);
 const root=page.locator('[data-vf-seo-form-shell]'),form=root.locator('form'),save=root.locator('[data-vf-seo-save]'),active=root.locator('[data-vf-seo-route-row]:visible'),input=active.locator('[data-key=pathPattern]');
 await input.fill('tools-proof');await active.locator('[data-key=canonicalPolicy]').selectOption('none');await active.locator('[data-key=hreflangPolicy]').selectOption('none');await active.locator('[data-key=indexability]').selectOption('noindex_follow');await active.locator('[data-key=staticPathPolicy]').selectOption('exclude');
 let release;const gate=new Promise(r=>release=r);await page.route('**/admin-ajax.php',async route=>{await gate;await route.continue();});
 const response=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST');await save.click();await page.waitForFunction(()=>document.querySelector('[data-vf-seo-form-shell]').getAttribute('aria-busy')==='true');
 assert.equal(await form.locator('select:not(:disabled),input[type=text]:not(:disabled)').count(),0,'edit race while saving');assert(await root.locator('[data-vf-seo-add-route]').isDisabled());await page.screenshot({path:'proof/seo-saving-1440.png',fullPage:true});release();
 const saved=await response,payload=await saved.json();assert(saved.ok()&&payload.success&&payload.data.ok,JSON.stringify(payload));await page.waitForFunction(()=>document.querySelector('[data-vf-seo-form-shell]').getAttribute('aria-busy')==='false');assert.equal(await save.isVisible(),false);await page.unroute('**/admin-ajax.php');
 const toast=await root.locator('[data-vf-seo-toast]').evaluate(n=>{const b=n.getBoundingClientRect();return{height:b.height,top:b.top,bottom:b.bottom,viewport:innerHeight};});assert(toast.height<=140&&toast.top>=0&&toast.bottom<=toast.viewport,'success toast obstructs editor');await page.screenshot({path:'proof/seo-saved-toast-1440.png',fullPage:true});
 await root.locator('.vf-seo-professional summary').click();assert.equal(await root.locator('[data-vf-seo-visible-revision]').innerText(),payload.data.revision.slice(0,10));
 await input.fill('temporary-after-save');await root.locator('[data-vf-seo-discard]').click();assert.equal(await input.inputValue(),'tools-proof','discard did not restore latest saved values');assert.equal(await input.isDisabled(),false,'saved snapshot retained disabled state');
 await page.reload();assert.equal(await input.inputValue(),'tools-proof');assert.equal(await active.locator('[data-key=canonicalPolicy]').inputValue(),'none');assert.equal(await active.locator('[data-key=staticPathPolicy]').inputValue(),'exclude');
 await input.fill('unsaved-network-draft');await page.route('**/admin-ajax.php',route=>route.abort('failed'));await save.click();await root.locator('[data-vf-seo-error-summary]:visible').waitFor();assert.equal(await input.inputValue(),'unsaved-network-draft');assert.equal(await input.isDisabled(),false);assert(await save.isVisible());assert.equal(await root.locator('[data-vf-seo-toast]').isVisible(),false,'error toast covers inputs');assert.equal(await root.locator('[data-vf-seo-error-list] li').count(),0,'duplicates generic error');await page.screenshot({path:'proof/seo-network-error-1440.png',fullPage:true});await page.unroute('**/admin-ajax.php');await root.locator('[data-vf-seo-discard]').click();assert.equal(await input.inputValue(),'tools-proof');
 await input.fill('unsaved-conflict-draft');await form.locator('[name=revision]').evaluate(n=>n.value='0'.repeat(64));const rejected=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST');await save.click();assert.equal((await rejected).status(),409);await root.locator('[data-vf-seo-error-summary]:visible').waitFor();assert.equal(await input.inputValue(),'unsaved-conflict-draft');await page.screenshot({path:'proof/seo-conflict-1440.png',fullPage:true});await page.reload();
 const cfg=await page.evaluate(()=>({ajaxUrl:window.VFThemeSeo.ajaxUrl,nonce:window.VFThemeSeo.nonce})),fields=await form.evaluate(n=>Object.fromEntries(new FormData(n)));fields.action='vf_theme_seo_save';fields.nonce=cfg.nonce;
 const invalid=await context.request.post(cfg.ajaxUrl,{form:{...fields,'seo[virtualRoutePolicy][0][canonicalPolicy]':'invalid-policy'}});assert.equal(invalid.status(),422);assert.equal((await invalid.json()).data.failureCode,'VALIDATION_FAILED');
 const csrf=await context.request.post(cfg.ajaxUrl,{form:{...fields,nonce:'invalid-nonce'}});assert(csrf.status()>=400);const anon=await browser.newContext(),denied=await anon.request.post(cfg.ajaxUrl,{form:fields});assert(denied.status()>=400||await denied.text()==='0');await anon.close();
 cli('vf_theme_bootstrap_require_many(require get_template_directory()."/inc/bootstrap/manifests/admin-tabs/seo.php");$s=theme_seo_readback()["seo"];if($s["virtualRoutePolicy"][0]["pathPattern"]!=="tools-proof"||$s["virtualRoutePolicy"][0]["canonicalPolicy"]!=="none"||$s["previewIndexability"]!=="noindex_follow"||$s["notFoundRobots"]!=="noindex_follow"){throw new Exception("database persistence or draft preservation mismatch");}');
 const native=await browser.newContext({javaScriptEnabled:false,storageState:await context.storageState()}),np=await native.newPage();await np.goto(url);await np.locator('[data-vf-seo-route-row]').first().locator('[data-key=canonicalPolicy]').selectOption('self');await Promise.all([np.waitForURL(/vf_theme_notice=seo-saved/),np.locator('[data-vf-seo-save]').click()]);assert.equal(await np.locator('[data-vf-seo-route-row]').first().locator('[data-key=canonicalPolicy]').inputValue(),'self');await native.close();
 // A controlled option-read dependency fault exercises the real verification engine.
 cli('$dir=WP_CONTENT_DIR."/mu-plugins";if(!is_dir($dir))mkdir($dir);file_put_contents($dir."/vf-seo-proof.php",\'<?php add_filter("option_vf_theme_seo",function($v){static $reads=0;if(isset($_GET["vf_seo_test_failure"])&&is_array($v)){$v["virtualRoutePolicy"][0]["pathPattern"]="runtime-fault-".(++$reads);}return $v;});\');');
 await page.goto(url+'&vf_seo_test_failure=1');await root.locator('[data-vf-seo-runtime-issues]:visible').waitFor();assert.equal(await root.locator('details[open]').count(),0,'failure forced whole diagnostics open');await input.fill('draft-with-runtime-failure');assert(await root.locator('[data-vf-seo-runtime-issues]').isVisible(),'editing hid real failure');await page.screenshot({path:'proof/seo-runtime-failure-1440.png',fullPage:true});cli('unlink(WP_CONTENT_DIR."/mu-plugins/vf-seo-proof.php");');await page.goto(url);assert.equal(await root.locator('[data-vf-seo-runtime-issues]').isVisible(),false);
 assert.equal(errors.length,0,JSON.stringify(errors));fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'PASS',wordpress_integration:'REAL_ISOLATED_WORDPRESS',checks,persistence:'PASS',invalid_contract:'PASS',csrf:'PASS',guest:'PASS',revision_conflict:'PASS',network_failure:'PASS',busy_lock:'PASS',native_post:'PASS',runtime_failure_visible:'PASS',errors},null,2));await browser.close();
})().catch(async error=>{if(page)await page.screenshot({path:'proof/seo-failure.png',fullPage:true}).catch(()=>{});fs.writeFileSync('proof/failure.json',JSON.stringify({status:'FAIL',message:error.message}));console.error(error);process.exit(1)});
