'use strict';
const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
const {cli,load,state,base,url,login,sample}=require('./common');
const checkPreviewControls=require('../target/tests/preview-controls-browser-check.js');
const tests=[],checks=[],errors=[];
const test=(name,ok=true)=>{assert(ok,name);tests.push({name,status:'PASS'});};
const root='[data-vf-preview-page]',run='[data-vf-preview-run]',pause='[data-vf-preview-pause]',resume='[data-vf-preview-resume]',stop='[data-vf-preview-stop]';
const ready=async p=>{await p.goto(url);await p.waitForFunction(()=>document.querySelector('[data-vf-preview-page]')?.dataset.scriptReady==='1');};
const idle=async p=>p.waitForFunction(()=>document.querySelector('[data-vf-preview-run]').disabled===false,{},{timeout:90000});
const settled=async p=>p.waitForFunction(()=>['paused','stopped','fail','blocked','review','pass'].includes(document.querySelector('[data-vf-preview-page]').dataset.state),{},{timeout:90000});
(async()=>{
 const backend=JSON.parse(cli(load+`$tests=[];$r=vf_theme_preview_workbench_create_job(['mode'=>'quick','revision'=>vf_theme_preview_revision()],1);$id=$r['job']['runId'];$lock=vf_theme_acceptance_state_acquire_step($id,1);$p=vf_theme_preview_workbench_control($id,'pause',1,0);$tests['control_respects_batch_lock']=empty($p['ok'])&&$p['failureCode']==='STEP_LOCKED';vf_theme_acceptance_state_release_step($id,$lock['token']);$p=vf_theme_preview_workbench_control($id,'pause',1,0);$tests['pause_persisted']=$p['ok']&&$p['job']['status']==='paused';$s=vf_theme_preview_workbench_step($id,1,0);$tests['stale_epoch_rejected']=empty($s['ok'])&&$s['failureCode']==='STALE_CONTROL_EPOCH';$s=vf_theme_preview_workbench_control($id,'resume',2,1);$tests['foreign_owner_rejected']=empty($s['ok'])&&$s['failureCode']==='PERMISSION_DENIED';$s=vf_theme_preview_workbench_control($id,'resume',1,1);$tests['resume_same_run']=$s['ok']&&$s['job']['runId']===$id;$s=vf_theme_preview_workbench_control($id,'stop',1,2);$tests['stop_partial_saved']=$s['ok']&&$s['job']['status']==='stopped'&&$s['artifact']['status']==='stopped';$s=vf_theme_preview_workbench_control($id,'resume',1,3);$tests['terminal_cannot_reopen']=empty($s['ok'])&&$s['failureCode']==='CONTROL_STATE_INVALID';echo wp_json_encode($tests);`));
 for(const [k,v]of Object.entries(backend))test(k,v);
 const modes=JSON.parse(cli(load+`$out=[];foreach(array_keys(vf_theme_preview_workbench_modes()) as $mode){$r=vf_theme_preview_workbench_create_job(['mode'=>$mode,'speed'=>'normal','revision'=>vf_theme_preview_revision()],1);if(empty($r['ok'])){throw new Exception('mode create failed: '.$mode);}$job=$r['job'];$out[$mode]=$job['mode']===$mode&&($mode==='quick'||$job['total']>0);$s=vf_theme_preview_workbench_step($job['runId'],1,$job['controlEpoch']);if(empty($s['ok'])){throw new Exception('mode foundation failed: '.$mode);}if(in_array($s['job']['status'],['running','paused'],true)||!empty($s['job']['browserPending'])){vf_theme_preview_workbench_control($job['runId'],'stop',1,$s['job']['controlEpoch']);}}echo wp_json_encode($out);`));
 for(const [k,v]of Object.entries(modes))test('actual_mode_start_foundation_'+k,v);

 const uiSnapshot=cli(load+'$keys=[vf_theme_preview_workbench_history_key(),vf_theme_acceptance_state_latest_job_key(),vf_theme_acceptance_state_latest_artifact_key()];$snapshot=[];foreach($keys as $key){$snapshot[$key]=get_option($key,null);delete_option($key);}echo wp_json_encode($snapshot);');
 const b=await chromium.launch(),c=await b.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai'}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await login(p);
 for(const width of [1920,1440,1319,1024,768,390]){await p.setViewportSize({width,height:1000});await ready(p);await checkPreviewControls(p,{width,out:'proof'});await p.locator('[data-vf-preview-workflow-step=scope]').click();await p.locator('[data-vf-preview-target-open]').click();test('dialog_background_inert_'+width,await p.evaluate(()=>document.querySelector('#adminmenumain')?.inert||document.querySelector('#wpwrap')?.inert||[...document.querySelectorAll('[inert]')].length>0));await p.keyboard.press('Escape');checks.push({width,status:'PASS'});}
 cli(load+'$rows=json_decode(base64_decode('+JSON.stringify(Buffer.from(uiSnapshot).toString('base64'))+'),true);foreach($rows as $key=>$value){if($value===null){delete_option($key);}else{update_option($key,$value,false);}}');
 await p.setViewportSize({width:1440,height:1000});await ready(p);await p.locator('[data-vf-preview-mode]').selectOption('quick');await p.locator('.vf-preview-v510__execution-options > summary').click();await p.locator('[data-vf-preview-speed]').selectOption('safe');await p.locator('.vf-preview-v510__execution-options > summary').click();
 const cfg=await p.evaluate(()=>({nonce:VFThemePreview.nonce,revision:VFThemePreview.revision}));const denied=await c.request.post(base+'/wp-admin/admin-ajax.php',{form:{action:'vf_theme_preview_run',phase:'workbench_start',nonce:'invalid',revision:cfg.revision,mode:'quick'}});test('nonce_rejected',!denied.ok()||(await denied.json()).success===false);
 let held=false,release,stepEntered;const gate=new Promise(r=>release=r),entered=new Promise(r=>stepEntered=r);let controls=0;
 await p.route('**/admin-ajax.php',async r=>{const data=new URLSearchParams(r.request().postData()||'');if(data.get('phase')==='workbench_control')controls++;if(data.get('phase')==='workbench_step'&&!held){held=true;stepEntered();await gate;}await r.continue();});
 await p.locator(run).click();await entered;const runId=state().runId;await p.locator(pause).click();test('pause_pending_controls_locked',await p.locator(pause).isDisabled()&&await p.locator(stop).isDisabled());await p.locator(pause).dispatchEvent('click');release();await p.waitForFunction(()=>document.querySelector('[data-vf-preview-page]').dataset.state==='paused');test('one_pause_request',controls===1);test('pause_same_run_saved',state().runId===runId&&state().status==='paused');await p.screenshot({path:'proof/preview-paused-1440.png',fullPage:true});
 await p.unroute('**/admin-ajax.php');await p.reload();await p.waitForFunction(()=>document.querySelector('[data-vf-preview-page]')?.dataset.scriptReady==='1');test('reload_recovers_pending_job',await p.locator(resume).isVisible()&&await p.locator(run).isDisabled());await p.locator(resume).click();await idle(p);test('resume_completes_same_run',state().runId===runId&&state().status==='complete');
 const download=await Promise.all([p.waitForEvent('download'),p.locator('[data-vf-preview-download]').click()]);const path=await download[0].path();const artifact=JSON.parse(fs.readFileSync(path,'utf8'));test('download_matches_server',artifact.runId===runId&&artifact.hash===state().artifact.hash);test('history_immediate',await p.locator('[data-vf-preview-history]').innerText().then(s=>s.includes('快速门禁')));await p.screenshot({path:'proof/preview-results-1440.png',fullPage:true});
 await ready(p);await p.locator('[data-vf-preview-mode]').selectOption('quick');await p.route('**/admin-ajax.php',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({success:true,data:{ok:true}})}));await p.locator(run).click();await idle(p);test('incomplete_success_rejected',await p.locator('[data-vf-preview-verdict-title]').innerText().then(s=>s.includes('不完整')));test('failed_start_preserves_scope',await p.locator('[data-vf-preview-mode]').inputValue()==='quick');await p.unroute('**/admin-ajax.php');
 await p.locator('[data-vf-preview-workflow-step=scope]').click();let failOnce=true;await p.route('**/admin-ajax.php',r=>{const phase=new URLSearchParams(r.request().postData()||'').get('phase');if(phase==='workbench_step'&&failOnce){failOnce=false;return r.abort('failed');}return r.continue();});await p.locator(run).click();await p.waitForFunction(()=>document.querySelector('[data-vf-preview-page]').dataset.state==='fail');test('failed_batch_keeps_recovery',await p.locator(resume).isVisible()&&await p.locator(stop).isEnabled());const failedId=state().runId;await p.unroute('**/admin-ajax.php');await p.locator(resume).click();await idle(p);test('network_retry_resumes_same_job',state().runId===failedId&&state().status==='complete');
 await ready(p);await p.locator('[data-vf-preview-mode]').selectOption('quick');await p.locator(run).click();await p.waitForFunction(()=>document.querySelector('[data-vf-preview-stop]').hidden===false);await p.locator(stop).click();await idle(p);test('stop_persisted_and_downloadable',state().status==='stopped'&&await p.locator('[data-vf-preview-download]').isVisible());
 // Use real server scans and the real frontend DOM. Stop once sampling starts;
 // no fabricated browser evidence or false all-product PASS is permitted.
 await ready(p);await p.locator('[data-vf-preview-mode]').selectOption('sample');await p.locator('.vf-preview-v510__execution-options > summary').click();await p.locator('[data-vf-preview-speed]').selectOption('fast');await p.locator('.vf-preview-v510__execution-options > summary').click();await p.locator(run).click();await p.waitForFunction(()=>document.querySelector('[data-vf-preview-frame]')?.getAttribute('src')?.includes('vf_theme_preview_acceptance'),{},{timeout:180000});await p.locator('[data-vf-preview-workflow-step=results]').click();await p.waitForTimeout(800);test('sampling_keeps_selected_tab',await p.locator(root).getAttribute('data-vf-preview-active-workflow')==='results');test('browser_pending_not_complete',await p.locator(run).isDisabled()&&await p.locator('[data-vf-preview-download]').isHidden());await p.locator(pause).click();await p.waitForFunction(()=>document.querySelector('[data-vf-preview-page]').dataset.state==='paused');test('browser_sampling_pause_saved',state().status==='paused'&&state().browserPending===true);await p.locator(resume).click();await idle(p);test('actual_browser_evidence_persisted',state().status==='complete'&&state().artifact.evidenceState.browser==='complete');
 test('real_matrix_rows',state().artifact.rows.length>0);test('truthful_result',!['pending','running'].includes(state().artifact.status));await p.screenshot({path:'proof/preview-browser-results-1440.png',fullPage:true});
 await sample(p);await sample(p);const samples=[];for(let i=0;i<5;i++)samples.push(await sample(p));const before=JSON.parse(fs.readFileSync('proof/baseline.json')).performance.samples;const med=(a,k)=>a.map(x=>x[k]).sort((x,y)=>x-y)[Math.floor(a.length/2)];test('bounded_dom_performance',med(samples,'nodes')<=med(before,'nodes')*1.5+150);fs.writeFileSync('proof/performance.json',JSON.stringify({status:'PASS',dataset:'same isolated WordPress catalogue, task histories naturally added',baseline:before,candidate:samples},null,2));test('no_page_errors',errors.length===0);
 fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'PASS',checks,tests,errors,real_wordpress:true,owner_real_use:'POST_PRODUCTION_REQUIRED'},null,2));await b.close();
})().catch(e=>{fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'FAIL',checks,tests,errors,error:e.message},null,2));console.error(e);process.exit(1)});
