from pathlib import Path

script = Path(__file__).with_name('temp-s01-c02-v121814-build.py').read_text()
old = '''old="    $state = vf_ops_s01_static_source_recovery_v2_state_v121814();\\n    $jobId = preg_replace('/[^a-z0-9_\\\\-]/i', '', (string)($state['jobId'] ?? ''));"\nnew="    $record = vf_ops_s01_static_source_recovery_v2_record_v121814();\\n    $activeId = preg_replace('/[^a-z0-9_\\\\-]/i', '', (string)($record['active_release_job'] ?? $record['candidate_async_job'] ?? ''));\\n    if ($activeId !== '') {\\n        $activeJob = VF_Ops_Release_Async_Job::load($activeId);\\n        $activeSource = is_array($activeJob) ? trim((string)($activeJob['source_path'] ?? '')) : '';\\n        if ($activeSource !== '' && is_file($activeSource) && is_readable($activeSource)) {\\n            vf_ops_s01_static_source_recovery_v2_store_marker_v121814('current','CURRENT_SOURCE_AVAILABLE','current_active_job',1,0,true,true,'');\\n            return ['status'=>'PASS','code'=>'CURRENT_SOURCE_AVAILABLE'];\\n        }\\n    }\\n\\n    $state = vf_ops_s01_static_source_recovery_v2_state_v121814();\\n    $jobId = preg_replace('/[^a-z0-9_\\\\-]/i', '', (string)($state['jobId'] ?? ''));"\nif s.count(old)!=1: raise SystemExit('current source anchor mismatch')\ns=s.replace(old,new,1)'''
new = '''anchor="    $state = vf_ops_s01_static_source_recovery_v2_state_v121814();"\ninsert="    $record = vf_ops_s01_static_source_recovery_v2_record_v121814();\\n    $activeId = preg_replace('/[^a-z0-9_\\\\-]/i', '', (string)($record['active_release_job'] ?? $record['candidate_async_job'] ?? ''));\\n    if ($activeId !== '') {\\n        $activeJob = VF_Ops_Release_Async_Job::load($activeId);\\n        $activeSource = is_array($activeJob) ? trim((string)($activeJob['source_path'] ?? '')) : '';\\n        if ($activeSource !== '' && is_file($activeSource) && is_readable($activeSource)) {\\n            vf_ops_s01_static_source_recovery_v2_store_marker_v121814('current','CURRENT_SOURCE_AVAILABLE','current_active_job',1,0,true,true,'');\\n            return ['status'=>'PASS','code'=>'CURRENT_SOURCE_AVAILABLE'];\\n        }\\n    }\\n\\n" + anchor\nif anchor not in s: raise SystemExit('current source anchor missing')\ns=s.replace(anchor,insert,1)'''
if old not in script:
    raise SystemExit('wrapper patch anchor mismatch')
script = script.replace(old, new, 1)
exec(compile(script, 'temp-s01-c02-v121814-build-patched.py', 'exec'))
