'use strict';
const {chromium}=require('playwright');
const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');
const {execFileSync}=require('child_process');
const base='http://127.0.0.1:18880',url=base+'/wp-admin/themes.php?page=vf-theme-modules&tab=recovery';
const cli=php=>execFileSync('docker',['exec','--user','www-data',process.env.WP,'php','/usr/local/bin/wp','eval',php,'--path=/var/www/html'],{encoding:'utf8',maxBuffer:16*1024*1024});
const boot='vf_theme_bootstrap_require_many(require get_template_directory()."/inc/bootstrap/manifests/admin-tabs/recovery.php");';
const stores=()=>JSON.parse(cli(boot+'echo wp_json_encode(vf_theme_recovery_current_stores());'));
const policy=()=>JSON.parse(cli(boot+'echo wp_json_encode(vf_theme_recovery_readback()["settings"]);'));
const points=()=>JSON.parse(cli(boot+'echo wp_json_encode(vf_theme_revision_store());'));
const output=(name,data)=>fs.writeFileSync('proof/'+name,JSON.stringify(data,null,2));
async function login(page){await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill('admin');await page.locator('#user_pass').fill('Synthetic-Only-Update-54!');await Promise.all([page.waitForURL(/wp-admin/),page.locator('#wp-submit').click()]);}
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',acceptDownloads:true}),page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
 const cases=[],pass=name=>{cases.push({name,status:'PASS'});console.log('BACKUP_CASE '+name);output('backup-workflow-progress.json',{status:'RUNNING',cases});};
 try{
  await login(page);await page.goto(url);
  const root=()=>page.locator('[data-vf-recovery-page]'),pick=s=>root().locator('[data-vf-recovery-'+s+']'),primary=()=>pick('primary');
  const idle=()=>page.waitForFunction(()=>document.querySelector('[data-vf-recovery-page]').getAttribute('aria-busy')==='false');
  const task=async key=>root().locator('[data-vf-recovery-workflow-step='+key+']').click();
  const ajax=async(action,click)=>{const [response]=await Promise.all([page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().postData()?.includes(action)),click()]);const d=await response.json();await idle();assert.equal(d.success,true,JSON.stringify(d));return d.data;};
  const initial=stores(),initialPolicy=policy();assert.equal(points().length,0);assert(await primary().isEnabled());pass('zero-point healthy initial state');
  const rows=[];
  for(const width of [1920,1440,1319,1024,768,390]){
   await page.setViewportSize({width,height:1000});await page.goto(url);rows.push(await require('../target/tests/recovery-controls-browser-check.js')(page,width));
   for(const key of ['status','export','import','restore']){await task(key);await page.screenshot({path:'proof/backup-'+key+'-'+width+'.png',fullPage:true});}
   console.log('REAL_BACKUP_WIDTH_COMPLETE '+width);
  }
  output('backup-controls.json',{status:'PASS',rows,production:'NOT_EXECUTED'});assert.deepEqual(stores(),initial);assert.deepEqual(policy(),initialPolicy);assert.equal(points().length,0);pass('all six-width controls and keyboard are read-only');
  await page.setViewportSize({width:1440,height:1000});await page.goto(url);
  output('backup-request-failures.json',await require('../target/tests/recovery-request-browser-check.js')(page));assert.deepEqual(stores(),initial);assert.deepEqual(policy(),initialPolicy);assert.equal(points().length,0);pass('timeouts malformed responses and source races preserve state');
  await page.goto(url);const created=await ajax('vf_theme_recovery_snapshot_ajax',()=>primary().click());assert(created.snapshotId);assert.equal(points().length,1);assert.equal(points()[0].id,created.snapshotId);assert.deepEqual(stores(),initial);assert.equal(await pick('record-count').innerText(),'1');pass('first snapshot actual DB persistence and no-reload count');
  await task('restore');assert(await root().locator('[data-vf-recovery-form=restore]').isVisible());await pick('picker-open').click();assert.equal(await pick('revision-choice').count(),1);await pick('revision-choice').check();await pick('picker-apply').click();const firstId=await pick('revision-id').inputValue();assert.equal(firstId,created.snapshotId);assert(await primary().isDisabled());pass('first snapshot immediately selectable and confirmation required');
  await pick('picker-open').click();await pick('picker-search').fill('no-such-synthetic-point');assert(await pick('picker-empty').isVisible());await pick('picker-search').fill('');await page.keyboard.press('Escape');assert.equal(await pick('revision-id').inputValue(),firstId);assert(await pick('picker-open').evaluate(n=>n===document.activeElement));pass('picker search empty cancel focus preserves committed choice');
  await task('export');const [download,exportResponse]=await Promise.all([page.waitForEvent('download'),ajax('vf_theme_recovery_export_ajax',()=>primary().click())]);const bytes=fs.readFileSync(await download.path()),payload=JSON.parse(bytes);assert.deepEqual(payload.stores,initial);assert.equal(Object.keys(payload.stores).length,7);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),exportResponse.download.sha256);assert.deepEqual(stores(),initial);pass('actual downloaded JSON seven stores hash and read-only export');
  await task('import');await pick('file').setInputFiles({name:'downloaded-backup.json',mimeType:'application/json',buffer:bytes});await page.waitForTimeout(250);const same=await ajax('vf_theme_recovery_preflight_ajax',()=>primary().click());assert.equal(same.totalChangedCount,0);assert(await primary().isDisabled());assert.deepEqual(stores(),initial);assert.deepEqual(policy(),initialPolicy);assert.equal(points().length,1);pass('own exported file upload exact no-change server preflight');
  await root().locator('[data-vf-recovery-source-mode][value=paste]').check();const changed=JSON.parse(bytes);changed.stores.brand.siteName='Synthetic Recovery New Name';changed.integrity.storesSha256=JSON.parse(cli(boot+'$e=vf_theme_export_config();$p=$e["payload"]; $p["stores"]["brand"]["siteName"]="Synthetic Recovery New Name"; echo wp_json_encode(vf_theme_recovery_hash($p["stores"]));'));
  await pick('json').fill(JSON.stringify(changed));await page.waitForTimeout(250);assert.equal(await pick('preflight-token').inputValue(),'');
  const beforePre=points().length;const pre=await ajax('vf_theme_recovery_preflight_ajax',()=>primary().click());assert(pre.totalChangedCount>0&&pre.token);assert.deepEqual(stores(),initial);assert.equal(points().length,beforePre);pass('changed paste preflight compares but never writes');
  await primary().click();assert(await root().locator('[data-vf-recovery-dialog=confirm]').isVisible());await page.keyboard.press('Escape');assert.deepEqual(stores(),initial);assert(await primary().evaluate(n=>n===document.activeElement));pass('import confirmation cancellation writes nothing');
  await root().locator('[name="recovery[retention]"]').fill('12');assert.equal(await pick('preflight-token').inputValue(),'');await ajax('vf_theme_recovery_preflight_ajax',()=>primary().click());const countBefore=points().length;await primary().click();const imported=await ajax('vf_theme_recovery_apply_ajax',()=>pick('confirm-apply').click());assert(imported.snapshotId);assert.equal(stores().brand.siteName,'Synthetic Recovery New Name');assert.equal(policy().retention,12);assert.equal(points().length,countBefore+1);assert(await pick('restore-next').isVisible());pass('confirmed import protection point actual write readback and consumers');
  await task('restore');await pick('picker-open').click();assert.equal(await pick('revision-choice').count(),points().length);const beforeSelection=await pick('revision-id').inputValue();await pick('revision-choice').first().check();await page.keyboard.press('Escape');assert.equal(await pick('revision-id').inputValue(),beforeSelection);pass('picker new selection cancellation does not change restored target');
  await pick('picker-open').click();await root().locator('[data-vf-recovery-revision-choice][value="'+firstId+'"]').check();await pick('picker-apply').click();await pick('confirm').fill('RESTORE');await primary().click();const restored=await ajax('vf_theme_recovery_restore_ajax',()=>pick('confirm-apply').click());assert(restored.snapshotId);assert.deepEqual(stores(),initial);assert.equal(policy().retention,12);assert(await pick('restore-next').isVisible());pass('actual restore protection and exact seven-store readback');
  await task('import');await root().locator('[name="recovery[retention]"]').fill('33');await task('restore');await root().locator('.vf-recovery-danger-zone > summary').click();await pick('default-open').click();await pick('default-confirm').fill('RESET_DEFAULTS');const reset=await ajax('vf_theme_recovery_defaults_ajax',()=>pick('default-apply').click());assert(reset.ok);assert.equal(policy().retention,12);assert(await pick('restore-next').isVisible());pass('actual defaults restore excludes unsaved import policy');
  await task('import');await root().locator('[data-vf-recovery-source-mode][value=paste]').check();await pick('json').fill(JSON.stringify(payload));await page.waitForTimeout(250);await ajax('vf_theme_recovery_preflight_ajax',()=>primary().click());if(await primary().isEnabled()){await primary().click();await ajax('vf_theme_recovery_apply_ajax',()=>pick('confirm-apply').click());}assert.deepEqual(stores(),initial);pass('defaults recovery re-import restores customized navigation');
  await page.goto(url);let release;const held=new Promise(r=>release=r);await page.route('**/wp-admin/admin-ajax.php',async route=>{await held;await route.continue();});await primary().click();await page.waitForFunction(()=>document.querySelector('[data-vf-recovery-page]').getAttribute('aria-busy')==='true');assert(await primary().isDisabled());assert(await root().locator('[data-vf-recovery-workflow-step=import]').isDisabled());assert(await root().locator('[name="recovery[retention]"]').isDisabled());release();await idle();await page.unroute('**/wp-admin/admin-ajax.php');pass('real slow request locks repeat writes tabs and policy inputs');
  const security=await page.evaluate(async()=>{const config=VFThemeRecovery;const b=new FormData();b.set('action',config.actions.snapshot);b.set('nonce','invalid');const r=await fetch(config.ajaxUrl,{method:'POST',body:b});return {http:r.status,data:await r.json()};});assert.equal(security.http,403);assert.equal(security.data.success,false);pass('actual HTTP invalid nonce rejected');
  const beforeNoAuth=stores();const anon=await browser.newContext();const denied=await anon.request.post(base+'/wp-admin/admin-ajax.php',{form:{action:'vf_theme_recovery_snapshot_ajax',nonce:'invalid'}});assert.equal(denied.status(),400);await anon.close();assert.deepEqual(stores(),beforeNoAuth);pass('unauthenticated actual request writes nothing');
  await page.goto(url);await task('restore');await page.screenshot({path:'proof/backup-real-restored-1440.png',fullPage:true});await page.setViewportSize({width:390,height:1000});await page.screenshot({path:'proof/backup-real-restored-390.png',fullPage:true});
  const nojs=await browser.newContext({javaScriptEnabled:false,acceptDownloads:true});await nojs.addCookies(await context.cookies());const native=await nojs.newPage();await native.goto(url);const [nativeDownload]=await Promise.all([native.waitForEvent('download'),native.locator('noscript button').click()]);assert.deepEqual(JSON.parse(fs.readFileSync(await nativeDownload.path())).stores,stores());await nojs.close();pass('no-JavaScript actual native form download');
  assert.deepEqual(errors,[]);output('backup-browser-errors.json',{status:'PASS',errors});output('backup-workflow.json',{status:'PASS',environment:'REAL_ISOLATED_WORDPRESS',cases,production:'NOT_EXECUTED'});
 }finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exit(1);});
