'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const check=require('../target/tests/preview-controls-browser-check'),base='http://127.0.0.1:18880',url=base+'/wp-admin/themes.php?page=vf-theme-modules&tab=preview';
const cli=php=>execFileSync('docker',['exec','--user','www-data','vf-v8-'+process.env.GITHUB_RUN_ID+'-wp','php','/usr/local/bin/wp','eval',php,'--path=/var/www/html'],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
let page;
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({acceptDownloads:true});page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill('admin');await page.locator('#user_pass').fill('Synthetic-Only-Update-54!');await Promise.all([page.waitForURL(/wp-admin/),page.locator('#wp-submit').click()]);
 cli('$dir=WP_CONTENT_DIR."/mu-plugins";if(!is_dir($dir))mkdir($dir);file_put_contents($dir."/vf-preview-proof.php",\'<?php add_action("send_headers",function(){if(!isset($_GET["vf_tools_preview"])||!function_exists("vf_tools_theme_preview_context"))return;$c=vf_tools_theme_preview_context();$p=$c["scope"]??[];$r=function_exists("vf_tools_theme_renderer_readback")?vf_tools_theme_renderer_readback():[];header("X-VF-Preview-Proof: ".base64_encode(wp_json_encode(["failure"=>$c["failureCode"]??"","locale"=>vf_tools_theme_projection_current_locale(),"signed_locale"=>$p["locale"]??"","route"=>vf_tools_theme_projection_current_route(),"signed_route"=>$p["route"]??"","profile_matches"=>($p["profile_revision"]??"")===($r["revision"]??"")])));},0);\');');
 const checks=[];for(const width of [1920,1440,1319,1024,768,390]){await page.setViewportSize({width,height:1000});await page.goto(url);await page.evaluate(()=>document.fonts.ready);checks.push(await check(page,{width,out:path.resolve('proof')}));}
 await page.setViewportSize({width:1440,height:1000});await page.goto(url);
 const root=page.locator('[data-vf-preview-page]'),run=root.locator('[data-vf-preview-run]');
 // Real start/step/finalization, retaining the engine's actual verdict.
 await root.locator('[data-vf-preview-mode]').selectOption('quick');let release;const gate=new Promise(r=>release=r);
 await page.route('**/admin-ajax.php',async route=>{if(new URLSearchParams(route.request().postData()).get('phase')==='workbench_start')await gate;await route.continue();});
 const start=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&new URLSearchParams(r.request().postData()).get('phase')==='workbench_start');await run.click();await page.waitForFunction(()=>document.querySelector('[data-vf-preview-page]').getAttribute('aria-busy')==='true');
 assert(await root.locator('[data-vf-preview-mode]').isDisabled());assert(await root.locator('[data-vf-preview-target-open]').isDisabled());assert.equal(await root.locator('[data-vf-preview-stop]').isVisible(),false);await page.screenshot({path:'proof/preview-starting-1440.png',fullPage:true});release();assert((await start).ok());await page.unroute('**/admin-ajax.php');
 await page.waitForFunction(()=>document.querySelector('[data-vf-preview-page]').getAttribute('aria-busy')==='false',{},{timeout:180000});assert(await root.locator('[data-vf-preview-results]').isVisible());assert(await root.locator('[data-vf-preview-download]').isVisible());
 const [download]=await Promise.all([page.waitForEvent('download'),root.locator('[data-vf-preview-download]').click()]);const artifact=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(artifact.mode,'quick');assert(artifact.runId&&artifact.hash);assert.equal(await root.locator('[data-vf-preview-summary] article').count(),4,'irrelevant live write statistics repeated');
 await page.screenshot({path:'proof/preview-completed-1440.png',fullPage:true});fs.writeFileSync('proof/preview-real-run.json',JSON.stringify({mode:artifact.mode,status:artifact.status,runId:artifact.runId,evidenceState:artifact.evidenceState,rows:artifact.rows.length,issues:artifact.issues.length,online_final_pass:false},null,2));
 await page.setViewportSize({width:390,height:1000});await page.screenshot({path:'proof/preview-completed-390.png',fullPage:true});
 for(const d of await root.locator('.vf-preview-v510__professional').all())await d.locator('summary').click();await page.screenshot({path:'proof/preview-expanded-390.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.goto(url);await root.locator('[data-vf-preview-mode]').selectOption('sample');await run.click();
 await page.waitForFunction(()=>document.querySelector('[data-vf-preview-page]').getAttribute('aria-busy')==='false',{},{timeout:240000});assert(await root.locator('[data-vf-preview-download]').isVisible());
 const [sampleDownload]=await Promise.all([page.waitForEvent('download'),root.locator('[data-vf-preview-download]').click()]);const sample=JSON.parse(fs.readFileSync(await sampleDownload.path(),'utf8'));assert.equal(sample.mode,'sample');assert(sample.rows.length>0);const breakpoints=sample.rawEvidence?.browserEvidence?.breakpoints||[];assert.equal(breakpoints.length,3,'real three-breakpoint collection missing');assert(breakpoints.every(b=>b.loaded&&b.viewportWidth===b.width),'preview viewport differs from selected breakpoint');
 await root.locator('[data-vf-preview-workflow-step="preview"]').click();const view=root.locator('[data-vf-preview-view-mode]');assert(await view.isEnabled());await view.click();assert.equal(await view.getAttribute('aria-pressed'),'true');await view.click();assert.equal(await view.getAttribute('aria-pressed'),'false');await page.screenshot({path:'proof/preview-live-frame-1440.png',fullPage:true});
 fs.writeFileSync('proof/preview-real-sample.json',JSON.stringify({mode:sample.mode,status:sample.status,runId:sample.runId,rows:sample.rows.length,issues:sample.issues.length,breakpoints:breakpoints.map(b=>({width:b.width,loaded:b.loaded,viewportWidth:b.viewportWidth,horizontalOverflow:b.horizontalOverflow})),online_final_pass:false},null,2));
 await root.locator('[data-vf-preview-workflow-step="results"]').click();await root.locator('.vf-preview-v510__matrix-details summary').click();await page.screenshot({path:'proof/preview-real-matrix-1440.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.goto(url);await root.locator('[data-vf-preview-mode]').selectOption('deep');await root.locator('.vf-preview-v510__execution-options summary').click();await root.locator('[data-vf-preview-speed]').selectOption('safe');
 const firstStep=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&new URLSearchParams(r.request().postData()).get('phase')==='workbench_step');await run.click();assert((await firstStep).ok());await root.locator('[data-vf-preview-pause]').click();await root.locator('[data-vf-preview-resume]:visible').waitFor();assert(await root.locator('[data-vf-preview-mode]').isDisabled());assert(await root.locator('[data-vf-preview-status]').innerText().then(s=>s.includes('暂停')));await page.screenshot({path:'proof/preview-paused-1440.png',fullPage:true});
 await root.locator('[data-vf-preview-workflow-step="preview"]').click();assert(await root.locator('[data-vf-preview-resume]').isVisible(),'running controls vanished on screen change');
 await root.locator('[data-vf-preview-resume]').click();await root.locator('[data-vf-preview-pause]:visible').waitFor();await root.locator('[data-vf-preview-stop]').click();await page.waitForFunction(()=>document.querySelector('[data-vf-preview-page]').getAttribute('aria-busy')==='false',{},{timeout:60000});assert(await root.locator('[data-vf-preview-mode]').isEnabled());assert(await root.locator('[data-vf-preview-status]').innerText().then(s=>s.includes('停止')));await page.screenshot({path:'proof/preview-stopped-1440.png',fullPage:true});
 // Network and stale-revision failures surface on the results screen; selection survives.
 await page.goto(url);await root.locator('[data-vf-preview-mode]').selectOption('sample');const selected=await root.locator('[data-vf-preview-target]').inputValue();await page.route('**/admin-ajax.php',r=>r.abort('failed'));await run.click();await root.locator('[data-vf-preview-result-section="issues"] article:visible').waitFor();assert(await run.isEnabled());assert.equal(await root.locator('[data-vf-preview-mode]').inputValue(),'sample');assert.equal(await root.locator('[data-vf-preview-target]').inputValue(),selected);await page.screenshot({path:'proof/preview-network-error-1440.png',fullPage:true});await page.unroute('**/admin-ajax.php');
 await page.goto(url);await root.evaluate(n=>n.dataset.revision='0'.repeat(64));await run.click();await root.locator('[data-vf-preview-result-section="issues"] article:visible').waitFor();assert(await root.locator('[data-vf-preview-verdict-title]').innerText().then(s=>s.includes('配置已变化')));await page.screenshot({path:'proof/preview-conflict-1440.png',fullPage:true});
 await page.goto(url);const cfg=await page.evaluate(()=>({ajaxUrl:VFThemePreview.ajaxUrl,nonce:VFThemePreview.nonce,revision:document.querySelector('[data-vf-preview-page]').dataset.revision}));const fields={action:'vf_theme_preview_run',phase:'workbench_start',mode:'quick',speed:'normal',target:'route:',language:'en',revision:cfg.revision,nonce:cfg.nonce};
 assert.equal((await context.request.post(cfg.ajaxUrl,{form:{...fields,nonce:'invalid'}})).status(),403);assert.equal((await context.request.post(cfg.ajaxUrl,{form:{...fields,revision:'0'.repeat(64)}})).status(),409);const anon=await browser.newContext();const denied=await anon.request.post(cfg.ajaxUrl,{form:fields});assert(denied.status()>=400||await denied.text()==='0');
 // Anonymous signed front-end preview and actual revocation via its native form.
 const oldLink=await root.locator('[data-vf-preview-open-page]').getAttribute('href');assert(new URL(oldLink,base).searchParams.has('vf_tools_preview'));const signed=await anon.request.get(oldLink);const proof=signed.headers()['x-vf-preview-proof'];if(proof)fs.writeFileSync('proof/preview-signature-context.json',Buffer.from(proof,'base64'));assert.equal(signed.status(),200,'signed front-end preview rejected: '+(proof?Buffer.from(proof,'base64').toString():'no diagnostic header'));assert((await signed.text()).includes('noindex'));
 const language=root.locator('[data-vf-preview-language]'),originalLanguage=await language.inputValue();for(const value of await language.locator('option').evaluateAll(ns=>ns.map(n=>n.value))){await language.selectOption(value);const response=await anon.request.get(await root.locator('[data-vf-preview-open-page]').getAttribute('href'));const header=response.headers()['x-vf-preview-proof'];const diagnostic=header?JSON.parse(Buffer.from(header,'base64').toString()):{};fs.writeFileSync('proof/preview-language-'+value+'.json',JSON.stringify({language:value,status:response.status(),...diagnostic},null,2));assert.equal(response.status(),200,'signed preview language scope '+value+': '+JSON.stringify(diagnostic));assert((await response.text()).includes('noindex'));}await language.selectOption(originalLanguage);
 // A real renderer change still invalidates an otherwise authentic preview token.
 cli('$d=vf_tools_theme_renderer_readback()["renderer"];update_option("vf_renderer_proof_restore",$d,false);$d["inputLayout"]=$d["inputLayout"]==="STACKED"?"SPLIT_WHEN_SAFE":"STACKED";update_option(vf_tools_theme_renderer_option_key(),$d,false);');
 try { const changed=await anon.request.get(oldLink);assert.equal(changed.status(),403,'changed renderer profile accepted old token');const diagnostic=JSON.parse(Buffer.from(changed.headers()['x-vf-preview-proof'],'base64').toString());assert.equal(diagnostic.failure,'PROFILE_SCOPE_MISMATCH'); }
 finally {cli('update_option(vf_tools_theme_renderer_option_key(),get_option("vf_renderer_proof_restore"),false);delete_option("vf_renderer_proof_restore");');}
 assert.equal((await anon.request.get(oldLink)).status(),200,'restoring the same renderer did not restore its canonical revision');
 const tampered=new URL(oldLink,base);const token=tampered.searchParams.get('vf_tools_preview');tampered.searchParams.set('vf_tools_preview',token.slice(0,-1)+(token.endsWith('a')?'b':'a'));assert.equal((await anon.request.get(tampered.toString())).status(),403,'invalid signature accepted');
 await root.locator('[data-vf-preview-workflow-step="preview"]').click();await root.locator('.vf-preview-v510__link-options summary').click();await Promise.all([page.waitForURL(/vf_theme_notice=preview-links-revoked/),root.locator('.vf-preview-revoke-form button').click()]);const revoked=await anon.request.get(oldLink);assert(revoked.status()>=400,'revocation did not invalidate previous signature');await anon.close();
 assert.equal(errors.length,0,JSON.stringify(errors));
 fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'PASS',wordpress_integration:'REAL_ISOLATED_WORDPRESS',checks,actual_job:'PASS',page_matrix:'PASS',view_mode:'PASS',download:'PASS',busy_lock:'PASS',pause_resume_stop:'PASS',network_failure:'PASS',revision_conflict:'PASS',csrf:'PASS',guest:'PASS',signed_preview:'PASS',profile_revision:'PASS',revoke:'PASS',errors},null,2));await browser.close();
})().catch(async e=>{if(page)await page.screenshot({path:'proof/preview-failure.png',fullPage:true}).catch(()=>{});fs.writeFileSync('proof/failure.json',JSON.stringify({status:'FAIL',message:e.message}));console.error(e);process.exit(1)});
