const assert=require('assert/strict'),fs=require('fs');
module.exports=async(page,context,url)=>{
 await page.goto(url);
 const field=k=>page.locator(`[data-vf-brand-input="${k}"]`);
 const original=await field('siteName').inputValue();
 await field('tagline').fill('');await field('siteName').fill('空说明候选');
 assert(!await page.locator('[data-vf-brand-form]').evaluate(n=>n.checkValidity()));
 const result={version:process.env.SOURCE_VERSION,emptyTaglineBlocksSave:'REPRODUCED'};
 await field('tagline').fill('Synthetic valid tagline');
 const other=await context.newPage();await other.goto(url);
 await other.locator('[data-vf-brand-input="siteName"]').fill('另一窗口正式值');
 let response=other.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().postData()?.includes('vf_theme_brand_save'));
 await other.locator('[data-vf-brand-save]').click();assert((await (await response).json()).success);await other.close();
 const send=async()=>{const r=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().postData()?.includes('vf_theme_brand_save'));await page.locator('[data-vf-brand-save]').click();const v=await (await r).json();await page.waitForFunction(()=>document.querySelector('[data-vf-brand-save]').textContent!=='正在保存…');return v;};
 const conflict=await send();assert(!conflict.success&&conflict.data.failureCode==='REVISION_CONFLICT');
 assert((await send()).success,'baseline retry did not overwrite');result.conflictRetryOverwritesOtherWindow='REPRODUCED';
 await page.reload();await field('siteName').fill('尚未保存候选');
 await page.route('**/admin-ajax.php',r=>r.fulfill({json:{success:true,data:{}}}));
 await page.locator('[data-vf-brand-save]').click();await page.waitForFunction(()=>document.querySelector('[data-vf-brand-page]').dataset.vfBrandDirty==='0');
 result.incompleteResponseClaimsSaved='REPRODUCED';await page.unroute('**/admin-ajax.php');
 await page.reload();await field('siteName').fill('正在保存的候选');
 await page.route('**/admin-ajax.php',async r=>{const response=await r.fetch();await new Promise(resolve=>setTimeout(resolve,400));await r.fulfill({response});});
 const pending=page.waitForRequest(r=>r.url().includes('admin-ajax.php')&&r.postData()?.includes('vf_theme_brand_save'));
 await page.locator('[data-vf-brand-save]').click();await pending;
 assert(await field('siteName').isEnabled());await field('siteName').fill('保存期间的新输入');
 await page.waitForFunction(()=>document.querySelector('[data-vf-brand-page]').dataset.vfBrandDirty==='0');
 assert.equal(await field('siteName').inputValue(),'正在保存的候选');result.editDuringSaveLost='REPRODUCED';await page.unroute('**/admin-ajax.php');
 await page.reload();await page.setViewportSize({width:1319,height:1000});
 const inset=await page.evaluate(()=>document.querySelector('[data-vf-native-header-v8="brand"] h1').getBoundingClientRect().left-document.querySelector('.vf-admin-one-row-shell').getBoundingClientRect().left);
 assert(inset>28);result.titleInsetDiffersFromOverview='REPRODUCED';result.originalName=original;
 fs.writeFileSync('proof/baseline.json',JSON.stringify(result,null,2));
};
