const assert=require('assert/strict'),fs=require('fs');
module.exports=async(page,context,browser,url)=>{
 const check={},field=k=>page.locator(`[data-vf-brand-input="${k}"]`),save=page.locator('[data-vf-brand-save]');
 const read=async()=>page.evaluate(()=>Object.fromEntries(new FormData(document.querySelector('[data-vf-brand-form]'))));
 const send=async()=>{const r=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().postData()?.includes('vf_theme_brand_save'));await save.click();const v=await(await r).json();await page.waitForFunction(()=>document.querySelector('[data-vf-brand-page]').getAttribute('aria-busy')!=='true');return v;};
 const saved=async()=>{const v=await send();assert(v.success,JSON.stringify(v));await page.waitForFunction(()=>document.querySelector('[data-vf-brand-page]').dataset.vfBrandDirty==='0');return v;};
 const discard=async()=>{if(await page.locator('[data-vf-brand-discard]').isVisible())await page.locator('[data-vf-brand-discard]').click();};
 const payload=async()=>page.evaluate(()=>({schemaVersion:'1.0.0',artifactType:'vf-theme-brand-configuration',component:'vf-theme',pageId:'theme.brand',version:VFThemeBrand.version,brand:Object.fromEntries([...document.querySelectorAll('[data-vf-brand-form] [name^="brand["]')].map(n=>[n.dataset.vfBrandInput,n.dataset.vfBrandInput==='logoImageId'?Number(n.value):n.value])),tokens:Object.fromEntries([...document.querySelectorAll('[data-vf-brand-form] [name^="tokens["]')].map(n=>[n.dataset.vfBrandInput,n.value]))}));
 await page.setViewportSize({width:1319,height:1000});await page.goto(url);
 const original=await field('siteName').inputValue();
 await field('tagline').fill('');await field('siteName').fill('空说明可保存');await saved();await page.reload();assert.equal(await field('tagline').inputValue(),'');check.empty_tagline_save_reload='PASS';
 await field('brand').fill('');assert.equal(await page.locator('[data-vf-brand-page]').getAttribute('data-vf-brand-dirty'),'1');await discard();check.invalid_empty_color_stays_dirty='PASS';
 for(const k of ['brand','accent','success','warning','danger']){await page.evaluate(()=>document.querySelector('.vf-v8-brand-status-colors').open=true);await field(k).fill('#0f766e');assert.equal(await page.locator(`[data-vf-color-picker="${k}"]`).inputValue(),'#0f766e');await page.locator(`[data-vf-color-picker="${k}"]`).evaluate(n=>{n.value='#0891b2';n.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await field(k).inputValue(),'#0891b2');}await saved();check.five_color_pairs_save='PASS';
 await page.locator('[data-vf-brand-font-select]').selectOption('system');assert((await field('bodyFont').inputValue()).includes('system-ui'));await page.locator('[data-vf-brand-font-select]').selectOption('custom');assert(await page.locator('.vf-v8-brand-custom-font').evaluate(n=>n.open));await field('bodyFont').fill('Arial,sans-serif');await field('headingFont').fill('Georgia,serif');await saved();await page.reload();assert.equal(await page.locator('[data-vf-brand-font-select]').inputValue(),'custom');check.font_presets_custom_save='PASS';
 await page.locator('.vf-v9-brand-layout').evaluate(n=>n.open=true);
 for(const [k,v]of Object.entries({baseFontSize:18,siteMaxWidth:1240,toolMaxWidth:1160,articleMaxWidth:840,cardRadius:8,controlHeight:42})){await page.locator(`[data-vf-length-number="${k}"]`).fill(String(v));assert.equal(await field(k).inputValue(),v+'px');}await saved();await page.reload();assert.equal(await field('controlHeight').inputValue(),'42px');check.six_numeric_controls_save='PASS';
 await page.locator('.vf-v9-brand-layout').evaluate(n=>n.open=true);await page.locator('[data-vf-length-number="siteMaxWidth"]').fill('2000');assert(!await page.locator('[data-vf-brand-form]').evaluate(n=>n.checkValidity()));await discard();check.invalid_numeric_rejected='PASS';
 await page.locator('.vf-v9-brand-recipes').evaluate(n=>n.open=true);for(const b of await page.locator('[data-vf-brand-preset]').all()){await b.click();assert.equal(await b.getAttribute('aria-pressed'),'true');assert((await field('brand').inputValue()).startsWith('#'));}await discard();check.seven_recipes_candidate_only='PASS';
 await field('siteName').fill('差异候选');await page.locator('[data-vf-brand-preview-open]').click();await page.locator('[data-vf-brand-preview-diff]').click();await page.locator('#vf-brand-diff-dialog').waitFor();assert((await page.locator('[data-vf-brand-diff]').innerText()).includes('差异候选'));await page.keyboard.press('Escape');await page.keyboard.press('Escape');await discard();check.readonly_diff_dialog_keyboard='PASS';
 // Actual successful request is delayed after reaching the server. Controls must remain locked.
 await field('siteName').fill('忙碌保存');await page.route('**/admin-ajax.php',async r=>{const response=await r.fetch();await new Promise(resolve=>setTimeout(resolve,400));await r.fulfill({response});});
 const req=page.waitForRequest(r=>r.url().includes('admin-ajax.php')&&r.postData()?.includes('vf_theme_brand_save'));await save.click();await req;
 assert(await field('siteName').isDisabled());assert(await page.locator('.vf-brand-inheritance [name="label"]').isDisabled());assert(await page.locator('[data-vf-brand-media]').isDisabled());assert(await save.isDisabled());await page.waitForFunction(()=>document.querySelector('[data-vf-brand-page]').dataset.vfBrandDirty==='0');await page.unroute('**/admin-ajax.php');check.busy_isolates_all_mutation_controls='PASS';
 for(const scenario of ['network','invalid_json','incomplete','http','timeout']){
  await page.reload();await field('siteName').fill('失败保留-'+scenario);const revision=await page.locator('[data-vf-brand-revision]').inputValue();
  if(scenario==='timeout')await page.evaluate(()=>{const original=window.setTimeout;window.setTimeout=(fn,delay,...args)=>original(fn,delay===20000?50:delay,...args);});
  await page.route('**/admin-ajax.php',async r=>{
   if(scenario==='network')return r.abort('failed');
   if(scenario==='invalid_json')return r.fulfill({body:'<html>invalid</html>',contentType:'text/html'});
   if(scenario==='timeout'){await new Promise(resolve=>setTimeout(resolve,180));return r.abort('timedout').catch(()=>{});}
   return r.fulfill({status:scenario==='http'?503:200,json:{success:true,data:{}}});
  });await save.click();await page.locator('[data-vf-brand-error-summary]').waitFor();await page.waitForFunction(()=>!document.querySelector('[data-vf-brand-save]').disabled);
  assert.equal(await field('siteName').inputValue(),'失败保留-'+scenario);assert.equal(await page.locator('[data-vf-brand-revision]').inputValue(),revision);assert.equal(await page.locator('[data-vf-brand-page]').getAttribute('data-vf-brand-dirty'),'1');
  await page.screenshot({path:'proof/brand-error-'+scenario+'.png',fullPage:true});await page.unroute('**/admin-ajax.php');await saved();check[scenario+'_retains_input_and_retry']='PASS';
 }
 // Two real windows: a conflict never promotes the old form's revision or enables an overwrite.
 await page.reload();const revision=await page.locator('[data-vf-brand-revision]').inputValue();const other=await context.newPage();await other.goto(url);await other.locator('[data-vf-brand-input="siteName"]').fill('外部正式名称');const out=other.waitForResponse(r=>r.url().includes('admin-ajax.php'));await other.locator('[data-vf-brand-save]').click();assert((await(await out).json()).success);
 await field('siteName').fill('本窗口保留候选');for(let i=0;i<2;i++){const v=await send();assert(!v.success&&v.data.failureCode==='REVISION_CONFLICT');assert.equal(await page.locator('[data-vf-brand-revision]').inputValue(),revision);}await other.reload();assert.equal(await other.locator('[data-vf-brand-input="siteName"]').inputValue(),'外部正式名称');await other.close();check.conflict_retry_cannot_overwrite='PASS';
 const dl=page.waitForEvent('download');await page.locator('[data-vf-brand-error-export]').click();const download=await dl;const path=await download.path();const exported=JSON.parse(fs.readFileSync(path));assert.equal(exported.brand.siteName,'本窗口保留候选');check.conflict_candidate_export='PASS';
 await page.reload();await page.locator('.vf-brand-tools').evaluate(n=>n.open=true);await field('siteName').fill('仅导出候选');
 for(const mode of ['saved','candidate']){await page.locator('[data-vf-brand-export-scope]').selectOption(mode);const d=page.waitForEvent('download');await page.locator('[data-vf-brand-export-run]').click();const out=JSON.parse(fs.readFileSync(await(await d).path()));assert.equal(out.brand.siteName,mode==='saved'?'外部正式名称':'仅导出候选');}check.saved_candidate_exports='PASS';await discard();
 const upload=async p=>page.locator('[data-vf-brand-import-file]').setInputFiles({name:'brand.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});
 const valid=await payload();valid.brand.siteName='导入候选';await page.locator('[data-vf-brand-import-open]').click();await upload(valid);await page.locator('[data-vf-brand-import-apply]').waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('[data-vf-brand-import-apply]').disabled);await page.locator('[data-vf-brand-import-apply]').click();assert.equal(await field('siteName').inputValue(),'导入候选');await saved();check.import_preflight_apply_save='PASS';
 for(const type of ['unknown','missing','format','value','oversize','malformed']){await page.locator('[data-vf-brand-import-open]').click();const bad=JSON.parse(JSON.stringify(valid));if(type==='unknown')bad.tokens.unregistered=true;if(type==='missing')delete bad.tokens.accent;if(type==='format')bad.schemaVersion='99';if(type==='value')bad.tokens.brand='#bad';if(type==='oversize')bad.pad='x'.repeat(131073);if(type==='malformed')await page.locator('[data-vf-brand-import-file]').setInputFiles({name:'brand.json',mimeType:'application/json',buffer:Buffer.from('{invalid')});else await upload(bad);await page.locator('[data-vf-brand-import-error]').waitFor();assert(await page.locator('[data-vf-brand-import-apply]').isDisabled());await page.keyboard.press('Escape');}check.import_invalid_preserves_form='PASS';
 await page.locator('[data-vf-brand-import-open]').click();await page.evaluate(valid=>{
  const original=File.prototype.text;File.prototype.text=function(){return new Promise(resolve=>setTimeout(async()=>resolve(await original.call(this)),this.name==='slow.json'?300:10));};
  const node=document.querySelector('[data-vf-brand-import-file]');for(const [name,siteName]of [['slow.json','旧慢文件'],['fast.json','最新文件']]){const data=new DataTransfer();data.items.add(new File([JSON.stringify({...valid,brand:{...valid.brand,siteName}})],name,{type:'application/json'}));node.files=data.files;node.dispatchEvent(new Event('change',{bubbles:true}));}
 },valid);await page.waitForTimeout(400);await page.locator('[data-vf-brand-import-apply]').click();assert.equal(await field('siteName').inputValue(),'最新文件');await discard();check.import_latest_file_wins='PASS';
 // Media picker uses a real WordPress attachment created only in this synthetic runtime.
await page.locator('[data-vf-brand-media]').click();await page.locator('.media-modal').waitFor();await page.locator('.media-modal').getByText('Media Library',{exact:true}).click();const media=page.locator('.media-modal .attachments .attachment').first();await media.waitFor();await media.click();await page.locator('.media-modal .media-button-select').click();assert(Number(await field('logoImageId').inputValue())>0);
 await field('logoMode').selectOption('image');await page.locator('[data-vf-brand-preview-open]').click();assert(await page.locator('[data-vf-preview-logo]').isVisible());assert(!await page.locator('[data-vf-preview-wordmark]').isVisible());await page.keyboard.press('Escape');await field('logoMode').selectOption('combined');await page.locator('[data-vf-brand-preview-open]').click();assert(await page.locator('[data-vf-preview-logo]').isVisible());assert(await page.locator('[data-vf-preview-wordmark]').isVisible());assert(!await page.locator('[data-vf-preview-mark]').isVisible());await page.keyboard.press('Escape');await saved();await page.reload();assert.equal(await field('logoMode').inputValue(),'combined');await page.locator('[data-vf-brand-logo-remove]').click();assert.equal(await field('logoImageId').inputValue(),'0');assert.equal(await field('logoMode').inputValue(),'text');await saved();check.media_select_modes_remove_save='PASS';
 await page.locator('.vf-brand-tools').evaluate(n=>n.open=true);for(const scope of ['brand','colors','typography','layout','all']){await page.locator('[data-vf-brand-reset-open]').click();await page.locator('[data-vf-brand-reset-scope]').selectOption(scope);await page.locator('[data-vf-brand-reset-apply]').click();assert(await save.isVisible());await discard();}check.reset_five_scopes_candidate_only='PASS';
 await field('siteName').fill('高级操作之前的未保存值');await page.locator('#vf-brand-inheritance').evaluate(n=>n.open=true);await page.locator('[data-vf-brand-advanced-group="temporary"]').evaluate(n=>n.open=true);const beforeURL=page.url();await page.locator('.vf-brand-inheritance__form--tokens button[type="submit"]').click();assert.equal(page.url(),beforeURL);assert.equal(await field('siteName').inputValue(),'高级操作之前的未保存值');assert((await page.locator('[data-vf-brand-error-message]').innerText()).includes('先保存或放弃'));await discard();check.advanced_write_cannot_discard_brand_draft='PASS';
 // Preset application is executed only here in isolated synthetic WordPress; guarded proof remains enforced.
 await page.locator('[data-vf-brand-advanced-group="preset"]').evaluate(n=>n.open=true);const preset=page.locator('form').filter({has:page.locator('[name="action"][value="vf_theme_site_preset_preflight"]')});await preset.locator('[name="mode"]').selectOption('safe');await Promise.all([page.waitForURL(u=>u.searchParams.get('vf_theme_notice')==='preset-diff-ready'),preset.locator('button').click()]);await page.locator('.vf-brand-preset-confirm [name="confirm"]').fill('APPLY');await Promise.all([page.waitForURL(u=>u.searchParams.get('vf_theme_notice')==='preset-applied'),page.locator('.vf-brand-preset-confirm button').click()]);check.preset_preflight_confirm_apply='PASS';
 await page.goto(url);await field('siteName').fill(original);await saved();
 const nojs=await browser.newContext({javaScriptEnabled:false}),np=await nojs.newPage();
 const login=async(p,user,password)=>{await p.goto(new URL('/wp-login.php',url).href);await p.locator('#user_login').fill(user);await p.locator('#user_pass').fill(password);await Promise.all([p.waitForURL(/wp-admin/),p.locator('#wp-submit').click()]);};
 await login(np,'admin','Synthetic-Only-Update-54!');await np.goto(url);await np.locator('[data-vf-brand-input="tagline"]').fill('');await np.locator('[data-vf-brand-input="siteName"]').fill('无脚本原生保存');
 await Promise.all([np.waitForURL(u=>u.searchParams.get('vf_theme_notice')==='brand-saved'),np.locator('noscript button[type="submit"]').click()]);await np.reload();assert.equal(await np.locator('[data-vf-brand-input="siteName"]').inputValue(),'无脚本原生保存');await nojs.close();check.no_javascript_native_save_reload='PASS';
 const {execFileSync}=require('child_process');
 execFileSync('docker',['exec','--user','www-data',process.env.WP,'php','/usr/local/bin/wp','user','create','brand-subscriber','brand-subscriber@example.invalid','--role=subscriber','--user_pass=Synthetic-brand-only-84!','--path=/var/www/html'],{stdio:'pipe'});
 const limited=await browser.newContext(),lp=await limited.newPage();await login(lp,'brand-subscriber','Synthetic-brand-only-84!');
 const denied=await limited.request.post(new URL('/wp-admin/admin-ajax.php',url).href,{form:{action:'vf_theme_brand_save',nonce:'synthetic-denied',revision:'synthetic-denied'}});assert.equal(denied.status(),403);assert.equal((await denied.json()).data.failureCode,'PERMISSION_DENIED');await limited.close();
 await page.reload();assert.equal(await field('siteName').inputValue(),'无脚本原生保存');check.permission_denied_preserves_saved_state='PASS';await field('siteName').fill(original);await saved();
 fs.writeFileSync('proof/brand-functions.json',JSON.stringify({status:'PASS',checks:check},null,2));return check;
};
