const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const check=require('../target/tests/navigation-controls-browser-check'),base='http://127.0.0.1:18880',url=base+'/wp-admin/themes.php?page=vf-theme-modules&tab=navigation';
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill('admin');await page.locator('#user_pass').fill('Synthetic-Only-Update-54!');await Promise.all([page.waitForURL(/wp-admin/),page.locator('#wp-submit').click()]);
 const checks=[];for(const width of [1920,1440,1319,1024,768,390]){await page.setViewportSize({width,height:1000});await page.goto(url);await page.locator('[data-vf-page-id="THM-NAV-001"]').waitFor();checks.push(await check(page,{width,out:path.resolve('proof'),screenshots:true}));}
 await page.setViewportSize({width:1440,height:1000});await page.goto(url);const root=page.locator('[data-vf-page-id="THM-NAV-001"]'),tab=key=>root.locator('[data-vf-navigation-workflow-step='+key+']');
 await tab('footer').click();const copyright=root.locator('[data-vf-navigation-i18n-panel=footer]:visible input').last();await copyright.fill('Synthetic navigation retained 74');await copyright.dispatchEvent('input');
 await tab('header').click();const breakpoint=root.locator('[name="navigation[mobileBreakpoint]"]');await breakpoint.fill('820');await breakpoint.dispatchEvent('input');
 const response=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST');await root.locator('[data-vf-navigation-save]').click();const saved=await response;assert(saved.ok());const payload=await saved.json();assert(payload.success,'native save failed');await page.waitForFunction(()=>document.querySelector('[data-vf-navigation-page]').dataset.vfNavigationDirty==='0');
 await page.reload();await tab('header').click();assert.equal(await breakpoint.inputValue(),'820');await tab('footer').click();assert.equal(await copyright.inputValue(),'Synthetic navigation retained 74');
 await tab('header').click();const cta=root.locator('[data-vf-navigation-i18n-panel=header]:visible [data-vf-navigation-cta-url]'),oldUrl=await cta.inputValue();await cta.fill('javascript:alert(1)');await cta.dispatchEvent('input');await root.locator('[data-vf-navigation-save]').click();assert(await root.locator('[data-vf-navigation-error-summary]').isVisible(),'invalid URL not reported');assert.equal(await cta.inputValue(),'javascript:alert(1)');await cta.fill(oldUrl);await cta.dispatchEvent('input');
 const cfg=await page.evaluate(()=>({ajaxUrl:window.VF_THEME_NAVIGATION.ajaxUrl,nonce:window.VF_THEME_NAVIGATION.nonce}));const fields=await root.locator('form').evaluate(n=>Object.fromEntries(new FormData(n)));fields.action='vf_theme_navigation_save';fields.nonce=cfg.nonce;
 const invalid=await context.request.post(cfg.ajaxUrl,{form:{...fields,nonce:'invalid-nonce'}});assert(invalid.status()>=400||!(await invalid.json()).success,'invalid nonce accepted');
 const anon=await browser.newContext();const denied=await anon.request.post(cfg.ajaxUrl,{form:fields});assert(denied.status()>=400||await denied.text()==='0','guest accepted');await anon.close();
 const conflict=await context.request.post(cfg.ajaxUrl,{form:{...fields,baseNavigation:'',revision:'0'.repeat(64)}});const conflictBody=await conflict.text();assert(conflict.status()>=400&&conflictBody.includes('REVISION_CONFLICT'),'revision conflict accepted');
 execFileSync('docker',['exec','--user','www-data','vf-v8-'+process.env.GITHUB_RUN_ID+'-wp','php','/usr/local/bin/wp','eval',"$n=theme_navigation_readback()['navigation'];if((int)$n['mobileBreakpoint']!==820||!in_array('Synthetic navigation retained 74',array_column($n['shell']['i18n'],'footerCopyright'),true)){throw new Exception('native persisted state or negative preservation failed');}",'--path=/var/www/html'],{stdio:'pipe'});
 assert.equal(errors.length,0,JSON.stringify(errors));fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'PASS',wordpress_integration:'REAL_ISOLATED_WORDPRESS',checks,persistence:'PASS',invalid_url:'PASS',csrf:'PASS',guest:'PASS',revision_conflict:'PASS',errors},null,2));await browser.close();console.log('NAVIGATION_NATIVE_BROWSER=PASS');
})().catch(e=>{console.error(e);process.exit(1);});
