'use strict';
const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
const phase=process.argv[2]||'candidate',base='http://127.0.0.1:18880';
(async()=>{
 const b=await chromium.launch(),p=await b.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 async function ready(){await p.waitForLoadState('networkidle');await p.waitForFunction(()=>document.documentElement.getAttribute('data-vf-navigation')==='ready'&&document.documentElement.getAttribute('data-vf-runtime-ready')==='stable');await p.evaluate(()=>document.fonts.ready);}
 async function state(){return p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,h1:document.querySelectorAll('h1').length,theme_workflows:document.querySelectorAll('.vf-tool-runtime-path').length,provider_workflows:document.querySelectorAll('.vf-m3u8-launchbar').length,state:document.querySelector('.vf-tool-runtime-state')?.innerText,guide:document.querySelector('.vf-tool-runtime-guide-head')?.innerText}));}
 if(phase!=='candidate'){
  const rows=[];for(const route of ['/m3u8-downloader/','/m3u8-to-mp4/']){await p.goto(base+route);await ready();const s=await state();assert.equal(s.theme_workflows,1);assert.equal(s.provider_workflows,1);assert.match(s.state,/Real controls come from the tool plugin/);rows.push({route,...s});}
  await p.locator('.vf-tool-runtime-shell').screenshot({path:'proof/workspace-'+phase+'-1440.png'});
  fs.writeFileSync('proof/workspace-'+phase+'.json',JSON.stringify({status:'REPRODUCED',issue:'TWO_OPERATION_GUIDES_AND_DEVELOPER_COPY',rows,single_numbering:'NO_VISUAL_DUPLICATE_CONFIRMED',production:'NOT_EXECUTED'},null,2));await b.close();return;
 }
 await p.goto(base+'/tools/');await ready();const routes=await p.locator('.vf-directory-card').evaluateAll(a=>a.map(e=>new URL(e.href).pathname));assert.equal(routes.length,11);assert.equal(new Set(routes).size,11);
 const rows=[];for(const width of [1440,390]){await p.setViewportSize({width,height:1000});for(const route of routes){await p.goto(base+route);await ready();const s=await state();assert.equal(s.scroll,s.client,'overflow '+route+' '+width);assert.equal(s.h1,1);assert.equal(s.theme_workflows,0,route);assert.equal(s.provider_workflows,1,route);assert.match(s.state,/Workspace ready/i);assert.doesNotMatch(s.state,/plugin|real controls/i);assert.doesNotMatch(s.guide,/hidden in a disclosure/i);rows.push({route,...s});if(['/m3u8-downloader/','/m3u8-to-mp4/'].includes(route))await p.locator('.vf-tool-runtime-shell').screenshot({path:'proof/workspace-'+route.replaceAll('/','')+'-'+width+'.png'});}}
 const output=[];for(const [route,button] of [['/m3u8-downloader/','Download built-in demo'],['/m3u8-to-mp4/','Convert bundled sample']]){
  await p.goto(base+route);await ready();const wait=p.waitForEvent('download',{timeout:120000});await p.getByRole('button',{name:button,exact:true}).click();const d=await wait,file=await d.path(),data=fs.readFileSync(file);assert(data.length>100000);assert.equal(data.subarray(4,8).toString(),'ftyp');assert(data.includes(Buffer.from('mdat')));assert(await p.getByRole('button',{name:'Save again',exact:true}).isVisible());output.push({route,name:d.suggestedFilename(),bytes:data.length,mp4_container:'FTYP_MDAT_PASS',sha256:require('crypto').createHash('sha256').update(data).digest('hex')});await p.getByRole('button',{name:'Clear',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Save again',exact:true}).isVisible(),false);}
 assert.deepEqual(errors,[]);fs.writeFileSync('proof/workspace-browser.json',JSON.stringify({status:'PASS',scope:'THEME_WORKSPACE_GUIDANCE_ONLY',route_count:routes.length,rows,sample_outputs:output,clear_recovery:'PASS',page_errors:errors,provider_version:'1.25.77',production:'NOT_EXECUTED'},null,2));await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
