'use strict';
const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright'),{url,login,sample,cli,load,base}=require('./common');
(async()=>{
 cli(load+'update_option("permalink_structure","/%postname%/");foreach(["seo-front-one","seo-front-two"] as $slug){wp_insert_post(["post_type"=>"page","post_status"=>"publish","post_name"=>$slug,"post_title"=>"Synthetic frontend ".$slug,"post_content"=>"Actual isolated WordPress page."]);}flush_rewrite_rules(true);$s=vf_theme_seo_defaults();foreach(["seo-front-one","seo-front-two"] as $slug){$s["virtualRoutePolicy"][]=["routeId"=>str_replace("-","_",$slug),"pageFamily"=>"content","pathPattern"=>$slug,"resolver"=>"vf_theme_url_resolver","canonicalPolicy"=>"self","hreflangPolicy"=>"paired","indexability"=>"index_follow","staticPathPolicy"=>"required"];}update_option(vf_theme_seo_option_key(),$s,false);update_option("vf_seo_baseline_good",$s,false);');
 const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('dialog',d=>d.accept());await login(page);await page.goto(url);
 const r=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST'&&/(?:name="action"\r?\n\r?\nvf_theme_seo_save|(?:^|&)action=vf_theme_seo_save(?:&|$))/.test(r.request().postData()||''));await page.locator('[data-vf-seo-verify]').click();const init=(await(await r).json());fs.writeFileSync('proof/baseline-init.json',JSON.stringify(init));assert(init.success,'baseline verification failed: '+JSON.stringify(init));await page.waitForFunction(()=>document.querySelector('[data-vf-seo-form-shell]').getAttribute('aria-busy')!=='true');
 await page.setViewportSize({width:1024,height:1000});await page.goto(url);
 const boxes=await page.locator('.vf-v6-domain-nav > a,.vf-v6-domain-nav > details > summary').evaluateAll(ns=>ns.map(n=>{const b=n.getBoundingClientRect(),r=document.createRange();r.selectNodeContents(n);const t=r.getBoundingClientRect();return{text:n.textContent.trim(),control:{x:b.x,right:b.right},textBox:{x:t.x,right:t.right},overflows:t.x<b.x-1||t.right>b.right+1};}));
 assert(await page.locator('.vf-v6-domain-nav').isVisible());assert(boxes.some(n=>n.overflows),'92 crowded header must reproduce');fs.writeFileSync('proof/header-baseline-1024.json',JSON.stringify(boxes,null,2));await page.screenshot({path:'proof/header-baseline-1024.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 await sample(page);await sample(page);const samples=[];for(let i=0;i<5;i++)samples.push(await sample(page));
 fs.writeFileSync('proof/baseline.json',JSON.stringify({status:'REPRODUCED',source_version:process.env.SOURCE_VERSION,header_1024_crowding:true,performance:{dataset:'same isolated WordPress SEO route catalogue and two native frontend pages',warmups:2,samples}},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
