<?php
// Synthetic-only Runner MU fixture. Never part of the Theme package.
add_action('template_redirect',function(){
 if(!isset($_GET['vf-render-fixture'])){return;}
 vf_theme_bootstrap_require_many(['services/renderer-config-service.php','services/runtime-descriptor-service.php','services/page-projection-consumer-service.php','services/runtime-asset-loader-service.php','services/provider-widget-host-service.php','services/product-renderer-service.php']);
 $asset='/wp-content/mu-plugins/vf-render-fixture.js';$hash=hash_file('sha256',ABSPATH.ltrim($asset,'/'));$mode=sanitize_text_field($_GET['mode']??'');
 $descriptor=['schemaVersion'=>'1.0.0','descriptorRef'=>'synthetic-runtime','hash'=>str_repeat('a',64),'exactContracts'=>['synthetic/1.0.0'],'pipelineGraph'=>['nodes'=>['synthetic']],'ports'=>['input'=>['URL','TEXT']],'resourceLimits'=>['maxBytes'=>1024],'processingFacts'=>['location'=>'BROWSER'],'exposure'=>'PUBLIC_RUNTIME','networkPolicy'=>'NONE','entrypoints'=>['execute'=>'synthetic.execute','dispose'=>'synthetic.dispose'],'runtimeBundle'=>['ref'=>'synthetic-bundle','version'=>'1.0.0','hash'=>str_repeat('b',64)],'assets'=>[['ref'=>'synthetic-optional','type'=>'SCRIPT','loadPhase'=>'EXECUTION','url'=>$asset,'hash'=>$hash,'runtimeBundleRef'=>'synthetic-bundle']]];
 $p=['schemaVersion'=>'1.0.0','pageUid'=>'synthetic-page','pageRevision'=>'1','taskUid'=>'synthetic-task','taskRevision'=>'1','locale'=>'zh-CN','route'=>'/','runtimeDescriptor'=>$descriptor,'runtimeDescriptorHash'=>$descriptor['hash'],'product'=>['title'=>'合成工具测试','h1'=>'合成工具测试','intro'=>'页面说明始终可以阅读。','processingDisclosure'=>'合成数据仅用于隔离验证。'],'seo'=>['title'=>'合成工具测试','description'=>'合成数据','canonical'=>home_url('/'),'robots'=>'noindex,nofollow'],'interaction'=>['inputModes'=>['URL','TEXT'],'parameters'=>[['key'=>'optional','label'=>'可选格式','type'=>'SELECT','options'=>['A','B']],['key'=>'required','label'=>'必填名称','type'=>'TEXT','required'=>true],['key'=>'enabled','label'=>'启用选项','type'=>'TOGGLE']],'resultKinds'=>['SUMMARY'],'primaryAction'=>['key'=>'execute','label'=>'执行合成测试']],'providerWidget'=>['widgetKey'=>($_GET['widget']??'')==='missing'?'missing':'synthetic','contractVersion'=>'1.0.0','provider'=>'synthetic','runtimeBundle'=>'synthetic-bundle','hostApiVersion'=>($_GET['widget']??'')==='invalid'?'99.0.0':'1.0.0','renderSchemaRange'=>'>=1.0.0 <2.0.0','mobileSupport'=>sanitize_text_field($_GET['mobile']??'FULL'),'accessibilityProfile'=>'WCAG_KEYBOARD_FOCUS_ARIA_V1','assetRefs'=>['synthetic-optional']],'faq'=>[['question'=>'没有脚本可以阅读吗？','answer'=>'说明和帮助仍然可读。']],'quickHelp'=>[['title'=>'帮助','text'=>'合成工具操作指引']]];
 if($mode!==''){$p['rendererMode']=$mode;}
 if(isset($_GET['unsafe'])){$p['runtimeDescriptor']['assets'][0]['url']='https://outside.invalid/inject.js';}
 $GLOBALS['vf_tools_page_projection']=$p;
 add_filter('vf_tools_theme_provider_widget_renderers',function($renderers){$renderers['synthetic']=function($projection,$api){echo '<label>合成输入<input name="synthetic_input" type="text"></label><button type="button">合成操作</button><script>window.UNSAFE_WIDGET=true</script><img src="x" onerror="window.UNSAFE_WIDGET=true">';};return $renderers;});
 status_header(200);header('Cache-Control: no-store');echo '<!doctype html><html lang="zh-CN"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>合成工具测试</title>';
 echo '<link rel="stylesheet" href="'.esc_url(get_template_directory_uri().'/assets/css/public/v6-product-renderer.css').'">';
 echo '<style>body{font-family:Arial,sans-serif;margin:0;padding:16px;overflow-wrap:anywhere}main{max-width:1100px;margin:auto}input,textarea,select{box-sizing:border-box;max-width:100%}</style>';
 wp_head();echo '</head><body><div>';vf_tools_theme_render_product_page([]);echo '</div>';wp_footer();echo '</body></html>';exit;
},-99);
