'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{cli,setSettings,base,url,fixture,login,sample}=require('./common'),check=require('../target/tests/render-controls-browser-check');
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage(),errors=[],tests=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const passed=n=>tests.push(n);
 await login(page);const checks=[];
 for(const width of [1920,1440,1319,1024,768,390]){await page.setViewportSize({width,height:1000});await page.goto(url);await page.locator('[data-vf-render-enhanced]').waitFor();assert.equal(await page.locator('[data-vf-render-status]').getAttribute('data-status'),'pass');checks.push(await check(page,{width,out:path.resolve('proof'),screenshots:true}));}
 passed('six widths native controls / keyboard / exact edges / discard');await page.setViewportSize({width:1440,height:1000});await page.goto(url);
 const root=page.locator('[data-vf-render-page]'),form=root.locator('form'),save=root.locator('[data-vf-render-save]'),verify=root.locator('[data-vf-render-verify]'),advanced=root.locator('[data-vf-render-advanced]'),feedback=root.locator('[data-vf-render-save-feedback]'),revision=form.locator('[name=revision]');
 const edit=(key)=>form.locator('[name="renderer['+key+']"]');
 const request=()=>page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST');const idle=()=>page.waitForFunction(()=>!document.querySelector('[data-vf-render-page]').hasAttribute('aria-busy'));
 for(const [k,v]of Object.entries({defaultMode:'HYBRID',inputLayout:'SPLIT_WHEN_SAFE',parameterLayout:'VISIBLE',progressPresentation:'STAGE_ONLY',mobileFallback:'BLOCK_UNSUPPORTED_WIDGET'}))await edit(k).selectOption(v);
 await edit('lazyLoadRuntime').uncheck();await advanced.locator('summary').click();await edit('supportedProjectionSchemaRange').fill('^1.0.0');
 let release,requests=0;const gate=new Promise(r=>release=r);await page.route('**/admin-ajax.php',async r=>{requests++;await gate;await r.continue()});const resp=request();await save.click();await page.waitForFunction(()=>document.querySelector('[data-vf-render-page]').getAttribute('aria-busy')==='true');
 assert.equal(await form.locator('input:not(:disabled),select:not(:disabled),button:not(:disabled)').count(),0);const link=form.locator('a').first();const loc=page.url();await link.evaluate(n=>n.click());assert.equal(page.url(),loc);await form.evaluate(n=>n.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await page.screenshot({path:'proof/render-saving-1440.png',fullPage:true});release();const saved=await resp,payload=await saved.json();assert(saved.ok()&&payload.success&&payload.data.ok);await idle();assert.equal(requests,1);assert.equal(await save.isVisible(),false);assert.equal(await root.locator('[data-vf-render-status]').getAttribute('data-status'),'pass');assert.equal(await form.locator('select:disabled,input[type=text]:disabled,input[type=checkbox]:disabled').count(),0);await page.unroute('**/admin-ajax.php');passed('real save / lock all controls and preview / double-submit guarded / unlock');
 await page.reload();await advanced.locator('summary').click();for(const[k,v]of Object.entries({defaultMode:'HYBRID',inputLayout:'SPLIT_WHEN_SAFE',parameterLayout:'VISIBLE',progressPresentation:'STAGE_ONLY',mobileFallback:'BLOCK_UNSUPPORTED_WIDGET',supportedProjectionSchemaRange:'^1.0.0',widgetHostApiVersion:'1.0.0',primitiveProfile:'VF_TOOLS_STANDARD_V1',accessibilityProfile:'WCAG_KEYBOARD_FOCUS_ARIA_V1'}))assert.equal(await edit(k).inputValue(),v);assert.equal(await edit('lazyLoadRuntime').isChecked(),false);assert.equal((await root.locator('[data-vf-render-contract-revision]').innerText()),payload.data.state.revision.slice(0,12));passed('all ten controls persistence and complete canonical readback');
 let rr=request();await verify.click();const verified=(await(await rr).json()).data;await idle();assert.equal(verified.state.revision,payload.data.state.revision);assert.equal(await save.isVisible(),false);passed('idempotent clean recheck');
 const initial=await revision.inputValue();await edit('defaultMode').selectOption('STANDARD');
 const unknownCases=[['transport',r=>r.abort('failed')],['http',r=>r.fulfill({status:502,body:'upstream'} )],['malformed JSON',r=>r.fulfill({contentType:'application/json',body:'{'})],['incomplete',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({success:true,data:{ok:true}})})],['wrong revision',r=>{const x=structuredClone(payload);x.data.state.revision='f'.repeat(64);return r.fulfill({contentType:'application/json',body:JSON.stringify(x)})}],['missing check',r=>{const x=structuredClone(payload);delete x.data.runtimeVerification.checks.databaseReadback;return r.fulfill({contentType:'application/json',body:JSON.stringify(x)})}],['hash tamper',r=>{const x=structuredClone(payload);x.data.state.renderer.inputLayout='STACKED';return r.fulfill({contentType:'application/json',body:JSON.stringify(x)})}]];
 for(const[n,handler]of unknownCases){await page.route('**/admin-ajax.php',handler);await save.click();await feedback.locator('..').waitFor();await idle();assert.equal(await root.locator('[data-vf-render-status]').getAttribute('data-status'),'unknown',n);assert.equal(await edit('defaultMode').inputValue(),'STANDARD');assert.equal(await revision.inputValue(),initial);assert(await save.isVisible()&&!await save.isDisabled());await page.unroute('**/admin-ajax.php');passed('unknown readback preserves draft: '+n);}
 await page.screenshot({path:'proof/render-unconfirmed-1440.png',fullPage:true});await root.locator('[data-vf-render-discard]').click();assert.equal(await edit('defaultMode').inputValue(),'HYBRID');assert.equal(await root.locator('[data-vf-render-status]').getAttribute('data-status'),'unknown');assert(await verify.isVisible());passed('discard does not falsely confirm an uncertain save');
 await page.clock.install();await page.route('**/admin-ajax.php',()=>new Promise(()=>{}));await verify.click();await page.clock.fastForward(21000);await idle();assert((await feedback.innerText()).includes('超时'));assert.equal(await root.locator('[data-vf-render-status]').getAttribute('data-status'),'unknown');await page.unroute('**/admin-ajax.php');await page.clock.resume();passed('timeout / retry controls restored');rr=request();await verify.click();await rr;await idle();assert.equal(await root.locator('[data-vf-render-status]').getAttribute('data-status'),'pass');passed('real retry resolves uncertainty');
 // Real stale-revision rejection remains stale on every retry and cannot overwrite the winner.
 const before=cli('vf_theme_bootstrap_require_many(["services/renderer-config-service.php"]);echo vf_tools_theme_renderer_readback()["revision"];').trim();await edit('defaultMode').selectOption('STANDARD');await revision.evaluate(n=>n.value='0'.repeat(64));for(let i=0;i<2;i++){rr=request();await save.click();assert.equal((await rr).status(),409);await idle();assert.equal(await revision.inputValue(),'0'.repeat(64));assert.equal(await edit('defaultMode').inputValue(),'STANDARD');}assert.equal(cli('vf_theme_bootstrap_require_many(["services/renderer-config-service.php"]);echo vf_tools_theme_renderer_readback()["revision"];').trim(),before);passed('real revision conflict / repeated retry cannot overwrite winner');await page.reload();await advanced.locator('summary').click();
 for(const[k,v]of Object.entries({widgetHostApiVersion:'99.0.0',primitiveProfile:'UNREGISTERED',accessibilityProfile:'UNREGISTERED',supportedProjectionSchemaRange:'>=2.0.0 <3.0.0'})){await edit(k).fill(v);rr=request();await save.click();const invalid=await rr;assert.equal(invalid.status(),422);assert.equal((await invalid.json()).data.failureCode,'VALIDATION_FAILED');await idle();assert.equal(await edit(k).inputValue(),v);await root.locator('[data-vf-render-discard]').click();passed('unregistered configuration rejected: '+k);}
 const cfg=await page.evaluate(()=>({ajaxUrl:VFThemeRender.ajaxUrl,nonce:VFThemeRender.nonce}));const fields=await form.evaluate(n=>Object.fromEntries(new FormData(n)));fields.action='vf_theme_render_save';fields.nonce=cfg.nonce;
 let denied=await context.request.post(cfg.ajaxUrl,{form:{...fields,'renderer[unknownField]':'1'}});assert.equal(denied.status(),422);denied=await context.request.post(cfg.ajaxUrl,{form:{...fields,'renderer[defaultMode]':'UNKNOWN'}});assert.equal(denied.status(),422);denied=await context.request.post(cfg.ajaxUrl,{form:{...fields,nonce:'invalid-nonce'}});assert(denied.status()>=400);const anon=await browser.newContext();denied=await anon.request.post(cfg.ajaxUrl,{form:fields});assert(denied.status()>=400||await denied.text()==='0');await anon.close();passed('unknown fields / invalid enum / nonce / guest rejection');
 const native=await browser.newContext({javaScriptEnabled:false,storageState:await context.storageState()}),np=await native.newPage();await np.goto(url);await np.locator('[name="renderer[defaultMode]"]').selectOption('STANDARD');await Promise.all([np.waitForURL(/vf_theme_notice=render-saved/),np.locator('[data-vf-render-save]').click()]);assert.equal(await np.locator('[name="renderer[defaultMode]"]').inputValue(),'STANDARD');await native.close();passed('native no-JS save');
 cli('vf_theme_bootstrap_require_many(["services/renderer-config-service.php"]);$r=vf_tools_theme_renderer_readback()["renderer"];update_option("vf_render_good_state",$r);$r["resultKinds"]=["SUMMARY"];update_option(vf_tools_theme_renderer_option_key(),$r,false);');await page.goto(url);assert.equal(await root.locator('[data-vf-render-status]').getAttribute('data-status'),'blocked');await edit('defaultMode').selectOption('HYBRID');assert.equal(await root.locator('[data-vf-render-status]').getAttribute('data-status'),'blocked');assert(await root.locator('[data-vf-render-status]').isVisible());await page.screenshot({path:'proof/render-blocked-1440.png',fullPage:true});setSettings({});passed('true blocked contract remains visible');
 // Actual public consumers, independently configured through the persisted canonical option.
 setSettings({defaultMode:'HYBRID'});await page.goto(fixture);assert.equal(await page.locator('[data-vf-v6-renderer=HYBRID]').count(),1);assert(await page.locator('[data-vf-widget-surface]').isVisible());assert.equal(await page.locator('[data-vf-widget-surface] script,[data-vf-widget-surface] [onerror]').count(),0);assert.equal(await page.evaluate(()=>window.UNSAFE_WIDGET),undefined);passed('default mode actual consumer / widget sanitization');await page.goto(fixture+'&mode=STANDARD');assert.equal(await page.locator('[data-vf-v6-renderer=HYBRID]').count(),0);passed('explicit page mode overrides default');await page.goto(fixture+'&mode=INVALID');assert.equal(await page.locator('[data-vf-v6-renderer=BLOCKED]').count(),1);assert(await page.locator('.vf-tools-product-page--blocked').count()||await page.locator('.vf-module-fallback').count());passed('invalid explicit projection is blocked');
 const publicWidths=[];
 setSettings({inputLayout:'SPLIT_WHEN_SAFE'});
 for(const width of [1920,1440,1319,1024,768,390]){await page.setViewportSize({width,height:1000});await page.goto(fixture+'&mode=STANDARD');const geom=await page.locator('.vf-tools-standard-inputs').evaluate(n=>{const b=Array.from(n.children).map(c=>c.getBoundingClientRect());return{x:b.map(r=>r.x),overflow:document.documentElement.scrollWidth-innerWidth}});assert(geom.overflow<=1);assert(width>768?geom.x[1]>geom.x[0]+10:Math.abs(geom.x[1]-geom.x[0])<1);assert(await page.locator('[name=vf_parameter_required]').isVisible());assert.equal(await page.locator('[name=vf_parameter_optional]').isVisible(),false);await page.locator('[data-vf-parameter-disclosure] summary').focus();await page.keyboard.press('Enter');assert(await page.locator('[name=vf_parameter_optional]').isVisible());await page.locator('[name=vf_parameter_optional]').selectOption('B');await page.locator('[name=vf_parameter_enabled]').check();assert(await page.locator('[name=vf_parameter_enabled]').isChecked());publicWidths.push({width,status:'PASS',geometry:geom});await page.screenshot({path:'proof/render-public-'+width+'.png',fullPage:true});}passed('public input split / safe mobile stack / required visible / optional keyboard controls at six widths');
 await page.setViewportSize({width:1440,height:1000});setSettings({inputLayout:'STACKED',parameterLayout:'VISIBLE',progressPresentation:'STAGE_ONLY'});await page.goto(fixture+'&mode=STANDARD');assert.equal(await page.locator('[data-vf-parameter-disclosure]').count(),0);assert(await page.locator('[name=vf_parameter_optional]').isVisible());assert.equal(await page.locator('.vf-tools-standard-inputs').evaluate(n=>new Set(Array.from(n.children).map(x=>x.getBoundingClientRect().x)).size),1);await page.locator('[data-vf-runtime-progress]').evaluate(n=>{n.hidden=false;n.querySelector('progress').value=42;n.querySelector('progress').max=100;});assert.equal(await page.locator('[data-vf-runtime-progress] progress').isVisible(),false);assert(await page.locator('[data-vf-runtime-progress]>span').isVisible());passed('stacked / always visible parameters / stage-only progress');setSettings({});await page.reload();await page.locator('[data-vf-runtime-progress]').evaluate(n=>n.hidden=false);assert(await page.locator('[data-vf-runtime-progress] progress').isVisible());assert.equal(await page.locator('[data-vf-runtime-progress] progress').getAttribute('value'),null);await page.locator('[data-vf-runtime-progress] progress').evaluate(n=>{n.value=42;n.max=100});assert.equal(await page.locator('[data-vf-runtime-progress] progress').evaluate(n=>n.value),42);passed('stage or actual percent / no fabricated percentage');
 for(const strict of [false,true]){setSettings({mobileFallback:strict?'BLOCK_UNSUPPORTED_WIDGET':'HOST_CONTROLLED'});for(const support of ['FULL','LIMITED','UNSUPPORTED']){await page.setViewportSize({width:1440,height:1000});await page.goto(fixture+'&mode=PROVIDER_WIDGET&mobile='+support);assert(await page.locator('[data-vf-widget-surface]').isVisible());await page.setViewportSize({width:390,height:1000});const blocked=support==='UNSUPPORTED'||strict&&support==='LIMITED';assert.equal(await page.locator('[data-vf-widget-surface]').isVisible(),!blocked);if(support!=='FULL')assert(await page.locator('.vf-tools-widget-mobile-notice').isVisible());assert(await page.locator('h1').isVisible());passed('actual viewport widget mobile '+support+' / '+(strict?'strict':'auto'));}}
 const mobile=await browser.newContext({viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1'}),mp=await mobile.newPage();await mp.goto(fixture+'&mode=PROVIDER_WIDGET&mobile=LIMITED');assert.equal(await mp.locator('[data-vf-widget-surface]').count(),0);assert(await mp.locator('.vf-tools-widget-mobile-notice').isVisible());await mp.screenshot({path:'proof/render-mobile-strict-390.png',fullPage:true});await mobile.close();passed('server mobile UA blocks strict limited widget before provider callback');
 await page.setViewportSize({width:1440,height:1000});await page.goto(fixture+'&mode=PROVIDER_WIDGET&widget=missing');assert(await page.locator('[data-vf-widget-state=renderer-missing]').isVisible());await page.goto(fixture+'&mode=PROVIDER_WIDGET&widget=invalid');assert(await page.locator('[data-vf-widget-state=blocked]').isVisible());await page.goto(fixture+'&mode=STANDARD&unsafe=1');assert.equal(await page.locator('[data-vf-runtime-preload]').count(),0);assert.equal(await page.locator('[data-vf-runtime-primary-action]').count(),0);passed('missing / incompatible widget and unsafe asset remain blocked');
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}}),no=await nojs.newPage();await no.goto(fixture+'&mode=STANDARD');assert(await no.locator('h1').isVisible());assert((await no.locator('body').innerText()).includes('页面说明始终可以阅读'));assert(await no.locator('noscript').count());await nojs.close();passed('public no-JS product content readable');
 setSettings({});const perf=[];await sample(page);await sample(page);for(let i=0;i<5;i++)perf.push(await sample(page));assert(perf.every(s=>s.optional===0&&!s.executed));const baseline=JSON.parse(fs.readFileSync('proof/baseline.json'));assert(perf.every(s=>s.requests===baseline.performance.samples[0].requests));setSettings({lazyLoadRuntime:false});const eager=[];for(let i=0;i<5;i++)eager.push(await sample(page));assert(eager.every(s=>s.optional===1&&!s.executed));assert.equal(await page.locator('[data-vf-runtime-preload]').getAttribute('integrity'),'sha256:'+require('crypto').createHash('sha256').update(fs.readFileSync('lane/vf-render-fixture.js')).digest('base64'));setSettings({});passed('bounded repeated performance / lazy zero fetch / eager one fetch with no execution');
 assert.equal(errors.length,0,JSON.stringify(errors));fs.writeFileSync('proof/performance.json',JSON.stringify({status:'PASS',scope:'renderer settings and same-origin optional fetch only',dataset:baseline.performance.dataset,width:1440,warmups:2,baseline:baseline.performance.samples,current_default:perf,eager_opt_out:eager,default_request_regression:false,eager_delta:'one explicit optional resource fetch; no execution; accepted setting semantics'},null,2));fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'PASS',wordpress_integration:'REAL_ISOLATED_WORDPRESS',checks,publicWidths,tests,errors},null,2));await browser.close();console.log('RENDER_NATIVE_BROWSER=PASS cases='+tests.length);
})().catch(e=>{console.error(e);process.exit(1)});
