'use strict';
const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright'),{url,login,sample,cli,load,base}=require('./common');
(async()=>{
 cli(load+'update_option("permalink_structure","/%postname%/");foreach(["seo-front-one","seo-front-two"] as $slug){wp_insert_post(["post_type"=>"page","post_status"=>"publish","post_name"=>$slug,"post_title"=>"Synthetic frontend ".$slug,"post_content"=>"Actual isolated WordPress page."]);}flush_rewrite_rules(true);$s=vf_theme_seo_defaults();foreach(["seo-front-one","seo-front-two"] as $slug){$s["virtualRoutePolicy"][]=["routeId"=>str_replace("-","_",$slug),"pageFamily"=>"content","pathPattern"=>$slug,"resolver"=>"vf_theme_url_resolver","canonicalPolicy"=>"self","hreflangPolicy"=>"paired","indexability"=>"index_follow","staticPathPolicy"=>"required"];}update_option(vf_theme_seo_option_key(),$s,false);update_option("vf_seo_baseline_good",$s,false);');
 const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('dialog',d=>d.accept());await login(page);await page.goto(url);
 const r=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST'&&new URLSearchParams(r.request().postData()||'').get('action')==='vf_theme_seo_save');await page.locator('[data-vf-seo-verify]').click();const init=(await(await r).json());fs.writeFileSync('proof/baseline-init.json',JSON.stringify(init));assert(init.success,'baseline verification failed: '+JSON.stringify(init));await page.waitForFunction(()=>document.querySelector('[data-vf-seo-form-shell]').getAttribute('aria-busy')!=='true');
 cli(load+'$s=get_option(vf_theme_seo_option_key());$s["searchIndexability"]="legacy-noindex";update_option(vf_theme_seo_option_key(),$s,false);');await page.goto(url);
 assert(await page.locator('[data-vf-seo-runtime-issues]').isVisible());assert.equal(await page.locator('[data-vf-unsaved-indicator]').innerText(),'已保存');assert.equal(await page.locator('[data-vf-seo-save]').isVisible(),false);const preview=await page.locator('.vf-seo-actions a').getAttribute('href');assert(preview.includes('/wp-admin/')&&preview.includes('tab=preview'));
 await page.screenshot({path:'proof/seo-baseline-bad-state-1440.png',fullPage:true});const failed=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST'&&new URLSearchParams(r.request().postData()||'').get('action')==='vf_theme_seo_save');await page.locator('[data-vf-seo-verify]').click();const body=await(await failed).json();assert.equal(body.data.failureCode,'RUNTIME_CONSUMER_MISMATCH');assert.equal(cli(load+'echo get_option(vf_theme_seo_option_key())["searchIndexability"];').trim(),'legacy-noindex');
 cli(load+'update_option(vf_theme_seo_option_key(),get_option("vf_seo_baseline_good"),false);');await sample(page);await sample(page);const samples=[];for(let i=0;i<5;i++)samples.push(await sample(page));
 fs.writeFileSync('proof/baseline.json',JSON.stringify({status:'REPRODUCED',source_version:process.env.SOURCE_VERSION,invalid_stored_value_cannot_repair_same_candidate:true,false_initial_saved_badge:true,frontend_preview_points_to_admin_acceptance:true,performance:{dataset:'same isolated WordPress SEO route catalogue and two native frontend pages',warmups:2,samples}},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
