'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),{chromium}=require('playwright'),{cli,load,state,setSettings,base,url,login,sample}=require('./common'),check=require('../target/tests/seo-controls-browser-check');
(async()=>{
 async function rootGrid(page,width){await page.locator('[data-vf-seo-form-shell] details').last().locator('summary').click();const grids=await page.locator('.vf-seo-consumer-grid,.vf-seo-owner-grid').evaluateAll(ns=>ns.map(n=>getComputedStyle(n).gridTemplateColumns.split(' ').length));assert(grids.every(n=>n===(width<=782?1:2)),'professional diagnostics must use compact columns');}
 const b=await chromium.launch(),c=await b.newContext(),p=await c.newPage(),errors=[],tests=[],checks=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());const pass=n=>tests.push(n);
 await login(p);const screenshot=p.screenshot.bind(p);p.screenshot=async o=>{await p.evaluate(()=>scrollTo(0,0));return screenshot(o)};
 for(const width of [1920,1440,1319,1024,768,390]){await p.setViewportSize({width,height:1000});await p.goto(url);await p.locator('[data-vf-seo-add-route]').click();assert(await p.evaluate(()=>!!document.querySelector('#wpadminbar').closest('[inert]')&&!!document.querySelector('#adminmenuwrap').closest('[inert]')),'modal must isolate WP header/sidebar');assert(await p.evaluate(()=>{const before=document.activeElement;document.querySelector('#adminmenu a').focus();return document.activeElement===before}),'inert background cannot take native focus');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.querySelector('#wpadminbar').closest('[inert]')===null&&document.querySelector('#adminmenuwrap').closest('[inert]')===null),true);pass('modal background isolation and restoration '+width);}
 for(const width of [1920,1440,1319,1024,768,390]){await p.setViewportSize({width,height:1000});await p.goto(url);checks.push(await check(p,{width,out:path.resolve('proof')}));await rootGrid(p,width);}
 pass('all native controls / keyboard / disclosures / picker search / add / remove / discard at six widths');await p.setViewportSize({width:1440,height:1000});await p.goto(url);
 const root=p.locator('[data-vf-seo-form-shell]'),form=root.locator('[data-vf-seo-form]'),save=root.locator('[data-vf-seo-save]'),verify=root.locator('[data-vf-seo-verify]'),discard=root.locator('[data-vf-seo-discard]'),feedback=root.locator('[data-vf-seo-save-feedback]'),rev=form.locator('[name=revision]'),active=()=>root.locator('[data-vf-seo-route-row]:visible'),edit=k=>active().locator('[data-key='+k+']');
 const response=()=>p.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST'&&/(?:name="action"\r?\n\r?\nvf_theme_seo_save|(?:^|&)action=vf_theme_seo_save(?:&|$))/.test(r.request().postData()||'')),idle=()=>p.waitForFunction(()=>document.querySelector('[data-vf-seo-form-shell]').getAttribute('aria-busy')!=='true');
 cli(load+'$s=get_option(vf_theme_seo_option_key());$s["searchIndexability"]="legacy-noindex";update_option(vf_theme_seo_option_key(),$s,false);');await p.goto(url);
 assert.equal(await root.getAttribute('data-vf-seo-needs-save'),'1');assert.equal(await root.getAttribute('data-vf-seo-dirty'),'0');assert.equal(await p.locator('[data-vf-unsaved-indicator]').innerText(),'配置需处理');assert(await save.isVisible());assert.equal(await verify.isVisible(),false);assert((await root.locator('[data-vf-seo-runtime-issue-list]').innerText()).includes('只允许'));await p.screenshot({path:'proof/seo-repair-needed-1440.png',fullPage:true});
 let repairResponse=response();await save.click();const repaired=await(await repairResponse).json();assert(repaired.success&&repaired.data.ok);assert.equal(repaired.data.stages.execute,'passed');await idle();assert.equal(state().seo.searchIndexability,'noindex_follow');assert.equal(await root.getAttribute('data-vf-seo-needs-save'),'0');assert.equal(await save.isVisible(),false);assert.equal(await p.locator('[data-vf-unsaved-indicator]').innerText(),'已保存');assert.equal(cli(load+'$s=get_option(vf_theme_seo_snapshot_key());echo end($s)["before"]["canonical"]["value"]["searchIndexability"];').trim(),'legacy-noindex');pass('known invalid stored value repaired by explicit same-candidate write with preserved raw snapshot');
 // Existing transactional rollback must also preserve the original invalid value.
 cli(load+'$s=get_option(vf_theme_seo_option_key());$s["searchIndexability"]="legacy-noindex";update_option(vf_theme_seo_option_key(),$s,false);');
 const rollback=JSON.parse(cli(load+'add_filter("pre_update_option_vf_theme_seo",fn($new,$old)=>$old,999,2);$s=vf_theme_seo_readback();echo wp_json_encode(theme_seo_save($s["seo"],$s["revision"],1));'));
 assert.equal(rollback.failureCode,'READBACK_MISMATCH');assert(rollback.rollback.attempted&&rollback.rollback.ok);assert.equal(cli(load+'echo get_option(vf_theme_seo_option_key())["searchIndexability"];').trim(),'legacy-noindex');pass('repair write failure retains original stored configuration and existing rollback');
 await p.goto(url);repairResponse=response();await save.click();assert((await(await repairResponse).json()).success);await idle();pass('repair retry recovers without manually changing unrelated field');await p.screenshot({path:'proof/seo-repair-saved-1440.png',fullPage:true});
 await root.locator('[data-vf-seo-open-picker]').click();await root.locator('[data-vf-seo-picker-search]').fill('seo-front-one');await root.locator('[data-vf-seo-route-choice]:visible').click();
 const front=root.locator('[data-vf-seo-front-preview]');assert(await front.isVisible());assert((await front.getAttribute('href')).endsWith('/seo-front-one/'));const popupPromise=c.waitForEvent('page');await front.click();const popup=await popupPromise;await popup.waitForLoadState();assert(popup.url().endsWith('/seo-front-one/'));assert.equal((await c.request.get(popup.url())).status(),200);await popup.close();assert.equal(p.url(),url);pass('front preview opens real saved native page in new tab and leaves SEO editor');await p.screenshot({path:'proof/seo-real-front-preview-1440.png',fullPage:true});
 await root.locator('[data-vf-seo-open-picker]').click();await root.locator('[data-vf-seo-picker-search]').fill('seo-front-two');await root.locator('[data-vf-seo-route-choice]:visible').click();assert((await front.getAttribute('href')).endsWith('/seo-front-two/'));await edit('pathPattern').fill('unsaved-front-path');assert.equal(await front.isVisible(),false);assert((await root.locator('[data-vf-seo-front-note]').innerText()).includes('保存当前路径'));await discard.click();assert((await front.getAttribute('href')).endsWith('/seo-front-two/'));pass('route switching / unsaved path / discard keep preview target truthful');
 await root.locator('[data-vf-seo-open-picker]').click();await root.locator('[data-vf-seo-picker-search]').fill('/tools/');await root.locator('[data-vf-seo-route-choice]:visible').click();
 const firstPath=await edit('pathPattern').inputValue(),initial=state(),foreignBefore=cli('echo hash("sha256",serialize([get_option("vf_private_update_credential_v1"),get_theme_mod("vf_v8_preservation_sentinel"),get_option("vf_theme_seo_url_last_check"),get_option("vf_theme_seo_inspector_last_result"),get_option("vf_rank_meta_fixture"),get_option("vf_translation_fixture")]));').trim();
 for(const [k,v] of Object.entries({pageFamily:'content',canonicalPolicy:'none',hreflangPolicy:'none',indexability:'noindex_nofollow',staticPathPolicy:'exclude'}))await edit(k).selectOption(v);await edit('pathPattern').fill('  /'+firstPath.toUpperCase()+'-candidate/  ');
 await root.locator('[data-vf-seo-add-route]').click();await root.locator('[data-vf-seo-new-path]').fill('seo-saved-fixture');await root.locator('[data-vf-seo-new-family]').selectOption('content');await root.locator('[data-vf-seo-new-create]').click();
 await root.locator('[data-vf-seo-open-picker]').click();await root.locator('[data-vf-seo-picker-search]').fill(firstPath+'-candidate');await root.locator('[data-vf-seo-route-choice]:visible').click();assert.equal(await edit('canonicalPolicy').inputValue(),'none');assert.equal(await edit('staticPathPolicy').inputValue(),'exclude');pass('switching route retains independent draft values');
 await root.locator('[data-vf-seo-system-details] summary').click();await root.locator('[data-vf-seo-field=searchIndexability]').selectOption('index_follow');assert.equal(await verify.isVisible(),false);
 let release,requests=0;const gate=new Promise(r=>release=r);await p.route('**/admin-ajax.php',async r=>{requests++;await gate;await r.continue()});const rr=response();await save.click();await p.waitForFunction(()=>document.querySelector('[data-vf-seo-form-shell]').getAttribute('aria-busy')==='true');assert.equal(await form.locator('input:not(:disabled),select:not(:disabled),button:not(:disabled)').count(),0);assert.equal(await root.locator('summary:not([aria-disabled=true]),a[href]:not([aria-disabled=true])').count(),0);const beforeUrl=p.url();await root.locator('[data-vf-seo-front-preview]').evaluate(n=>n.click());assert.equal(p.url(),beforeUrl);await form.evaluate(n=>n.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await p.screenshot({path:'proof/seo-saving-1440.png',fullPage:true});release();const saved=await rr,payload=await saved.json();assert(saved.ok()&&payload.success&&payload.data.ok);await idle();assert.equal(requests,1);await p.unroute('**/admin-ajax.php');assert.equal(await root.getAttribute('data-vf-seo-unknown'),'0');assert.equal(await save.isVisible(),false,(await feedback.innerText()));assert((await feedback.innerText()).includes('核对'));assert.equal(await form.locator('select:disabled,input[type=text]:disabled').count(),0);pass('real save / all routes / globals / complete readback / lock preview and summaries / one request / unlock');
 await p.reload();const after=state();assert.equal(after.revision,payload.data.revision);assert.equal(after.seo.searchIndexability,'index_follow');assert.equal(after.seo.virtualRoutePolicy.length,initial.seo.virtualRoutePolicy.length+1);assert.deepEqual(after.seo.virtualRoutePolicy[0],{...initial.seo.virtualRoutePolicy[0],pathPattern:firstPath+'-candidate',pageFamily:'content',canonicalPolicy:'none',hreflangPolicy:'none',indexability:'noindex_nofollow',staticPathPolicy:'exclude'});assert.equal(await rev.inputValue(),after.revision);assert.deepEqual(after.seo.virtualRoutePolicy.slice(1,-1),initial.seo.virtualRoutePolicy.slice(1));assert.equal(cli('echo hash("sha256",serialize([get_option("vf_private_update_credential_v1"),get_theme_mod("vf_v8_preservation_sentinel"),get_option("vf_theme_seo_url_last_check"),get_option("vf_theme_seo_inspector_last_result"),get_option("vf_rank_meta_fixture"),get_option("vf_translation_fixture")]));').trim(),foreignBefore);pass('all six route controls and search persisted / normalized path / sibling and cross-owner/legacy values preserved');
 let request=response();await verify.click();const idempotent=(await(await request).json()).data;await idle();assert(idempotent.idempotent&&idempotent.revision===after.revision);assert.equal(await save.isVisible(),false);pass('real clean recheck is idempotent');
 const oldRev=await rev.inputValue(),oldPath=await edit('pathPattern').inputValue();await edit('pathPattern').fill(oldPath+'-draft');
 const unknown=[['transport',r=>r.abort('failed')],['HTTP 502',r=>r.fulfill({status:502,body:'upstream unavailable'})],['malformed JSON',r=>r.fulfill({contentType:'application/json',body:'{'})],['incomplete success',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({success:true,data:{ok:true}})})]];
 for(const[n,handler] of unknown){await p.route('**/admin-ajax.php',handler);await save.click();await idle();assert.equal(await root.getAttribute('data-vf-seo-unknown'),'1',n);assert.equal(await edit('pathPattern').inputValue(),oldPath+'-draft');assert.equal(await rev.inputValue(),oldRev);assert(await save.isVisible()&&!await save.isDisabled());await p.unroute('**/admin-ajax.php');pass('unknown response preserves draft and revision: '+n);}
 await p.screenshot({path:'proof/seo-unconfirmed-1440.png',fullPage:true});await discard.click();assert.equal(await edit('pathPattern').inputValue(),oldPath);assert.equal(await root.getAttribute('data-vf-seo-unknown'),'1');assert(await verify.isVisible());pass('discard never falsely confirms an uncertain save');
 for(const[n,mutate] of [['missing check',x=>delete x.runtimeVerification.checks.database],['failed check',x=>x.runtimeVerification.checks.static.ok=false],['missing stage',x=>delete x.stages.verify],['route consumer failed',x=>x.runtimeVerification.routes[x.manifest.virtualRoutePolicy[0].routeId].checks.canonical=false],['revision hash tamper',x=>{x.revision='f'.repeat(64);x.manifest.revision=x.revision;x.runtimeVerification.manifest.revision=x.revision;}],['owner duplicate',x=>x.manifest.ownerBoundary.duplicateContentOwner=true],['missing front metadata',x=>delete x.manifest.previewLinks],['wrong front path',x=>x.manifest.previewLinks[x.manifest.virtualRoutePolicy[0].routeId].pathPattern='wrong-route'],['invalid front URL type',x=>x.manifest.previewLinks[x.manifest.virtualRoutePolicy[0].routeId].url=42]]){const x=structuredClone(idempotent);mutate(x);await p.route('**/admin-ajax.php',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({success:true,data:x})}));await verify.click();await idle();assert.equal(await root.getAttribute('data-vf-seo-unknown'),'1',n);assert.equal(await rev.inputValue(),oldRev);await p.unroute('**/admin-ajax.php');pass('incomplete or inconsistent clean readback is not saved: '+n);}
 await p.clock.install();await p.route('**/admin-ajax.php',()=>new Promise(()=>{}));await verify.click();await p.clock.fastForward(21000);await idle();assert((await root.locator('[data-vf-seo-error-message]').innerText()).includes('超时'));assert.equal(await root.getAttribute('data-vf-seo-unknown'),'1');await p.unroute('**/admin-ajax.php');await p.clock.resume();pass('timeout restores controls with explicit unconfirmed result');request=response();await verify.click();await request;await idle();assert.equal(await root.getAttribute('data-vf-seo-unknown'),'0');assert((await feedback.innerText()).includes('核对'));pass('real retry resolves uncertainty');
 await edit('pathPattern').fill(oldPath+'-stale');await rev.evaluate(n=>n.value='0'.repeat(64));const winner=state().revision;for(let i=0;i<2;i++){request=response();await save.click();assert.equal((await request).status(),409);await idle();assert.equal(await edit('pathPattern').inputValue(),oldPath+'-stale');assert.equal(await rev.inputValue(),'0'.repeat(64));assert.equal(state().revision,winner);}pass('real conflict and repeated retry cannot overwrite saved winner');await p.reload();
 const cfg=await p.evaluate(()=>({ajaxUrl:VFThemeSeo.ajaxUrl,nonce:VFThemeSeo.nonce})),fields=await form.evaluate(n=>Object.fromEntries(new FormData(n)));fields.action='vf_theme_seo_save';fields.nonce=cfg.nonce;const serverRev=state().revision;
 for(const[n,extra] of [['unknown top',{'seo[unknownField]':'1'}],['unknown route',{'seo[virtualRoutePolicy][0][unexpected]':'1'}],['non-string route',{'seo[virtualRoutePolicy][0][pathPattern][nested]':'x'}],['non-string global',{'seo[searchIndexability][nested]':'x'}],['invalid enum',{'seo[virtualRoutePolicy][0][canonicalPolicy]':'invalid'}],['fixed preview',{'seo[previewIndexability]':'index_follow'}],['fixed 404',{'seo[notFoundRobots]':'index_follow'}],['language prefix',{'seo[virtualRoutePolicy][0][pathPattern]':'zh/test'}],['duplicate path',{'seo[virtualRoutePolicy][1][pathPattern]':fields['seo[virtualRoutePolicy][0][pathPattern]']}],['duplicate route ID',{'seo[virtualRoutePolicy][1][routeId]':fields['seo[virtualRoutePolicy][0][routeId]']}],['traversal',{'seo[virtualRoutePolicy][0][pathPattern]':'../bad'}]]){const r=await c.request.post(cfg.ajaxUrl,{form:{...fields,...extra}});assert.equal(r.status(),422,n);assert.equal((await r.json()).data.failureCode,'VALIDATION_FAILED',n);assert.equal(state().revision,serverRev,n);pass('registered backend validation preserves canonical data: '+n);}
 let denied=await c.request.post(cfg.ajaxUrl,{form:{...fields,nonce:'invalid-nonce'}});assert.equal(denied.status(),403);const anon=await b.newContext();denied=await anon.request.post(cfg.ajaxUrl,{form:fields});assert(denied.status()>=400||await denied.text()==='0');await anon.close();pass('native nonce and guest rejection');
 for(const value of ['wp-admin','tools/../bad','https://outside.invalid/path','zh/foo','foo?query=1','foo#anchor','a*b','a//b','foo bar']){await edit('pathPattern').fill(value);await save.click();assert(await root.locator('[data-vf-seo-error-summary]').isVisible());assert.equal(state().revision,serverRev);await discard.click();pass('client path validation preserves saved configuration: '+value);}
 await root.locator('[data-vf-seo-add-route]').click();await root.locator('[data-vf-seo-new-path]').fill('new-page-rule');await root.locator('[data-vf-seo-new-create]').click();const count=await root.locator('[data-vf-seo-route-row]').count();await active().locator('[data-vf-seo-remove-route]').click();await root.locator('[data-vf-seo-remove-dialog] [data-vf-seo-dialog-close]').last().click();assert.equal(await root.locator('[data-vf-seo-route-row]').count(),count);await discard.click();pass('remove cancel and discard restore original catalogue');
 const native=await b.newContext({javaScriptEnabled:false,storageState:await c.storageState()}),np=await native.newPage();await np.goto(url);assert.equal(await np.locator('[data-vf-seo-route-row]:visible').count(),state().seo.virtualRoutePolicy.length);assert.equal(await np.locator('[data-vf-seo-open-picker]').isVisible(),false);assert.equal(await np.locator('[data-vf-seo-verify]').isVisible(),false);await np.locator('[data-vf-seo-route-row]').first().locator('[data-key=canonicalPolicy]').selectOption('self');await Promise.all([np.waitForURL(/vf_theme_notice=seo-saved/),np.locator('[data-vf-seo-save]').click()]);assert.equal(await np.locator('[data-vf-seo-route-row]').first().locator('[data-key=canonicalPolicy]').inputValue(),'self');await native.close();pass('no-JS all existing routes editable and native POST persistence');
 cli(load+'$s=vf_theme_seo_readback()["seo"];update_option("vf_seo_good_fixture",$s);$s["foreignOwnerField"]="preserve-me";update_option(vf_theme_seo_option_key(),$s,false);');await p.goto(url);assert(await root.locator('[data-vf-seo-runtime-issues]').isVisible());await edit('pathPattern').fill(oldPath+'-blocked');request=response();await save.click();const blocked=await request;assert.equal((await blocked.json()).data.failureCode,'UNKNOWN_FIELDS');await idle();assert.equal(await edit('pathPattern').inputValue(),oldPath+'-blocked');assert.equal(cli(load+'echo get_option(vf_theme_seo_option_key())["foreignOwnerField"];').trim(),'preserve-me');await p.screenshot({path:'proof/seo-blocked-1440.png',fullPage:true});cli(load+'update_option(vf_theme_seo_option_key(),get_option("vf_seo_good_fixture"),false);');pass('actual unknown stored field remains visible and blocks overwrite');
 cli(load+'$s=vf_theme_seo_defaults();$s["virtualRoutePolicy"]=array_slice($s["virtualRoutePolicy"],0,1);update_option(vf_theme_seo_option_key(),$s,false);');await p.goto(url);assert(await active().locator('[data-vf-seo-remove-route]').isDisabled());pass('last route removal protected');
 cli(load+'update_option(vf_theme_seo_option_key(),get_option("vf_seo_baseline_good"),false);');
 const pc=await b.newContext({viewport:{width:1440,height:1000},storageState:await c.storageState()}),pp=await pc.newPage();await sample(pp);await sample(pp);const perf=[];for(let i=0;i<5;i++)perf.push(await sample(pp));const baseline=JSON.parse(fs.readFileSync('proof/baseline.json')).performance;assert(perf.every(s=>s.requests===baseline.samples[0].requests));const median=a=>[...a].sort((a,b)=>a-b)[2];assert(median(perf.map(x=>x.duration))<=3*median(baseline.samples.map(x=>x.duration))+250);fs.writeFileSync('proof/performance.json',JSON.stringify({status:'PASS',scope:'same SEO route catalogue and same-source registered admin assets',width:1440,warmups:2,baseline:baseline.samples,current:perf,request_regression:false},null,2));await pc.close();pass('bounded five-sample request and latency regression');assert.equal(errors.length,0,JSON.stringify(errors));fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'PASS',wordpress_integration:'REAL_ISOLATED_WORDPRESS',checks,tests,errors},null,2));await b.close();console.log('SEO_NATIVE_BROWSER=PASS cases='+tests.length);
})().catch(e=>{console.error(e);process.exit(1)});
