'use strict';
const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const base='http://127.0.0.1:18880',url=t=>base+'/wp-admin/themes.php?page=vf-theme-modules&tab='+t;
const load='wp_set_current_user(1);vf_theme_bootstrap_require_many(require get_template_directory()."/inc/bootstrap/manifests/admin-tabs/recovery.php");';
const cli=s=>execFileSync('docker',['exec','--user','www-data',process.env.WP,'php','/usr/local/bin/wp','eval',s,'--path=/var/www/html'],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
const state=()=>JSON.parse(cli(load+'echo wp_json_encode(["stores"=>vf_theme_recovery_current_stores(),"revision"=>vf_theme_recovery_hash(vf_theme_recovery_current_stores()),"settings"=>vf_theme_recovery_readback()["settings"],"points"=>vf_theme_revision_store(),"consumers"=>vf_theme_recovery_runtime_verification()]);'));
const foreign=()=>cli('echo hash("sha256",serialize([get_option("vf_ops_preservation_sentinel"),get_option("vf_m3u8_preservation_sentinel"),get_option("vf_private_update_credential_v1"),get_option("vf_rank_meta_fixture"),get_option("vf_translation_fixture"),get_theme_mod("vf_v8_preservation_sentinel"),get_post(get_page_by_path("integration-page")->ID)->post_content]));').trim();
const cases=[],observed=[];let active;
function pass(name,detail={}){cases.push({name,status:'PASS',...detail});fs.writeFileSync('proof/integration-progress.json',JSON.stringify({cases,observed},null,2));console.log('INTEGRATION_PASS '+name);}
const unchanged=(before,after,allowed)=>{for(const key of Object.keys(before.stores))if(!allowed.includes(key))assert.deepEqual(after.stores[key],before.stores[key],'cross-page overwrite of '+key);};
async function login(p){await p.goto(base+'/wp-login.php');await p.locator('#user_login').fill('admin');await p.locator('#user_pass').fill('Synthetic-Only-Update-54!');await Promise.all([p.waitForURL(/wp-admin/),p.locator('#wp-submit').click()]);}
async function postClick(p,button,action){const next=p.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST'&&(r.request().postData()||'').includes(action));await button.click();const r=await next;return{status:r.status(),json:await r.json()};}
(async()=>{
 const b=await chromium.launch(),c=await b.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',acceptDownloads:true}),p=await c.newPage();active=p;p.on('dialog',d=>d.accept());const errors=[];p.on('pageerror',e=>errors.push(e.message));await login(p);const f0=foreign();
 const catalogue=JSON.parse(fs.readFileSync('lane/inventory.json'));
 for(const entry of catalogue.canonical){await p.goto(url(entry.family));assert(await p.locator('[data-vf-admin-tab='+entry.family+']').count());assert(await p.locator('[data-vf-page-id="'+entry.surface_id+'"]').first().isVisible());assert(!/Fatal error|critical error|Parse error/i.test(await p.locator('body').innerText()));}
 await p.goto(url('ads'));assert(await p.locator('[data-vf-admin-tab=render]').count());pass('eight canonical pages and legacy ads successor are reachable');
 // A second settings page stays open while its sibling saves. It must never overwrite a different domain.
 const brand=await c.newPage();brand.on('dialog',d=>d.accept());await brand.goto(url('brand'));await brand.locator('[data-vf-brand-input=siteName]').fill('Integration VF Brand');await brand.locator('[data-vf-brand-input=brand]').fill('#127c82');const pendingDraft=await brand.locator('[data-vf-brand-input=siteName]').inputValue();
 await p.goto(url('navigation'));await p.locator('[data-vf-navigation-workflow-step=header]').click();await p.locator('[data-vf-navigation-copy-language=header]').selectOption('en');await p.locator('[name="navigation[shell][i18n][en][ctaLabel]"]').fill('Integration CTA');await p.locator('[name="navigation[shell][i18n][en][ctaUrl]"]').fill('/integration-page/');await p.locator('[name="navigation[shell][header][height]"]').fill('78');
 await p.locator('[data-vf-navigation-workflow-step=footer]').click();await p.locator('[data-vf-navigation-copy-language=footer]').selectOption('en');await p.locator('[name="navigation[shell][i18n][en][footerNote]"]').fill('Integration footer note');let s0=state(),r=await postClick(p,p.locator('[data-vf-navigation-save]'),'vf_theme_navigation_save');assert(r.json.success&&r.json.data.ok);await p.waitForFunction(()=>document.querySelector('[data-vf-navigation-page]').dataset.vfNavigationDirty==='0');let s1=state();unchanged(s0,s1,['navigation']);assert.equal(s1.stores.navigation.shell.header.height,78);assert.equal(await brand.locator('[data-vf-brand-input=siteName]').inputValue(),pendingDraft);pass('navigation real save preserves another open page draft and all other stores');
 s0=state();r=await postClick(brand,brand.locator('[data-vf-brand-save]'),'vf_theme_brand_save');if(!r.json.success){assert.equal(r.status,409);assert.equal(await brand.locator('[data-vf-brand-input=siteName]').inputValue(),pendingDraft);await brand.reload();await brand.locator('[data-vf-brand-input=siteName]').fill(pendingDraft);await brand.locator('[data-vf-brand-input=brand]').fill('#127c82');r=await postClick(brand,brand.locator('[data-vf-brand-save]'),'vf_theme_brand_save');}assert(r.json.success&&r.json.data.ok);await brand.waitForFunction(()=>document.querySelector('[data-vf-brand-page]').dataset.vfBrandDirty==='0');s1=state();unchanged(s0,s1,['brand','tokens']);assert.equal(s1.stores.brand.siteName,pendingDraft);assert.equal(s1.stores.tokens.brand,'#127c82');await brand.reload();assert.equal(await brand.locator('[data-vf-brand-input=siteName]').inputValue(),pendingDraft);await brand.close();pass('brand save after sibling operation retains navigation and reloads canonical brand');
 await p.goto(url('layout')+'&context=home');const title=p.locator('[name="layout[activeModuleSettings][tool_grid][title]"]');await title.fill('Integration tools grid');s0=state();r=await postClick(p,p.locator('[data-vf-layout-save]'),'vf_theme_layout_save');assert(r.json.success&&r.json.data.ok);await p.waitForFunction(()=>document.querySelector('[data-vf-layout-page]').getAttribute('aria-busy')!=='true');s1=state();unchanged(s0,s1,['layout']);assert.equal(s1.stores.layout.moduleSettings.home.tool_grid.title,'Integration tools grid');await p.reload();assert.equal(await title.inputValue(),'Integration tools grid');pass('layout real save/reload preserves brand navigation and renderer stores');
 await p.goto(url('render'));await p.locator('[name="renderer[defaultMode]"]').selectOption('HYBRID');await p.locator('[name="renderer[inputLayout]"]').selectOption('SPLIT_WHEN_SAFE');s0=state();r=await postClick(p,p.locator('[data-vf-render-save]'),'vf_theme_render_save');assert(r.json.success&&r.json.data.ok);await p.waitForFunction(()=>!document.querySelector('[data-vf-render-page]').hasAttribute('aria-busy'));s1=state();unchanged(s0,s1,['renderer']);assert.equal(s1.stores.renderer.defaultMode,'HYBRID');await p.reload();assert.equal(await p.locator('[name="renderer[defaultMode]"]').inputValue(),'HYBRID');pass('renderer real save/reload preserves all sibling settings');
 await p.goto(url('seo'));await p.locator('[data-vf-seo-add-route]').click();await p.locator('[data-vf-seo-new-path]').fill('integration-page');await p.locator('[data-vf-seo-new-family]').selectOption('content');await p.locator('[data-vf-seo-new-create]').click();const row=p.locator('[data-vf-seo-route-row]:visible');await row.locator('[data-key=canonicalPolicy]').selectOption('self');await row.locator('[data-key=hreflangPolicy]').selectOption('none');await row.locator('[data-key=indexability]').selectOption('noindex_follow');await row.locator('[data-key=staticPathPolicy]').selectOption('exclude');s0=state();r=await postClick(p,p.locator('[data-vf-seo-save]'),'vf_theme_seo_save');assert(r.json.success&&r.json.data.ok);await p.waitForFunction(()=>document.querySelector('[data-vf-seo-form-shell]').getAttribute('aria-busy')!=='true');s1=state();unchanged(s0,s1,['seo']);assert(s1.stores.seo.virtualRoutePolicy.some(x=>x.pathPattern==='integration-page'&&x.indexability==='noindex_follow'));pass('SEO real save preserves sibling settings and persists existing native-page technical policy');
 const saved=state();assert(saved.consumers.ok);const front=await c.newPage();
 async function inspect(stage){await front.goto(base+'/');const result=await front.evaluate(()=>({brand:document.querySelector('#vf-site-header .site-title')?.textContent,brandColor:getComputedStyle(document.documentElement).getPropertyValue('--vf-brand').trim(),headerHeight:document.querySelector('#vf-site-header')?.dataset.vfHeaderHeight,body:document.body.innerText,overflow:document.documentElement.scrollWidth-innerWidth}));assert.equal(result.brand,'Integration VF Brand');assert.equal(result.brandColor,'#127c82');assert.equal(result.headerHeight,'78');assert(result.body.includes('Integration footer note'));assert(result.body.includes('Integration tools grid'),'saved layout title absent from actual public home');assert(result.overflow<=1);await front.goto(base+'/integration-page/');const head=await front.locator('head').evaluate(n=>({canonical:[...n.querySelectorAll('link[rel=canonical]')].map(n=>n.href),robots:[...n.querySelectorAll('meta[name=robots]')].map(n=>n.content),languages:[...n.querySelectorAll('link[hreflang]')].map(n=>n.href)}));assert.deepEqual(head.canonical,[base+'/integration-page/']);assert(head.robots.join(',').includes('noindex'));assert.equal(head.languages.length,0);const xml=await(await c.request.get(base+'/sitemap.xml')).text();assert(!xml.includes('<loc>'+base+'/integration-page/</loc>'));await front.goto(base+'/?vf-render-fixture=1');assert.equal(await front.locator('[data-vf-v6-renderer]').getAttribute('data-vf-v6-renderer'),'HYBRID');observed.push({stage,brand:result.brand,brandColor:result.brandColor,headerHeight:result.headerHeight,layout_title_visible:true,footer_note_visible:true,head,tool_mode:'HYBRID'});pass('actual public HTML/CSS/layout/navigation/tool renderer/Head/XML '+stage);}
 await inspect('after five UI saves');
 await p.goto(url('overview'));let rr=await postClick(p,p.locator('[data-vf-dashboard-refresh]'),'vf_theme_dashboard_refresh');assert(rr.json.success&&rr.json.data.model);assert.equal(rr.json.data.model.rows.length,5);assert(rr.json.data.model.rows.every(x=>x.status!=='blocked'));pass('overview real refresh reads healthy saved domain configuration');
 await p.goto(url('preview'));await p.locator('[data-vf-preview-workflow-step=preview]').click();const frame=p.locator('[data-vf-preview-frame]');await frame.waitFor();await p.waitForFunction(()=>document.querySelector('[data-vf-preview-frame]')?.contentDocument?.querySelector('#vf-site-header .site-title')?.textContent==='Integration VF Brand',{},{timeout:60000});assert((await frame.getAttribute('src')).includes('vf_tools_preview'));pass('signed visual preview loads current public branding after all sibling saves');
 await p.goto(url('recovery'));const root=p.locator('[data-vf-recovery-page]'),tab=k=>root.locator('[data-vf-recovery-workflow-step='+k+']').click(),primary=root.locator('[data-vf-recovery-primary]');rr=await postClick(p,primary,'vf_theme_recovery_snapshot');assert(rr.json.success);const pointId=rr.json.data.snapshotId;assert(pointId);await tab('export');let dp=p.waitForEvent('download');rr=await postClick(p,primary,'vf_theme_recovery_export');assert(rr.json.success);const doc=JSON.parse(fs.readFileSync(await(await dp).path()));assert.deepEqual(doc.stores,saved.stores);assert.equal(state().revision,saved.revision);pass('actual recovery point and parsed download contain the same five saved page domains');
 // A preflight opened on old cross-page state cannot write over a newer brand save.
 await tab('import');await root.locator('[data-vf-recovery-source-mode][value=file]').check();await root.locator('[data-vf-recovery-file]').setInputFiles({name:'integration.json',mimeType:'application/json',buffer:Buffer.from(cli(load+'$p=vf_theme_export_config()["payload"];$p["stores"]["brand"]["siteName"]="Integration preflight candidate";$p["integrity"]["storesSha256"]=vf_theme_recovery_hash($p["stores"]);echo wp_json_encode($p);'))});await p.waitForFunction(()=>!document.querySelector('[data-vf-recovery-primary]').disabled);rr=await postClick(p,primary,'vf_theme_recovery_preflight');assert(rr.json.success);assert.equal(state().revision,saved.revision);const retained=await root.locator('[data-vf-recovery-preflight-token]').inputValue();assert(retained);const bp=await c.newPage();await bp.goto(url('brand'));await bp.locator('[data-vf-brand-input=siteName]').fill('Integration newer brand');r=await postClick(bp,bp.locator('[data-vf-brand-save]'),'vf_theme_brand_save');assert(r.json.success);await bp.waitForFunction(()=>document.querySelector('[data-vf-brand-page]').dataset.vfBrandDirty==='0');await bp.close();const newest=state();await primary.click();rr=await postClick(p,root.locator('[data-vf-recovery-confirm-apply]'),'vf_theme_recovery_apply');assert.equal(rr.status,409);assert.equal(rr.json.data.failureCode,'REVISION_CONFLICT');assert.deepEqual(state().stores,newest.stores);assert.equal(await root.locator('[data-vf-recovery-preflight-token]').inputValue(),'');pass('cross-page revision conflict invalidates old import preflight without overwriting newer saved brand');
 await p.reload();await tab('restore');await root.locator('[data-vf-recovery-picker-open]').click();const radio=root.locator('[data-vf-recovery-revision-choice][value="'+pointId+'"]');assert(await radio.count());await radio.check();await root.locator('[data-vf-recovery-picker-apply]').click();await root.locator('[data-vf-recovery-confirm]').fill('RESTORE');await primary.click();rr=await postClick(p,root.locator('[data-vf-recovery-confirm-apply]'),'vf_theme_recovery_restore');assert(rr.json.success);assert.deepEqual(state().stores,saved.stores);assert(state().consumers.ok);await inspect('after confirmed cross-page recovery');assert(await root.locator('[data-vf-recovery-restore-next]').isVisible());pass('confirmed recovery restores all seven stores and offers next visual-acceptance action');
 await p.goto(url('overview'));rr=await postClick(p,p.locator('[data-vf-dashboard-refresh]'),'vf_theme_dashboard_refresh');assert(rr.json.success);assert((await p.locator('[data-vf-dashboard-maintenance-meta]').innerText()).includes('恢复点'));pass('overview maintenance summary follows real recovery operation');
 const widths=[];for(const width of catalogue.widths){await front.setViewportSize({width,height:1000});await front.goto(base+'/');assert((await front.locator('body').innerText()).includes('Integration tools grid'));const overflow=await front.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert(overflow<=1);widths.push({width,status:'PASS',overflow});await front.screenshot({path:'proof/integration-public-'+width+'.png',fullPage:true});}pass('combined frontend settings remain readable at six widths');assert.equal(foreign(),f0);assert.deepEqual(errors,[]);pass('outside-owner content state credential and Theme-mod sentinels preserved');
 fs.writeFileSync('proof/integration.json',JSON.stringify({status:'PASS',environment:'REAL_ISOLATED_WORDPRESS_SAME_DATABASE',source_sha:process.env.TARGET_SHA,version:process.env.TARGET_VERSION,cases,observed,widths,errors,production:'NOT_EXECUTED',real_provider_domain:'NOT_CLAIMED',owner_acceptance:'NOT_CLAIMED'},null,2));await b.close();
})().catch(async e=>{if(active)await active.screenshot({path:'proof/integration-failure.png',fullPage:true}).catch(()=>{});fs.writeFileSync('proof/integration-failure.json',JSON.stringify({status:'FAIL',message:e.message,stack:e.stack,cases,observed},null,2));console.error(e);process.exit(1)});
