'use strict';
const fs=require('fs'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const base='http://127.0.0.1:18880',url=base+'/wp-admin/themes.php?page=vf-theme-modules&tab=overview';
const cli=php=>execFileSync('docker',['exec','--user','www-data','vf-v8-'+process.env.GITHUB_RUN_ID+'-wp','php','/usr/local/bin/wp','eval',php,'--path=/var/www/html'],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
const load='wp_set_current_user(1);vf_theme_bootstrap_require_many(require get_template_directory()."/inc/bootstrap/manifests/admin-tabs/recovery.php");vf_theme_bootstrap_require_many(require get_template_directory()."/inc/bootstrap/manifests/admin-tabs/overview.php");';
const seed=mode=>cli(load+'$d=vf_theme_recovery_default_stores();foreach(["brand"=>"vf_theme_brand","tokens"=>"vf_theme_tokens","layout"=>"vf_theme_layout","renderer"=>"vf_tools_theme_renderer","ads"=>"vf_theme_ads","seo"=>"vf_theme_seo"] as $k=>$option)update_option($option,$d[$k],false);update_option("vf_theme_recovery",["retention"=>10,"importMode"=>"strict"],false);delete_option("vf_theme_revision_store");delete_option("vf_theme_preview_audit_log");$l=get_option("vf_theme_layout");'+(mode==='legacy'?'foreach(["articleReading","guideReading","problemReading","glossaryReading","basicPageReading"] as $k)foreach(["mobileOrder","sidebarMode","tocPosition"] as $field)unset($l[$k][$field]);update_option("vf_theme_layout",$l,false);':mode==='blocked'?'$l["articleReading"]["mobileOrder"]=["content","content","toc"];update_option("vf_theme_layout",$l,false);':mode==='empty'?'$l["modules"]=[];$l["templates"]=[];$l["toc"]=[];update_option("vf_theme_layout",$l,false);':mode==='bad-renderer'?'$r=get_option("vf_tools_theme_renderer");$r["defaultMode"]="INVALID";update_option("vf_tools_theme_renderer",$r,false);':''));
const snapshot=()=>cli('$x=[];foreach(["vf_theme_options","vf_theme_brand","vf_theme_tokens","vf_theme_layout","vf_theme_navigation","vf_tools_theme_renderer","vf_theme_ads","vf_theme_seo","vf_theme_recovery","vf_theme_revision_store","vf_theme_preview_audit_log","vf_ops_preservation_sentinel","vf_m3u8_preservation_sentinel","vf_private_update_credential_v1"] as $k)$x[$k]=get_option($k,"__MISSING__");$x["mods"]=get_theme_mods();echo hash("sha256",serialize($x));').trim();
const mark={};let failurePage=null,errors=[];
async function login(page,user='admin',password='Synthetic-Only-Update-54!'){await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill(user);await page.locator('#user_pass').fill(password);await Promise.all([page.waitForURL(/wp-admin/),page.locator('#wp-submit').click()]);}
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({timezoneId:'Asia/Shanghai'}),page=await context.newPage();failurePage=page;page.on('pageerror',e=>errors.push(e.message));await login(page);
 seed('legacy');
 const actual=JSON.parse(cli(load+'echo wp_json_encode(["reading"=>vf_theme_layout_readback()["layout"]["articleReading"]["mobileOrder"],"renderer"=>vf_tools_theme_renderer_runtime_verification()["ok"],"layoutModuleFamilies"=>count(array_filter(get_option("vf_theme_layout")["modules"])),"layoutTemplateFamilies"=>count(get_option("vf_theme_layout")["templates"])]);'));
 assert.deepEqual(actual.reading.slice().sort(),['content','sidebar','toc']);assert(actual.renderer);assert.equal(actual.layoutModuleFamilies,20);assert.equal(actual.layoutTemplateFamilies,20);
 await page.goto(url);const root=page.locator('[data-vf-dashboard-root]'),refresh=root.locator('[data-vf-dashboard-refresh]'),feedback=root.locator('[data-vf-dashboard-feedback]');
 const cfg=()=>page.evaluate(()=>({ajaxUrl:VFThemeDashboard.ajaxUrl,nonce:VFThemeDashboard.nonce,action:VFThemeDashboard.action,revision:document.querySelector('[data-vf-dashboard-root]').dataset.vfDashboardRevision}));
 const action=async()=>{const pending=page.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST'&&(r.request().postData()||'').includes('action=vf_theme_dashboard_refresh'));await refresh.click();const response=await pending;const json=await response.json();await page.waitForFunction(()=>document.querySelector('[data-vf-dashboard-root]').getAttribute('aria-busy')==='false');return{response,json};};
 if(process.env.PHASE==='baseline'){
  const initial=await root.getAttribute('data-vf-page-state');assert.equal(initial,'blocked');
  const r=await action();assert(r.json.success);const rows=r.json.data.model.rows;assert.equal(rows.find(x=>x.id==='layout').status,'blocked');assert.equal(rows.find(x=>x.id==='render').status,'blocked');
  cli('$b=get_option("vf_theme_brand");$b["siteName"]="Synthetic concurrent baseline";update_option("vf_theme_brand",$b,false);');const stale=await action();assert.equal(stale.response.status(),409);assert.equal(stale.json.data.failureCode,'REVISION_CONFLICT');
  fs.writeFileSync('proof/baseline.json',JSON.stringify({version:process.env.SOURCE_VERSION,realConsumerChecks:actual,legacyLayoutFalseBlocked:'REPRODUCED',lazyRendererFalseBlocked:'REPRODUCED',readOnlyRefreshRejectsNewerState:'REPRODUCED'},null,2));await browser.close();return;
 }
 assert.equal(await root.getAttribute('data-vf-page-state'),'warning');assert.equal((await root.locator('[data-vf-dashboard-config-ready]').innerText()).trim(),'6');assert.equal((await root.locator('[data-vf-dashboard-config-total]').innerText()).trim(),'6');assert((await root.locator('[data-vf-dashboard-acceptance]').innerText()).includes('待完成'));
 let before=snapshot(),r=await action();assert(r.json.success);assert.equal(snapshot(),before);
 assert.equal(r.json.data.model.rows.find(x=>x.id==='layout').status,'ready');assert.equal(r.json.data.model.rows.find(x=>x.id==='render').status,'ready');
 mark.legacy_effective_layout='PASS';mark.lazy_renderer_consumer='PASS';mark.initial_ajax_same_contract='PASS';mark.configuration_not_owner_acceptance='PASS';mark.read_only='PASS';
 const widths=[];
 for(const width of [1920,1440,1319,1024,768,390]){
  await page.setViewportSize({width,height:1000});await page.goto(url);await page.waitForFunction(()=>!document.querySelector('[data-vf-dashboard-refresh]').hidden);await page.evaluate(()=>document.fonts.ready);
  const metrics=await page.evaluate(()=>{
   const root=document.querySelector('[data-vf-dashboard-root]'),rect=root.getBoundingClientRect(),workspace=root.querySelectorAll('[data-workspace-id]');
   return {width:innerWidth,root:rect.toJSON(),shell:document.querySelector(".vf-v6-shell-header").getBoundingClientRect().toJSON(),head:document.querySelector(".vf-admin-page-head").getBoundingClientRect().toJSON(),overflow:document.documentElement.scrollWidth>innerWidth+1,items:[...workspace].map(a=>{const r=a.getBoundingClientRect(),c=a.querySelector('.vf-overview-workspace-copy').getBoundingClientRect(),t=a.querySelector('.vf-workbench-v4__workspace-title').getBoundingClientRect(),i=a.querySelector('.vf-overview-workspace-action').getBoundingClientRect();return{rect:r.toJSON(),copy:c.toJSON(),title:t.toJSON(),action:i.toJSON(),font:parseFloat(getComputedStyle(a.querySelector('p')).fontSize),helper:parseFloat(getComputedStyle(a.querySelector('small')).fontSize)};}),feedbackVisible:getComputedStyle(root.querySelector('[data-vf-dashboard-feedback]')).display!=='none'};
  });
  assert(!metrics.overflow,JSON.stringify(metrics));assert.equal(metrics.items.length,5);assert(metrics.feedbackVisible);assert(Math.abs(metrics.root.left-metrics.shell.left)<=1&&Math.abs(metrics.root.right-metrics.shell.right)<=1,JSON.stringify(metrics));
  for(let i=0;i<metrics.items.length;i++){const m=metrics.items[i];assert(m.font>=14&&m.helper>=13);assert(m.rect.left>=metrics.root.left&&m.rect.right<=metrics.root.right+1);if(i)assert(m.rect.top>=metrics.items[i-1].rect.bottom-1);if(width>1100)assert(m.title.right<=m.copy.left+1&&m.copy.right<=m.action.left+1);else if(width<=700)assert(m.title.right<=m.action.left+1&&m.copy.top>=m.title.bottom-1);}
  await refresh.focus();assert(await refresh.evaluate(n=>n===document.activeElement));const pending=page.waitForResponse(x=>(x.request().postData()||'').includes('action=vf_theme_dashboard_refresh'));await page.keyboard.press('Enter');const response=await pending;assert((await response.json()).success);await page.waitForFunction(()=>document.querySelector('[data-vf-dashboard-root]').getAttribute('aria-busy')==='false');assert(await feedback.isVisible());
  fs.writeFileSync('proof/overview-metrics-'+width+'.json',JSON.stringify(metrics));await page.screenshot({path:'proof/overview-configured-'+width+'.png',fullPage:true});widths.push({width,status:'PASS',rows:'PASS',fonts:'PASS',keyboard:'PASS',feedback:'PASS',overflow:'PASS'});
 }
 mark.six_viewports='PASS';mark.keyboard_focus='PASS';
 // Exercise the existing content-owner detector through real page and AJAX reads.
 cli('wp_mkdir_p(WP_CONTENT_DIR."/mu-plugins");file_put_contents(WP_CONTENT_DIR."/mu-plugins/overview-owner-fixture.php", base64_decode("PD9waHAgZGVmaW5lKCJSQU5LX01BVEhfVkVSU0lPTiIsIlNZTlRIRVRJQ19URVNUX09OTFkiKTs="));');
 before=snapshot();await page.goto(url);r=await action();assert(r.json.success);assert.equal(r.json.data.model.rows.find(x=>x.id==='seo').status,'ready');assert((await root.locator('[data-workspace-id=seo]').innerText()).includes('Rank Math'));assert.equal(snapshot(),before);
 cli('unlink(WP_CONTENT_DIR."/mu-plugins/overview-owner-fixture.php");');await page.goto(url);r=await action();assert.equal(r.json.data.model.rows.find(x=>x.id==='seo').status,'warning');mark.seo_owner_readback='PASS';

 await page.setViewportSize({width:1440,height:1000});await page.goto(url);
 // A different tab changed a canonical field while this page remained mounted.
 cli('$b=get_option("vf_theme_brand");unset($b["tagline"]);update_option("vf_theme_brand",$b,false);');before=snapshot();r=await action();assert(r.json.success);assert.equal(snapshot(),before);assert.equal((await root.locator('[data-vf-dashboard-config-ready]').innerText()).trim(),'5');assert.equal(await root.getAttribute('data-vf-page-state'),'blocked');assert.equal(new URL(await root.locator('[data-vf-dashboard-next-link]').getAttribute('href')).searchParams.get('tab'),'brand');mark.latest_state_without_reload='PASS';mark.summary_next_synchronized='PASS';await page.screenshot({path:'proof/overview-blocked-1440.png',fullPage:true});
 seed('blocked');await page.goto(url);r=await action();assert.equal(r.json.data.model.rows.find(x=>x.id==='layout').status,'blocked');assert((await root.locator('[data-workspace-id=layout]').innerText()).includes('移动区域顺序无效'));mark.true_invalid_layout='PASS';
 seed('empty');
 const layoutTruth=()=>JSON.parse(cli(load+'$l=get_option("vf_theme_layout",[]);echo wp_json_encode(["modules"=>count(array_filter((array)($l["modules"]??[]))),"templates"=>count((array)($l["templates"]??[])),"tocFields"=>count((array)($l["toc"]??[])),"dashboard"=>vf_theme_dashboard_layout_state()["ok"]]);'));
 const incompleteBefore=layoutTruth();await page.goto(url);r=await action();const incompleteAfter=layoutTruth();
 fs.writeFileSync('proof/incomplete-layout.json',JSON.stringify({before:incompleteBefore,after:incompleteAfter,row:r.json.data.model.rows.find(x=>x.id==='layout')},null,2));
 assert.equal(r.json.data.model.rows.find(x=>x.id==='layout').status,incompleteAfter.dashboard?'ready':'blocked');
 if(incompleteAfter.dashboard)assert(incompleteAfter.modules===20&&incompleteAfter.templates===20&&incompleteAfter.tocFields>=5);else assert(incompleteAfter.modules<20||incompleteAfter.templates<20||incompleteAfter.tocFields<5);
 mark.incomplete_canonical_layout='PASS';
 seed('bad-renderer');await page.goto(url);r=await action();assert.equal(r.json.data.model.rows.find(x=>x.id==='render').status,'blocked');mark.true_invalid_renderer='PASS';
 seed('legacy');await page.goto(url);r=await action();assert(r.json.success);
 // Detect a changing snapshot, without persisting the fault-injection values.
 before=snapshot();const race=JSON.parse(cli(load+'add_filter("option_vf_theme_brand",static function($v){static $i=0;$v["siteName"]="Synthetic read race ".(++$i);return $v;});echo wp_json_encode(vf_theme_refresh_dashboard("stale"));'));assert.equal(race.failureCode,'READBACK_MISMATCH');assert.equal(snapshot(),before);mark.readback_race_rejected='PASS';
 const endpoint=await cfg();const nonceBad=await context.request.post(endpoint.ajaxUrl,{form:{action:endpoint.action,nonce:'INVALID',revision:endpoint.revision}});assert.equal(nonceBad.status(),403);assert.equal((await nonceBad.json()).data.failureCode,'NONCE_INVALID');mark.nonce='PASS';
 const anon=await browser.newContext();const guest=await anon.request.post(endpoint.ajaxUrl,{form:{action:endpoint.action}});assert(guest.status()>=400||await guest.text()==='0');await anon.close();mark.guest='PASS';
 cli('$id=wp_create_user("overview-subscriber","Synthetic-overview-only-83!","overview-subscriber@example.invalid");if(is_wp_error($id))$id=username_exists("overview-subscriber");');
 const limited=await browser.newContext(),lp=await limited.newPage();await login(lp,'overview-subscriber','Synthetic-overview-only-83!');const deny=await limited.request.post(endpoint.ajaxUrl,{form:{action:endpoint.action,nonce:endpoint.nonce,revision:endpoint.revision}});assert.equal(deny.status(),403);assert.equal((await deny.json()).data.failureCode,'PERMISSION_DENIED');await limited.close();mark.permission='PASS';assert.equal(snapshot(),before);
 // Busy feedback is visible and repeated invocation produces only one request.
 let seen=0,release;const held=new Promise(resolve=>release=resolve);
 await page.route('**/admin-ajax.php',async route=>{if((route.request().postData()||'').includes('action=vf_theme_dashboard_refresh')){seen++;await held;}await route.continue();});
 await refresh.click();await page.waitForTimeout(300);assert(await refresh.isDisabled());assert((await feedback.innerText()).includes('正在读取'));await refresh.evaluate(n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));assert.equal(seen,1);release();await page.waitForFunction(()=>document.querySelector('[data-vf-dashboard-root]').getAttribute('aria-busy')==='false');await page.unroute('**/admin-ajax.php');mark.busy_lock='PASS';
 // Failed requests keep the last diagnosis and expose a reusable control.
 const oldCount=await root.locator('[data-vf-dashboard-config-ready]').innerText();
 for(const type of ['network','invalid-json','incomplete','http']){
  await page.route('**/admin-ajax.php',route=>!(route.request().postData()||'').includes('action=vf_theme_dashboard_refresh')?route.continue():type==='network'?route.abort('failed'):route.fulfill({status:type==='http'?503:200,contentType:'application/json',body:type==='invalid-json'?'not json':JSON.stringify(type==='incomplete'?{success:true,data:{revision:'incomplete'}}:{success:false,data:{message:'Synthetic server unavailable'}})}));
  await refresh.click();await page.waitForFunction(()=>document.querySelector('[data-vf-dashboard-root]').getAttribute('aria-busy')==='false');assert(await feedback.isVisible());assert.equal(await feedback.getAttribute('data-status'),'error');assert.equal(await refresh.isDisabled(),false);assert.equal(await root.locator('[data-vf-dashboard-config-ready]').innerText(),oldCount);await page.unroute('**/admin-ajax.php');r=await action();assert(r.json.success);mark[type+'_retry']='PASS';
 }
 await page.route('**/admin-ajax.php',async route=>{if((route.request().postData()||'').includes('action=vf_theme_dashboard_refresh')){await new Promise(resolve=>setTimeout(resolve,23000));try{await route.continue();}catch{}}else await route.continue();});
 await refresh.click();await page.waitForFunction(()=>document.querySelector('[data-vf-dashboard-root]').getAttribute('aria-busy')==='false',{},{timeout:25000});assert((await feedback.innerText()).includes('超时'));assert(!await refresh.isDisabled());await page.screenshot({path:'proof/overview-error-1440.png',fullPage:true});await page.unroute('**/admin-ajax.php');r=await action();assert(r.json.success);mark.timeout_retry='PASS';assert.equal(snapshot(),before);
 // Every current page-body entry reaches its canonical page, using keyboard Enter.
 const ids={brand:'THM-BRAND-001',layout:'THM-LAYOUT-001',navigation:'THM-NAV-001',render:'THM-RENDER-001',seo:'THM-SEO-001'};
 for(const [id,pageId]of Object.entries(ids)){await page.goto(url);const link=root.locator('[data-workspace-id='+id+']');await link.focus();assert(await link.evaluate(n=>n===document.activeElement));await Promise.all([page.waitForURL(u=>u.searchParams.get('tab')===id),page.keyboard.press('Enter')]);assert(await page.locator('[data-vf-page-id="'+pageId+'"]').first().isVisible());assert.equal(await page.locator('text=There has been a critical error').count(),0);}
 mark.workspace_routes='PASS';
 await page.goto(url);await Promise.all([page.waitForURL(u=>u.searchParams.get('tab')==='preview'),root.locator('[data-vf-dashboard-next-link]').click()]);assert(await page.locator('[data-vf-page-id="THM-PREVIEW-001"]').first().isVisible());mark.next_route='PASS';
 await page.goto(url);const notices=await root.locator('[data-vf-dashboard-notice-list] a').evaluateAll(a=>a.map(n=>({href:n.href,label:n.innerText})));assert(notices.length>=1);for(const n of notices){await page.goto(n.href);assert(await page.locator('.vf-theme-admin').isVisible());}mark.notice_routes='PASS';
 await page.goto(url);await Promise.all([page.waitForURL(u=>u.searchParams.get('tab')==='recovery'),root.locator('[data-vf-dashboard-maintenance-link]').click()]);assert(await page.locator('[data-vf-page-id="THM-BACKUP-001"]').isVisible());mark.maintenance_route='PASS';
 // Real update to retention and a point is reflected by the same read-only refresh.
 cli(load+'update_option("vf_theme_recovery",["retention"=>14,"importMode"=>"strict"],false);vf_theme_revision_store_create("manual");');await page.goto(url);r=await action();assert(r.json.success);assert((await root.locator('[data-vf-dashboard-maintenance-meta]').innerText()).includes('1 个恢复点'));assert((await root.locator('[data-vf-dashboard-maintenance-meta]').innerText()).includes('14'));assert(!(await root.locator('[data-vf-dashboard-notice-list]').innerText()).includes('尚未建立恢复点'));mark.notices_maintenance_synchronized='PASS';
 const nojs=await browser.newContext({javaScriptEnabled:false,storageState:await context.storageState(),viewport:{width:390,height:1000}}),np=await nojs.newPage();await np.goto(url);const native=np.locator('[data-vf-dashboard-reload]');assert(await native.isVisible());assert(!await np.locator('[data-vf-dashboard-refresh]').isVisible());seed('blocked');before=snapshot();await Promise.all([np.waitForNavigation(),native.click()]);assert.equal(await np.locator('[data-vf-dashboard-root]').getAttribute('data-vf-page-state'),'blocked');assert.equal(snapshot(),before);await np.screenshot({path:'proof/overview-native-390.png',fullPage:true});await nojs.close();mark.native_refresh='PASS';
 assert.equal(errors.length,0,JSON.stringify(errors));
 fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'PASS',checks:widths,functional:mark,errors,owner_real_use:'POST_PRODUCTION_REQUIRED',production:'NOT_EXECUTED'},null,2));await browser.close();console.log('OVERVIEW_REAL_WORDPRESS_BROWSER=PASS');
})().catch(async error=>{if(failurePage){await failurePage.screenshot({path:'proof/overview-failed.png',fullPage:true});fs.writeFileSync('proof/overview-failure.json',JSON.stringify({message:error.message,errors,completed:mark},null,2));}console.error(error);process.exit(1);});

