'use strict';
const fs=require('fs'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const check=require('../target/tests/recovery-controls-browser-check'),base='http://127.0.0.1:18880',url=base+'/wp-admin/themes.php?page=vf-theme-modules&tab=recovery';
const cli=php=>execFileSync('docker',['exec','--user','www-data','vf-v8-'+process.env.GITHUB_RUN_ID+'-wp','php','/usr/local/bin/wp','eval',php,'--path=/var/www/html'],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
const load='wp_set_current_user(1);vf_theme_bootstrap_require_many(require get_template_directory()."/inc/bootstrap/manifests/admin-tabs/recovery.php");';
const state=()=>JSON.parse(cli(load+'echo wp_json_encode(["revision"=>vf_theme_recovery_hash(vf_theme_recovery_current_stores()),"settings"=>vf_theme_recovery_readback()["settings"],"points"=>count(vf_theme_revision_store()),"stores"=>vf_theme_recovery_current_stores()]);'));
const checkDisclosure=async(page,root,screenshot)=>{
 const details=root.locator('.vf-recovery-professional'),summary=details.locator(':scope > summary'),label=summary.locator('em');
 if(await details.getAttribute('open')!==null)await summary.click();
 assert.equal((await label.innerText()).trim(),'展开');assert.equal(await label.locator('span:visible').count(),1);
 await summary.focus();await page.keyboard.press('Enter');assert.equal(await details.getAttribute('open'),'');
 assert.equal((await label.innerText()).trim(),'收起');assert.equal(await label.locator('span:visible').count(),1);
 if(screenshot)await page.screenshot({path:screenshot,fullPage:true});
 await summary.focus();await page.keyboard.press('Enter');assert.equal(await details.getAttribute('open'),null);
 assert.equal((await label.innerText()).trim(),'展开');assert.equal(await label.locator('span:visible').count(),1);
};
let failurePage=null,failureErrors=[];
const changed=name=>JSON.parse(cli(load+'$p=vf_theme_export_config()["payload"];$p["stores"]["brand"]["siteName"]='+JSON.stringify(name)+';$p["integrity"]["storesSha256"]=vf_theme_recovery_hash($p["stores"]);echo wp_json_encode($p);'));
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({timezoneId:'Asia/Shanghai'}),page=await context.newPage(),errors=[];
 failurePage=page;failureErrors=errors;page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill('admin');await page.locator('#user_pass').fill('Synthetic-Only-Update-54!');await Promise.all([page.waitForURL(/wp-admin/),page.locator('#wp-submit').click()]);
 cli(load+'delete_option(vf_theme_revision_store_key());delete_option(vf_tools_theme_post_restore_preview_key());delete_option(vf_theme_recovery_last_operation_key());update_option("vf_ops_preservation_sentinel",["keep"=>"ops"]);update_option("vf_m3u8_preservation_sentinel",["keep"=>"provider"]);');
 const checks=[];
 for(const width of [1920,1440,1319,1024,768,390]){
  await page.setViewportSize({width,height:1000});await page.goto(url);await page.reload();await page.waitForFunction(()=>document.querySelector('[data-vf-recovery-page]')?.getAttribute('aria-busy')===null);
  fs.writeFileSync('proof/layout-metrics-'+width+'.json',JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('.vf-v6-shell-header,.vf-admin-page-head,.vf-admin-workspace,.vf-recovery-page')].map(n=>({class:n.className,rect:n.getBoundingClientRect().toJSON(),width:getComputedStyle(n).width,margin:getComputedStyle(n).margin,padding:getComputedStyle(n).padding,display:getComputedStyle(n).display,parent:n.parentElement.className})))));
  const initialRoot=page.locator('[data-vf-recovery-page]');await page.screenshot({path:'proof/recovery-default-'+width+'.png',fullPage:true});await initialRoot.locator('[data-vf-recovery-workflow-step=import]').click();await page.screenshot({path:'proof/recovery-import-empty-'+width+'.png',fullPage:true});await initialRoot.locator('[data-vf-recovery-workflow-step=restore]').click();await page.screenshot({path:'proof/recovery-restore-empty-'+width+'.png',fullPage:true});await initialRoot.locator('[data-vf-recovery-workflow-step=status]').click();
  try{checks.push(await check(page,width));}catch(e){await page.screenshot({path:'proof/recovery-controls-failed-'+width+'.png',fullPage:true});throw e;}for(const key of ['status','export','import','restore']){await initialRoot.locator('[data-vf-recovery-workflow-step='+key+']').click();await checkDisclosure(page,initialRoot,key==='status'?'proof/recovery-details-open-'+width+'.png':null);}await initialRoot.locator('[data-vf-recovery-workflow-step=status]').click();await page.screenshot({path:'proof/recovery-default-'+width+'.png',fullPage:true});
  const root=page.locator('[data-vf-recovery-page]');await root.locator('[data-vf-recovery-workflow-step=import]').click();await page.screenshot({path:'proof/recovery-import-invalid-'+width+'.png',fullPage:true});
  await root.locator('[data-vf-recovery-workflow-step=restore]').click();await page.screenshot({path:'proof/recovery-restore-empty-'+width+'.png',fullPage:true});
 }
 await page.setViewportSize({width:1440,height:1000});await page.goto(url);await page.reload();const root=page.locator('[data-vf-recovery-page]'),primary=root.locator('[data-vf-recovery-primary]');
 const tab=async key=>root.locator(`[data-vf-recovery-workflow-step=${key}]`).click();
 const action=async click=>{const pending=page.waitForResponse(async r=>{if(!r.url().includes('admin-ajax.php')||r.request().method()!=='POST')return false;if((r.request().postData()||'').includes('vf_theme_recovery_'))return true;try{const body=await r.json();return typeof body?.data?.actionId==='string'&&body.data.actionId.startsWith('theme.recovery');}catch{return false;}});await click();const response=await pending;const data=await response.json();await page.waitForFunction(()=>document.querySelector('[data-vf-recovery-page]').getAttribute('aria-busy')==='false');return {response,data};};
 const perform=async()=>action(()=>primary.click());const config=()=>page.evaluate(()=>({ajaxUrl:VFThemeRecovery.ajaxUrl,nonce:VFThemeRecovery.nonce}));
 const requestBefore=state();const requestCheck=await require('../target/tests/recovery-request-browser-check')(page);assert.deepEqual(state(),requestBefore);fs.writeFileSync('proof/recovery-requests.json',JSON.stringify(requestCheck,null,2));
 const before=state();let r=await perform();assert(r.data.success);assert.equal(state().points,1);assert.equal(state().revision,before.revision);assert.equal(await root.locator('[data-vf-recovery-record-count]').innerText(),'1');assert.equal(await root.locator('[data-vf-recovery-capacity-summary]').textContent(),'1/10');
 // The first point immediately exposes the restore form, without navigation/reload.
 await tab('restore');assert(await root.locator('[data-vf-recovery-form=restore]').isVisible());assert.equal(await root.locator('[data-vf-recovery-empty]').isVisible(),false);await root.locator('[data-vf-recovery-picker-open]').click();const picker=root.locator('[data-vf-recovery-dialog=picker]');assert.equal(await picker.locator('[data-vf-recovery-revision-choice]').count(),1);await picker.locator('[data-vf-recovery-revision-choice]').first().check();await picker.locator('button').filter({hasText:'取消'}).click();assert.equal(await root.locator('[data-vf-recovery-revision-id]').inputValue(),'');
 await root.locator('[data-vf-recovery-picker-open]').click();await picker.locator('[data-vf-recovery-revision-choice]').first().check();await picker.locator('[data-vf-recovery-picker-apply]').click();const firstId=await root.locator('[data-vf-recovery-revision-id]').inputValue();assert(firstId);
 await tab('export');const downloadPromise=page.waitForEvent('download');r=await perform();assert(r.data.success);const download=await downloadPromise;const buffer=fs.readFileSync(await download.path());const exported=JSON.parse(buffer);assert.equal(Object.keys(exported.stores).length,7);assert.deepEqual(exported.stores,state().stores);assert.equal(state().points,1);assert.equal(state().revision,before.revision);
 const nojs=await browser.newContext({javaScriptEnabled:false,storageState:await context.storageState()}),np=await nojs.newPage();await np.goto(url);await checkDisclosure(np,np.locator('[data-vf-recovery-page]'),'proof/recovery-details-native-1280.png');const nd=np.waitForEvent('download');await np.getByRole('button',{name:'验证并下载备份',exact:true}).click();const nativeDownload=await nd;assert.deepEqual(JSON.parse(fs.readFileSync(await nativeDownload.path(),'utf8')).stores,state().stores);assert.equal(state().points,1);assert.equal(state().revision,before.revision);await nojs.close();
 await tab('import');await root.locator('[data-vf-recovery-source-mode][value=file]').check();await root.locator('[data-vf-recovery-file]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer});await page.waitForFunction(()=>!document.querySelector('[data-vf-recovery-primary]').disabled);r=await perform();assert(r.data.success&&r.data.data.totalChangedCount===0);assert(await primary.isDisabled());assert.equal(state().points,1);
 const source=JSON.stringify(changed('Synthetic UI imported name'));await root.locator('[data-vf-recovery-source-mode][value=paste]').check();const jsonLimit=Number(await root.getAttribute('data-vf-recovery-json-max-bytes'));await root.locator('[data-vf-recovery-json]').fill('a'.repeat(jsonLimit+1));await page.waitForTimeout(230);assert(await primary.isDisabled());assert((await root.locator('[data-vf-recovery-local-message]').textContent()).includes('超过'));assert.equal(state().revision,before.revision);await root.locator('[data-vf-recovery-json]').fill(source);await root.locator('[name="recovery[retention]"]').fill('14');await page.waitForTimeout(230);r=await perform();assert(r.data.success&&r.data.data.totalChangedCount===2);assert.equal(state().revision,before.revision);assert.equal(state().settings.retention,10);assert.equal(state().points,1);assert((await root.locator('[data-vf-recovery-preflight-diff]').innerText()).includes('工具页渲染'));
 // A changed draft immediately discards the reviewed token.
 await root.locator('[data-vf-recovery-json]').fill(source+' ');assert.equal(await root.locator('[data-vf-recovery-preflight-token]').inputValue(),'');await page.waitForTimeout(230);r=await perform();assert(r.data.success);await page.screenshot({path:'proof/recovery-preflight-1440.png',fullPage:true});
 let token=await root.locator('[data-vf-recovery-preflight-token]').inputValue();cli(load+'$t='+JSON.stringify(token)+';$p=vf_theme_recovery_preflight_read($t);$p["expiresAt"]=gmdate("c",time()-60);vf_theme_recovery_preflight_store($t,$p);');await primary.click();r=await action(()=>root.locator('[data-vf-recovery-confirm-apply]').click());assert.equal(r.data.data.failureCode,'PREFLIGHT_EXPIRED');assert.equal(await root.locator('[data-vf-recovery-preflight-token]').inputValue(),'');assert.equal(await root.locator('[data-vf-recovery-json]').inputValue(),source+' ');
 r=await perform();assert(r.data.success);await primary.click();await root.locator('[data-vf-recovery-dialog=confirm]').getByRole('button',{name:'取消',exact:true}).click();assert.equal(state().revision,before.revision);
 // Drop a real write during an authenticated apply, then retry from the preserved draft.
 const failedState=state(),plugin="<?php function vf_synthetic_recovery_write_failure($new,$old){return $old;} add_filter('pre_update_option_vf_theme_brand','vf_synthetic_recovery_write_failure',10,2);";
 cli('if(!wp_mkdir_p(WPMU_PLUGIN_DIR)||file_put_contents(WPMU_PLUGIN_DIR."/synthetic-recovery-write-failure.php",'+'base64_decode('+JSON.stringify(Buffer.from(plugin).toString('base64'))+')'+')===false)throw new Exception("failure fixture persistence failed");');
 cli('if(!function_exists("vf_synthetic_recovery_write_failure")||!has_filter("pre_update_option_vf_theme_brand","vf_synthetic_recovery_write_failure"))throw new Exception("failure fixture was not loaded");');
 await primary.click();r=await action(()=>root.locator('[data-vf-recovery-confirm-apply]').click());assert.equal(r.data.data.failureCode,'READBACK_MISMATCH');assert.deepEqual(state(),failedState);assert.equal(await root.locator('[data-vf-recovery-preflight-token]').inputValue(),'');assert.equal(await root.locator('[data-vf-recovery-json]').inputValue(),source+' ');assert(await root.locator('[data-vf-recovery-error-summary]').isVisible());
 cli('unlink(WPMU_PLUGIN_DIR."/synthetic-recovery-write-failure.php");');r=await perform();assert(r.data.success);
 // One actual slow request disables every conflicting task/input/action.
 let release;const held=new Promise(resolve=>release=resolve);await page.route('**/admin-ajax.php',async route=>{await held;await route.continue();});await primary.click();const pending=action(()=>root.locator('[data-vf-recovery-confirm-apply]').click());await page.waitForFunction(()=>document.querySelector('[data-vf-recovery-page]').getAttribute('aria-busy')==='true');assert.equal(await root.locator('[data-vf-recovery-workflow-step]:not(:disabled)').count(),0);assert(await root.locator('[data-vf-recovery-refresh-status]').isDisabled());assert(await root.locator('[data-vf-recovery-json]').isDisabled());await page.screenshot({path:'proof/recovery-import-busy-1440.png',fullPage:true});release();r=await pending;assert(r.data.success);await page.unroute('**/admin-ajax.php');assert.equal(state().stores.brand.siteName,'Synthetic UI imported name');assert.equal(state().settings.retention,14);assert.equal(state().points,2);assert.equal(await root.locator('[data-vf-recovery-record-capacity]').textContent(),'14');assert.equal(await root.locator('[data-vf-recovery-capacity-summary]').textContent(),'2/14');
 await tab('restore');await root.locator('[data-vf-recovery-picker-open]').click();const radios=picker.locator('[data-vf-recovery-revision-choice]');await radios.filter({hasNotText:'never'}).first().check();await picker.getByRole('button',{name:'取消',exact:true}).click();assert.equal(await root.locator('[data-vf-recovery-revision-id]').inputValue(),firstId);
 await root.locator('[data-vf-recovery-confirm]').fill('RESTORE');await primary.click();r=await action(()=>root.locator('[data-vf-recovery-confirm-apply]').click());assert(r.data.success);assert.equal(state().revision,before.revision);assert(await root.locator('[data-vf-recovery-restore-next]').isVisible());await page.screenshot({path:'proof/recovery-restored-1440.png',fullPage:true});
 await page.reload();await tab('status');r=await action(()=>root.locator('[data-vf-recovery-refresh-status]').click());assert(r.data.success);assert((await root.locator('[data-vf-recovery-health-title]').innerText()).startsWith('7 类'));assert.equal(await root.locator('[data-vf-recovery-consumer-total]').innerText(),'6');
 // Defaults must not persist a draft from a different task.
 await tab('import');await root.locator('[name="recovery[retention]"]').fill('31');await tab('restore');await root.locator('.vf-recovery-danger-zone > summary').click();await root.locator('[data-vf-recovery-default-open]').click();await root.locator('[data-vf-recovery-default-confirm]').fill('RESET_DEFAULTS');const defaultBefore=state(),defaultStores=JSON.parse(cli(load+'echo wp_json_encode(vf_theme_export_config("", "defaults")["payload"]["stores"]);'));r=await action(()=>root.locator('[data-vf-recovery-default-apply]').click());assert(r.data.success);assert.equal(state().settings.retention,14);assert.deepEqual(state().stores,defaultStores);assert.equal(state().points,defaultBefore.points+1);
 await tab('import');await root.locator('[data-vf-recovery-source-mode][value=paste]').check();const draft=JSON.stringify(changed('Synthetic network draft'));await root.locator('[data-vf-recovery-json]').fill(draft);await page.waitForTimeout(230);const networkState=state();await page.route('**/admin-ajax.php',route=>route.abort('failed'));await primary.click();await root.locator('[data-vf-recovery-error-summary]').waitFor();await page.waitForFunction(()=>document.querySelector('[data-vf-recovery-page]').getAttribute('aria-busy')==='false');assert.equal(await root.locator('[data-vf-recovery-json]').inputValue(),draft);assert.equal(state().revision,networkState.revision);assert.equal(await primary.isDisabled(),false);await page.screenshot({path:'proof/recovery-network-error-1440.png',fullPage:true});await page.unroute('**/admin-ajax.php');
 r=await perform();assert(r.data.success);cli(load+'$b=get_option("vf_theme_brand",[]);$b["siteName"]="Synthetic concurrent change";update_option("vf_theme_brand",$b,false);');await primary.click();r=await action(()=>root.locator('[data-vf-recovery-confirm-apply]').click());assert.equal(r.response.status(),409);assert.equal(await root.locator('[data-vf-recovery-preflight-token]').inputValue(),'');assert.equal(await root.locator('[data-vf-recovery-json]').inputValue(),draft);
 // Server endpoints retain permission, nonce, confirmation, size and corruption protection.
 const cfg=await config();const post=async(action,extra={})=>context.request.post(cfg.ajaxUrl,{form:{action,nonce:cfg.nonce,revision:state().revision,...extra}});
 for(const a of ['vf_theme_recovery_snapshot_ajax','vf_theme_recovery_export_ajax','vf_theme_recovery_preflight_ajax','vf_theme_recovery_apply_ajax','vf_theme_recovery_restore_ajax','vf_theme_recovery_defaults_ajax','vf_theme_recovery_status_ajax']){const bad=await post(a,{nonce:'invalid'});assert.equal(bad.status(),403);}
 const anon=await browser.newContext();const denied=await anon.request.post(cfg.ajaxUrl,{form:{action:'vf_theme_recovery_export_ajax'}});assert(denied.status()>=400||await denied.text()==='0');await anon.close();
 const subscriber=JSON.parse(cli('$id=wp_create_user("synthetic-subscriber","Synthetic-only-subscriber-81!","subscriber@example.invalid");if(is_wp_error($id))$id=username_exists("synthetic-subscriber");wp_set_current_user($id);echo wp_json_encode(["id"=>$id,"nonce"=>wp_create_nonce("theme.recovery.manage")]);'));
 const limited=await browser.newContext(),lp=await limited.newPage();await lp.goto(base+'/wp-login.php');await lp.locator('#user_login').fill('synthetic-subscriber');await lp.locator('#user_pass').fill('Synthetic-only-subscriber-81!');await Promise.all([lp.waitForURL(/wp-admin/),lp.locator('#wp-submit').click()]);const unprivileged=await limited.request.post(cfg.ajaxUrl,{form:{action:'vf_theme_recovery_snapshot_ajax',nonce:subscriber.nonce}});assert.equal(unprivileged.status(),403);await limited.close();
 let deniedWrite=await post('vf_theme_recovery_restore_ajax',{revision_id:firstId,confirmation:'WRONG'});assert.equal(deniedWrite.status(),422);deniedWrite=await post('vf_theme_recovery_defaults_ajax',{confirmation:'WRONG'});assert.equal(deniedWrite.status(),422);
 const corrupted=changed('Must not import');corrupted.integrity.storesSha256='0'.repeat(64);deniedWrite=await post('vf_theme_recovery_preflight_ajax',{'config_json':JSON.stringify(corrupted),'recovery[retention]':'14','recovery[importMode]':'strict'});assert.equal(deniedWrite.status(),422);
 const oversized=await context.request.post(cfg.ajaxUrl,{multipart:{action:'vf_theme_recovery_preflight_ajax',nonce:cfg.nonce,revision:state().revision,'recovery[retention]':'14','recovery[importMode]':'strict',config_file:{name:'oversize.json',mimeType:'application/json',buffer:Buffer.alloc(Number(await root.getAttribute('data-vf-recovery-file-max-bytes'))+1,32)}}});assert.equal(oversized.status(),422);
 const oversizePaste=await post('vf_theme_recovery_preflight_ajax',{config_json:'a'.repeat(Number(await root.getAttribute('data-vf-recovery-json-max-bytes'))+1)});assert.equal(oversizePaste.status(),422);assert((await oversizePaste.json()).data.message.includes('超过'));
 const executable=await context.request.post(cfg.ajaxUrl,{multipart:{action:'vf_theme_recovery_preflight_ajax',nonce:cfg.nonce,revision:state().revision,config_file:{name:'bad.php',mimeType:'application/json',buffer:Buffer.from('{}')}}});assert.equal(executable.status(),422);
 // Emptying the store after a page was mounted must clear stale picker/form state.
 cli(load+'delete_option(vf_theme_revision_store_key());');await tab('status');r=await action(()=>root.locator('[data-vf-recovery-refresh-status]').click());assert(r.data.success);await tab('restore');assert(await root.locator('[data-vf-recovery-empty]').isVisible());assert.equal(await root.locator('[data-vf-recovery-form=restore]').isVisible(),false);assert.equal(await root.locator('[data-vf-recovery-revision-id]').inputValue(),'');
 cli(load+'update_option(vf_theme_recovery_option_key(),["retention"=>50,"importMode"=>"strict"],false);for($i=0;$i<35;$i++)vf_theme_revision_store_create("manual");');await page.reload();await tab('status');r=await action(()=>root.locator('[data-vf-recovery-refresh-status]').click());assert(r.data.success);
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:900});await tab('restore');await root.locator('[data-vf-recovery-picker-open]').click();assert.equal(await picker.locator('[data-vf-recovery-revision-choice]').count(),35);assert.equal(await root.locator('[data-vf-recovery-toast]').isVisible(),false);const geometry=await picker.locator('.vf-recovery-dialog__panel').evaluate(n=>({top:n.getBoundingClientRect().top,bottom:n.getBoundingClientRect().bottom,height:innerHeight,scroll:n.querySelector('.vf-recovery-revisions').scrollHeight>n.querySelector('.vf-recovery-revisions').clientHeight}));assert(geometry.top>=10&&geometry.bottom<=geometry.height-9&&geometry.scroll,JSON.stringify(geometry));await picker.locator('[data-vf-recovery-picker-search]').fill('no-such-synthetic-point');assert(await picker.locator('[data-vf-recovery-picker-empty]').isVisible());await picker.locator('[data-vf-recovery-picker-search]').fill('');await picker.locator('[data-vf-recovery-revision-choice]').last().check();await page.screenshot({path:'proof/recovery-picker-'+width+'.png',fullPage:true});await page.keyboard.press('Escape');assert(await root.locator('[data-vf-recovery-picker-open]').evaluate(n=>n===document.activeElement));}
 // Corrupt existing records are true blocking cases, including direct endpoint calls.
 cli(load+'$p=vf_theme_revision_store();$p[0]["checksum"]=str_repeat("0",64);update_option(vf_theme_revision_store_key(),$p,false);');await page.reload();await tab('status');assert(await primary.isDisabled());await root.locator('.vf-recovery-professional > summary').click();assert((await root.locator('[data-vf-recovery-diagnostic-issues]').innerText()).includes('完整性'));await page.screenshot({path:'proof/recovery-true-blocked-390.png',fullPage:true});r=await post('vf_theme_recovery_snapshot_ajax');assert.equal((await r.json()).data.failureCode,'CONFIGURATION_BLOCKED');r=await post('vf_theme_recovery_export_ajax');assert.equal((await r.json()).data.failureCode,'CONFIGURATION_BLOCKED');
 cli(load+'delete_option(vf_theme_revision_store_key());');
 assert.equal(errors.length,0,JSON.stringify(errors));
 fs.writeFileSync('proof/live-browser.json',JSON.stringify({status:'PASS',checks,disclosure_labels:'PASS',native_disclosure_labels:'PASS',first_point_no_reload:'PASS',real_download:'PASS',native_no_js_export:'PASS',real_preflight:'PASS',real_import:'PASS',real_restore:'PASS',real_defaults:'PASS',source_isolation:'PASS',picker_cancel:'PASS',expired_retry:'PASS',failed_write_retry:'PASS',draft_invalidation:'PASS',summary_refresh:'PASS',busy_lock:'PASS',network_failure:'PASS',revision_conflict:'PASS',nonce:'PASS',guest:'PASS',permission:'PASS',confirmation:'PASS',corruption:'PASS',upload_abuse:'PASS',empty_refresh:'PASS',long_picker:'PASS',true_blocked:'PASS',owner_real_use:'PENDING',errors},null,2));
 await browser.close();console.log('RECOVERY_REAL_WORDPRESS_BROWSER=PASS');
})().catch(async e=>{if(failurePage){await failurePage.screenshot({path:'proof/recovery-functional-failed.png',fullPage:true});const state=await failurePage.evaluate(()=>{const r=document.querySelector('[data-vf-recovery-page]'),f=r?.querySelector('[data-vf-recovery-file]');return {task:r?.dataset.vfRecoveryTask,busy:r?.getAttribute('aria-busy'),mode:r?.querySelector('[data-vf-recovery-source-mode]:checked')?.value,file:f?.files?.[0]?{size:f.files[0].size,type:f.files[0].type}:null,fileDisabled:f?.disabled,primaryDisabled:r?.querySelector('[data-vf-recovery-primary]')?.disabled,localTitle:r?.querySelector('[data-vf-recovery-local-title]')?.textContent,localMessage:r?.querySelector('[data-vf-recovery-local-message]')?.textContent};});fs.writeFileSync('proof/failure-state.json',JSON.stringify({state,errors:failureErrors},null,2));console.error(JSON.stringify({state,errors:failureErrors}));}console.error(e);process.exit(1);});

