const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
const origin='http://127.0.0.1:18880',url=origin+'/wp-admin/themes.php?page=vf-theme-modules&tab=layout';
const rootSel='[data-vf-layout-page]', titleSel='[name="layout[activeModuleSettings][tool_grid][title]"]',saveSel='[data-vf-layout-save]';
const contexts=['home','basic_page','about_page','contact_page','tool_hub','tool','blog_index','article_detail','guide_index','guide_detail','problem_index','problem_detail','faq_page','glossary_index','glossary_detail','archive_list','search','html_sitemap','not_found','legal'];
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1319,height:1000}}),page=await context.newPage(),errors=[];
 global.proofPage=page;page.on('pageerror',e=>errors.push(e.message));
 const login=async p=>{await p.goto(origin+'/wp-login.php');await p.locator('#user_login').fill('admin');await p.locator('#user_pass').fill('Synthetic-Only-Update-54!');await Promise.all([p.waitForURL(/wp-admin/),p.locator('#wp-submit').click()]);};
 const go=async(key='home')=>{await page.goto(url+'&context='+key);await page.locator(rootSel).waitFor();};
 const settled=()=>page.waitForFunction(()=>document.querySelector('[data-vf-layout-page]').getAttribute('aria-busy')!=='true');
 const send=async(p=page)=>{const response=p.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().postData()?.includes('vf_theme_layout_save'));await p.locator(saveSel).click();const data=await(await response).json();await p.waitForFunction(()=>document.querySelector('[data-vf-layout-page]').getAttribute('aria-busy')!=='true');return data;};
 const saved=async()=>{const v=await send();assert(v.success&&v.data.ok&&v.data.readback&&v.data.runtimeVerification.ok&&v.data.roundtripEvidence.ok,JSON.stringify(v));assert(!await page.locator(rootSel).evaluate(n=>n.classList.contains('is-dirty')),'client rejected full canonical readback');return v;};
 const openSections=async()=>page.locator(rootSel+' details:not([hidden])').evaluateAll(ns=>ns.forEach(n=>n.open=true));
 const clean=async()=>page.reload();
 await login(page);await go();
 if(process.env.PHASE==='baseline'){
  const result={version:process.env.SOURCE_VERSION};
  const offset=await page.evaluate(()=>document.querySelector('[data-vf-page-tab="layout"] h1').getBoundingClientRect().left-document.querySelector('.vf-admin-one-row-shell').getBoundingClientRect().left);assert(offset>24);result.title_extra_indent='REPRODUCED';
  await page.locator(titleSel).fill('旧版残缺响应');await page.route('**/admin-ajax.php',r=>r.fulfill({json:{success:true,data:{}}}));await page.locator(saveSel).click();await page.waitForFunction(()=>!document.querySelector('[data-vf-layout-page]').classList.contains('is-dirty'));result.incomplete_response_false_success='REPRODUCED';await page.unroute('**/admin-ajax.php');await clean();
  await page.locator(titleSel).fill('旧版已发送候选');await page.route('**/admin-ajax.php',async r=>{const response=await r.fetch();await new Promise(resolve=>setTimeout(resolve,500));await r.fulfill({response});});const request=page.waitForRequest(r=>r.url().includes('admin-ajax.php'));await page.locator(saveSel).click();await request;assert(await page.locator(titleSel).isEnabled());await page.locator(titleSel).fill('旧版请求中继续编辑');await page.waitForFunction(()=>!document.querySelector('[data-vf-layout-page]').classList.contains('is-dirty'));assert.equal(await page.locator(titleSel).inputValue(),'旧版已发送候选');result.busy_edit_lost='REPRODUCED';await page.unroute('**/admin-ajax.php');fs.writeFileSync('proof/baseline.json',JSON.stringify(result,null,2));await browser.close();return;
 }
 const functional={},checks=[],contextChecks=[];
 for(const width of [1920,1440,1319,1024,768,390]){
  await page.setViewportSize({width,height:1000});await go();await page.evaluate(()=>document.fonts.ready);
  const geometry=await page.evaluate(()=>{
   const root=document.querySelector('[data-vf-layout-page]'),head=document.querySelector('[data-vf-page-tab="layout"]'),shell=document.querySelector('.vf-admin-one-row-shell'),field=root.querySelector('input[type="number"]'),label=field.closest('label'),r=root.getBoundingClientRect(),h=head.getBoundingClientRect(),s=shell.getBoundingClientRect();
   return {overflow:document.documentElement.scrollWidth>innerWidth+1,edges:[r.left-s.left,r.right-s.right,h.left-s.left,h.right-s.right],title:head.querySelector('h1').getBoundingClientRect().left-h.left,font:parseFloat(getComputedStyle(field).fontSize),padding:getComputedStyle(root).paddingLeft,left:label.getBoundingClientRect().left-r.left,right:r.right-label.getBoundingClientRect().right};
  });assert(!geometry.overflow&&geometry.edges.every(n=>Math.abs(n)<=1)&&Math.abs(geometry.title)<=1&&geometry.font>=14,JSON.stringify({width,geometry}));
  assert.equal(geometry.padding,width<=520?'16px':width<=782?'20px':'24px');assert(!await page.locator(saveSel).isVisible());
  assert(await page.evaluate(()=>{const nodes=[...document.querySelectorAll('.vf-admin-one-row-inner,.vf-admin-topbar-brand,.vf-admin-topbar-pill,.vf-theme-domain-mobile')],read=()=>nodes.map(n=>{const r=n.getBoundingClientRect(),s=getComputedStyle(n);return[r.width,r.height,s.fontSize,s.padding,s.backgroundColor];});const first=read(),sheet=[...document.styleSheets].find(s=>s.href?.includes('admin-page-layout-v8.css'));if(!sheet)return false;sheet.disabled=true;const second=read();sheet.disabled=false;return JSON.stringify(first)===JSON.stringify(second);}),'frozen header styling changed');
  await page.screenshot({path:'proof/layout-'+width+'.png',fullPage:true});
  const box=page.locator('.vf-layout-function-master__editor input[type="checkbox"]').first();if(await box.count()){const before=await box.isChecked();await box.locator('..').click();assert.equal(await box.isChecked(),!before);await box.focus();await page.keyboard.press('Space');assert.equal(await box.isChecked(),before);const dim=await box.evaluate(n=>{const r=n.getBoundingClientRect();return[r.width,r.height];});assert.deepEqual(dim,[18,18]);}
  await openSections();assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1));await page.screenshot({path:'proof/layout-expanded-'+width+'.png',fullPage:true});
  await page.locator('[data-vf-layout-context-catalog-open]').click();const dialog=page.locator('[data-vf-layout-context-dialog]');await dialog.waitFor();assert.equal(await dialog.getAttribute('role'),'dialog');await page.keyboard.press('Escape');assert(!await dialog.isVisible());assert(await page.locator('[data-vf-layout-context-catalog-open]').evaluate(n=>n===document.activeElement));
  checks.push({width,geometry,control_interactions:'PASS',frozen_header_parity:'PASS'});
 }
 await page.setViewportSize({width:1319,height:1000});
 // Exercise every exposed field through the actual function tabs and disclosures.
 for(const key of contexts){
  await go(key);await openSections();const visited=new Set(),expected=new Map();
  const editVisible=async()=>{
   const inputs=await page.locator('[data-vf-layout-form] input:not([type="hidden"])[name],[data-vf-layout-form] select[name],[data-vf-layout-form] textarea[name]').all();
   for(const field of inputs){if(!await field.isVisible()||!await field.isEnabled())continue;const name=await field.getAttribute('name');if(visited.has(name))continue;visited.add(name);const meta=await field.evaluate(n=>({tag:n.tagName,type:n.type,value:n.value,min:n.min,max:n.max,options:n.options?[...n.options].filter(o=>!o.disabled).map(o=>o.value):[]}));
    if(meta.type==='checkbox'){await field.click();expected.set(name,{type:'checkbox',value:await field.isChecked()});}
    else if(meta.tag==='SELECT'){const next=meta.options.find(v=>v!==meta.value);if(next!==undefined)await field.selectOption(next);expected.set(name,{type:'value',value:await field.inputValue()});}
    else if(meta.type==='number'){const min=meta.min===''?0:Number(meta.min),max=meta.max===''?999:Number(meta.max),old=Number(meta.value)||min;await field.fill(String(old<max?old+1:Math.max(min,old-1)));expected.set(name,{type:'value',value:await field.inputValue()});}
    else if(!['radio','submit','button'].includes(meta.type)){await field.fill((meta.value||'测试')+' QA');expected.set(name,{type:'value',value:await field.inputValue()});}
   }
  };
  const tabs=await page.locator('.vf-layout-function-master__item[role="tab"]').all();for(const tab of tabs){if(await tab.isVisible()){await tab.click();await editVisible();}}await editVisible();assert(visited.size>0,key+' has no editable controls');
  const invalid=await page.locator('[data-vf-layout-form]').evaluate(n=>[...n.querySelectorAll(':invalid')].map(el=>({name:el.name,value:el.value})));assert.deepEqual(invalid,[],key+' generated invalid dataset');const result=await saved();assert.equal(result.data.contextVerification.context,key);assert.equal(result.data.roundtripEvidence.contextCount,20);await page.reload();
  for(const [name,entry]of expected){const values=await page.locator('[data-vf-layout-form] input,[data-vf-layout-form] select,[data-vf-layout-form] textarea').evaluateAll((ns,arg)=>ns.filter(n=>n.name===arg.name&&n.type!=='hidden').map(n=>arg.type==='checkbox'?n.checked:n.value),{name,type:entry.type});assert(values.length&&values.every(v=>String(v)===String(entry.value)),JSON.stringify({key,name,expected:entry.value,values}));}
  assert(!await page.locator(saveSel).isVisible());contextChecks.push({context:key,status:'PASS',editable_controls:visited.size,verified_fields:result.data.roundtripEvidence.totalFieldCount,consumers:20});
  if(['tool','article_detail','search','not_found','basic_page'].includes(key)){await openSections();await page.screenshot({path:'proof/context-'+key+'.png',fullPage:true});}
 }
 functional.all_20_context_fields_save_reload='PASS';functional.hidden_inactive_fields_preserved='PASS';functional.all_20_frontend_consumers='PASS';
 await go();await openSections();const optionalRow=page.locator('[data-vf-layout-list] li[data-required="0"]').first();const moduleKey=await optionalRow.getAttribute('data-module');assert(moduleKey);
 const inactiveBefore=await page.locator('[data-vf-layout-module-settings-json]').evaluate((n,key)=>JSON.parse(n.value).home[key],moduleKey);
 await optionalRow.locator('[data-vf-layout-remove]').click();assert.equal(await page.locator('[data-vf-layout-list] li[data-module="'+moduleKey+'"]').count(),0);const stopped=await saved();assert.deepEqual(stopped.data.layout.moduleSettings.home[moduleKey],inactiveBefore);await page.reload();await openSections();assert.equal(await page.locator('[data-vf-layout-list] li[data-module="'+moduleKey+'"]').count(),0);
 await page.locator('[data-vf-layout-enable-module="'+moduleKey+'"]').click();assert.equal(await page.locator('[data-vf-layout-list] li[data-module="'+moduleKey+'"]').count(),1);const resumed=await saved();assert.deepEqual(resumed.data.layout.moduleSettings.home[moduleKey],inactiveBefore);functional.module_disable_enable_preserves_fields='PASS';
 await openSections();const moved=page.locator('[data-vf-layout-list] li[data-module="'+moduleKey+'"]');const index=await moved.evaluate(n=>[...n.parentElement.children].indexOf(n));assert(index>1);await moved.locator('[data-vf-layout-move="up"]').click();assert.equal(await moved.evaluate(n=>[...n.parentElement.children].indexOf(n)),index-1);await moved.locator('[data-vf-layout-edit-module]').focus();await page.keyboard.press('Alt+ArrowDown');assert.equal(await moved.evaluate(n=>[...n.parentElement.children].indexOf(n)),index);
 const persistedOrder=await page.locator('[data-vf-layout-list] li').evaluateAll(ns=>ns.map(n=>n.dataset.module));const reordered=await saved();assert.deepEqual(reordered.data.layout.modules.home,persistedOrder);await page.reload();assert.deepEqual(await page.locator('[data-vf-layout-list] li').evaluateAll(ns=>ns.map(n=>n.dataset.module)),persistedOrder);assert.equal(await page.locator('[data-vf-layout-list] li[data-required="1"] .vf-layout-row-actions').count(),0);functional.module_mouse_keyboard_sort_save='PASS';
 await go();await page.locator(titleSel).fill('隔离保存候选');await page.route('**/admin-ajax.php',async r=>{const response=await r.fetch();await new Promise(resolve=>setTimeout(resolve,500));await r.fulfill({response});});const req=page.waitForRequest(r=>r.url().includes('admin-ajax.php'));await page.locator(saveSel).click();await req;assert(await page.locator(titleSel).isDisabled());assert(await page.locator('[data-vf-layout-context-catalog-open]').isDisabled());assert(await page.locator(saveSel).isDisabled());assert(await page.locator('[data-vf-layout-reset]').isDisabled());await settled();assert(!await page.locator(rootSel).evaluate(n=>n.classList.contains('is-dirty')));await page.unroute('**/admin-ajax.php');functional.busy_controls_navigation_structure_isolated='PASS';
 for(const scenario of ['network','invalid_json','incomplete','http','timeout']){
  await go();await page.locator(titleSel).fill('输入保留-'+scenario);const revision=await page.locator('[data-vf-layout-revision]').inputValue();if(scenario==='timeout')await page.evaluate(()=>{const original=window.setTimeout;window.setTimeout=(fn,delay,...args)=>original(fn,delay===20000?50:delay,...args);});await page.route('**/admin-ajax.php',async r=>{if(scenario==='network')return r.abort('failed');if(scenario==='invalid_json')return r.fulfill({body:'<html>invalid</html>'});if(scenario==='timeout'){await new Promise(resolve=>setTimeout(resolve,200));return r.abort('timedout').catch(()=>{});}return r.fulfill({status:scenario==='http'?503:200,json:{success:true,data:{}}});});await page.locator(saveSel).click();await page.locator('[data-vf-layout-error-summary]').waitFor();await settled();assert.equal(await page.locator(titleSel).inputValue(),'输入保留-'+scenario);assert.equal(await page.locator('[data-vf-layout-revision]').inputValue(),revision);assert(await page.locator(rootSel).evaluate(n=>n.classList.contains('is-dirty')));assert(await page.locator(titleSel).isEnabled());assert(!await page.locator('[data-vf-layout-toast]').isVisible());await page.screenshot({path:'proof/layout-error-'+scenario+'.png',fullPage:true});await page.unroute('**/admin-ajax.php');await saved();functional[scenario+'_input_retained_retry']='PASS';
 }
 await go();const revision=await page.locator('[data-vf-layout-revision]').inputValue(),other=await context.newPage();await other.goto(url);await other.locator(titleSel).fill('另一窗口正式配置');assert((await send(other)).success);await page.locator(titleSel).fill('冲突候选保留');for(let i=0;i<2;i++){const v=await send();assert(!v.success&&v.data.failureCode==='REVISION_CONFLICT');assert.equal(await page.locator('[data-vf-layout-revision]').inputValue(),revision);}await other.reload();assert.equal(await other.locator(titleSel).inputValue(),'另一窗口正式配置');await other.close();functional.repeated_conflict_no_overwrite='PASS';
 await go();const form=await page.evaluate(()=>({fields:Object.fromEntries(new FormData(document.querySelector('[data-vf-layout-form]'))),cfg:VFThemeLayout}));const denied=await context.request.post(form.cfg.ajaxUrl,{form:{...form.fields,action:'vf_theme_layout_save',nonce:'invalid-synthetic'}});assert.equal(denied.status(),403);assert.equal((await denied.json()).data.failureCode,'NONCE_INVALID');const guest=await browser.newContext();const out=await guest.request.post(form.cfg.ajaxUrl,{form:{...form.fields,action:'vf_theme_layout_save',nonce:form.cfg.nonce}});assert(out.status()>=400||(await out.text()).trim()==='0');await guest.close();functional.nonce_guest_rejected='PASS';
 // Native WordPress post uses the same protected canonical transaction.
 const nativeFields=await page.locator('[data-vf-layout-form]').evaluate(n=>new URLSearchParams([...new FormData(n)]).toString());const native=await context.request.post(origin+'/wp-admin/admin-post.php',{data:nativeFields,headers:{'content-type':'application/x-www-form-urlencoded'},maxRedirects:0});assert.equal(native.status(),302);assert(native.headers().location.includes('layout-saved'));functional.native_post_canonical_save='PASS';
 await go();await page.locator(titleSel).fill('离开保护候选');await page.locator('[data-vf-layout-context-catalog-open]').click();await page.locator('[data-vf-layout-context-search]').fill('工具目录');await page.locator('[data-vf-layout-context-card="tool_hub"]').click();await page.locator('[data-vf-layout-navigation-dialog]').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator(titleSel).inputValue(),'离开保护候选');await page.keyboard.press('Escape');await go();functional.context_switch_cancel_keeps_draft='PASS';
 await page.locator('[data-vf-layout-context-catalog-open]').click();for(const b of await page.locator('[data-vf-layout-context-group-filter]').all()){await b.click();assert(await page.locator('[data-vf-layout-context-card]:visible').count()>0);}await page.locator('[data-vf-layout-context-search]').fill('工具目录');assert(await page.locator('[data-vf-layout-context-card="tool_hub"]').isVisible());await page.locator('[data-vf-layout-context-search]').fill('no-match-synthetic');assert.equal(await page.locator('[data-vf-layout-context-card]:visible').count(),0);await page.setViewportSize({width:390,height:560});await page.locator('[data-vf-layout-context-search]').fill('首页');await page.screenshot({path:'proof/layout-picker-short-390.png',fullPage:true});await page.keyboard.press('Escape');functional.context_picker_groups_search_escape='PASS';
 await page.setViewportSize({width:1319,height:1000});await go();await openSections();const modules=page.locator('[data-vf-layout-list] li');const before=await modules.evaluateAll(ns=>ns.map(n=>n.dataset.module));const buttons=page.locator('[data-vf-layout-list] [data-vf-layout-edit-module]');for(const b of await buttons.all()){if(await b.isVisible()&&await b.isEnabled()){await b.click();break;}}await page.keyboard.press('Escape');assert.deepEqual(await modules.evaluateAll(ns=>ns.map(n=>n.dataset.module)),before);await page.locator('[data-vf-layout-reset]').click();assert(await page.locator(rootSel).evaluate(n=>n.classList.contains('is-dirty')));await saved();functional.recommended_order_save='PASS';
 await go('search');await openSections();assert(await page.locator('[data-vf-layout-reset]').isDisabled());assert.equal(await page.locator('[data-vf-layout-list] li[draggable="true"]').count(),0);functional.locked_system_structure='PASS';
 assert.deepEqual(errors,[]);const proof={status:'PASS',checks,contexts:contextChecks,functional,errors};fs.writeFileSync('proof/live-browser.json',JSON.stringify(proof,null,2));await browser.close();
})().catch(async error=>{fs.writeFileSync('proof/failure.json',JSON.stringify({status:'FAIL',message:String(error),version:process.env.TARGET_VERSION},null,2));if(global.proofPage)await global.proofPage.screenshot({path:'proof/layout-failure.png',fullPage:true}).catch(()=>{});console.error(error);process.exit(1);});
