'use strict';
const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright'),{url,login,base,cli,load,state}=require('./common');
(async()=>{
 const b=await chromium.launch(),c=await b.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await login(p);
 for(const method of ['get','post']){const r=await c.request[method](base+'/wp-admin/install.php?step=2');assert(/Already Installed|已安装/.test(await r.text()));}
 const actual=[];
 async function checkInitial(label){await p.goto(url);await p.waitForFunction(()=>document.querySelector('[data-vf-seo-form-shell]')?.dataset.vfSeoEnhanced==='1');const s=state();assert.equal(await p.locator('[data-vf-seo-field=searchIndexability]').inputValue(),'noindex_follow');assert(await p.locator('[data-vf-seo-route-row]').count()>0);assert.equal(await p.locator('[data-vf-unsaved-indicator]').innerText(),s.stored?'已保存':'默认配置');assert.equal(await p.locator('[data-vf-seo-save]').isVisible(),!s.stored);assert.equal(await p.locator('[data-vf-seo-verify]').isVisible(),!!s.stored);actual.push({label,stored:s.stored,badge:await p.locator('[data-vf-unsaved-indicator]').innerText()});}
 await checkInitial('native clean installation after existing Theme initialization');
 // Native initializer stores defaults before this admin page; test the actual default transaction separately, then verify native reinitialization.
 cli(load+'delete_option(vf_theme_seo_option_key());');assert.equal(state().stored,false);
 const initialSave=JSON.parse(cli('vf_theme_bootstrap_require_many(["services/install-migration-service.php"]);vf_theme_install_migration_load_runtime();wp_set_current_user(1);'+load+'$s=vf_theme_seo_readback();echo wp_json_encode(theme_seo_save($s["seo"],$s["revision"],1));'));assert(initialSave.ok&&initialSave.readback&&initialSave.runtimeVerification.ok);assert.equal(initialSave.stages.execute,'passed');fs.writeFileSync('proof/default-save-readback.json',JSON.stringify(initialSave,null,2));await checkInitial('explicit default transaction saved and revisited');
 cli(load+'delete_option(vf_theme_seo_option_key());');await checkInitial('native missing-Option initialization before admin render');assert.equal(state().stored,true);await p.screenshot({path:'proof/seo-fresh-native-initial-1440.png',fullPage:true});
 const response=p.waitForResponse(r=>r.url().includes('admin-ajax.php')&&r.request().method()==='POST'&&/(?:name="action"\r?\n\r?\nvf_theme_seo_save|(?:^|&)action=vf_theme_seo_save(?:&|$))/.test(r.request().postData()||''));await p.locator('[data-vf-seo-verify]').click();const saved=await(await response).json();assert(saved.success&&saved.data.ok);await p.waitForFunction(()=>document.querySelector('[data-vf-seo-form-shell]').getAttribute('aria-busy')!=='true');assert.equal(await p.locator('[data-vf-seo-form-shell]').getAttribute('data-vf-seo-unknown'),'0');assert.equal(await p.locator('[data-vf-seo-save]').isVisible(),false);await p.reload();assert.equal(await p.locator('[name=revision]').inputValue(),saved.data.revision);assert.equal(await p.locator('[data-vf-unsaved-indicator]').innerText(),'已保存');assert.equal(errors.length,0);
 fs.writeFileSync('proof/clean-install.json',JSON.stringify({status:'PASS',environment:'fresh synthetic WordPress database and native clean Theme package installation',version:process.env.TARGET_VERSION,first_login:'PASS',default_initialization:'PASS',actual_initial_states:actual,explicit_default_service_save:'PASS',native_missing_option_reinitialization:'PASS',default_ui_scope:'native initializer stores valid defaults before admin render; initial badge verified against actual stored readback',canonical_save_and_revisit:'PASS',host_setup_revisit_get_post_locked:'PASS',errors},null,2));await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
