'use strict';
const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch(),context=await browser.newContext({acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
 const base='http://127.0.0.1:18880';await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill('admin');await page.locator('#user_pass').fill('Synthetic-Only-Update-54!');await Promise.all([page.waitForURL(/wp-admin/),page.locator('#wp-submit').click()]);
 for(const method of ['get','post']){const response=await context.request[method](base+'/wp-admin/install.php?step=2');assert(/Already Installed|已安装/.test(await response.text()));}
 await page.goto(base+'/wp-admin/themes.php?page=vf-theme-modules&tab=preview');const root=page.locator('[data-vf-preview-page]');assert(await root.locator('[data-vf-preview-run]').isEnabled());assert.equal(await root.locator('[data-vf-preview-mode] option').count(),6);
 const history=JSON.parse(await root.locator('[data-vf-preview-history-json]').textContent());assert.equal(history.length,0);await root.locator('[data-vf-preview-mode]').selectOption('quick');await root.locator('[data-vf-preview-run]').click();await page.waitForFunction(()=>document.querySelector('[data-vf-preview-page]').getAttribute('aria-busy')==='false',{}, {timeout:180000});
 const [download]=await Promise.all([page.waitForEvent('download'),root.locator('[data-vf-preview-download]').click()]);const artifact=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(artifact.version,process.env.TARGET_VERSION);assert.equal(artifact.persistence.ok,true);assert.equal(artifact.mode,'quick');await page.reload();assert.equal(JSON.parse(await root.locator('[data-vf-preview-history-json]').textContent())[0].runId,artifact.runId);assert.equal(errors.length,0);
 await page.screenshot({path:'proof/preview-clean-install-1440.png',fullPage:true});fs.writeFileSync('proof/clean-install.json',JSON.stringify({status:'PASS',environment:'fresh synthetic WordPress database; native exact candidate ZIP install and activation',version:artifact.version,first_login:'PASS',reinstall_guard_get_post:'PASS',six_modes:'PASS',empty_history:'PASS',actual_job:'PASS',persisted_artifact:'PASS',actual_engine_verdict:artifact.status,engine_issues:artifact.issues.map(issue=>({level:issue.level,problem:issue.problem,current:issue.current})),production:'NOT_EXECUTED',errors},null,2));await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
