#!/usr/bin/env python3
from __future__ import annotations
import base64, hashlib, importlib.util, json, sys
from pathlib import Path

BASE=Path(__file__).with_name('p01-build-release.py')
spec=importlib.util.spec_from_file_location('p01_base',BASE)
if spec is None or spec.loader is None: raise SystemExit('cannot load p01 base builder')
m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)

def b64json(x): return base64.b64encode(json.dumps(x,ensure_ascii=False,separators=(',',':'),sort_keys=True).encode()).decode()
def sha(b): return hashlib.sha256(b).hexdigest()

def build_repair(source:dict[str,bytes],target:dict[str,bytes],bridge_update_hash:str)->str:
    src_manifest={k:sha(v) for k,v in source.items()}
    target_manifest={k:sha(v) for k,v in target.items() if k!='release-manifest.json'}
    payload={k:base64.b64encode(v).decode() for k,v in target.items()}
    removed=sorted(set(source)-set(target))
    old_update=src_manifest.get('app/UpdateManager.php','')
    alternates={'app/UpdateManager.php':sorted({x for x in [old_update,bridge_update_hash] if x})}
    template=r'''<?php
declare(strict_types=1);
final class VfAtomicPackage
{
    public const SOURCE_VERSION='2.21.14';
    public const TARGET_VERSION='2.21.15';
    public const TARGET_SCHEMA='2026080902';
    private const SOURCE_MANIFEST='@@SOURCE_MANIFEST@@';
    private const TARGET_MANIFEST='@@TARGET_MANIFEST@@';
    private const PAYLOAD='@@PAYLOAD@@';
    private const REMOVED='@@REMOVED@@';
    private const SOURCE_ALTERNATES='@@ALTERNATES@@';

    private static function decode(string $b64): array {$raw=base64_decode($b64,true);if($raw===false)throw new RuntimeException('Atomic metadata decode failed.');$x=json_decode($raw,true);if(!is_array($x))throw new RuntimeException('Atomic metadata JSON invalid.');return $x;}
    private static function rel(string $rel): string {if($rel===''||$rel[0]==='/'||strpos($rel,'\\')!==false||preg_match('#(^|/)\.\.(/|$)#',$rel))throw new RuntimeException('Unsafe Atomic path.');return $rel;}
    private static function writeExact(string $path,string $bytes,int $mode=0640): void {$dir=dirname($path);if(!is_dir($dir)&&!@mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Cannot create Atomic directory.');$tmp=$path.'.atomic-tmp-'.bin2hex(random_bytes(4));$h=@fopen($tmp,'xb');if(!$h)throw new RuntimeException('Cannot create Atomic temp file.');try{$off=0;$len=strlen($bytes);while($off<$len){$n=@fwrite($h,substr($bytes,$off));if($n===false||$n===0)throw new RuntimeException('Short Atomic write.');$off+=$n;}if(!@fflush($h))throw new RuntimeException('Atomic flush failed.');if(function_exists('fsync'))@fsync($h);}finally{@fclose($h);}@chmod($tmp,$mode);if(!@rename($tmp,$path)){@unlink($tmp);throw new RuntimeException('Atomic rename failed.');}}
    private static function jsonWrite(string $path,array $data):void{$j=json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);if($j===false)throw new RuntimeException('Atomic journal serialization failed.');self::writeExact($path,$j."\n",0600);}
    private static function verifyManifest(string $root,array $manifest,bool $source=false): array {$alts=$source?self::decode(self::SOURCE_ALTERNATES):[];$errors=[];foreach($manifest as $rel=>$expected){$rel=self::rel((string)$rel);$p=rtrim($root,'/').'/'.$rel;if(!is_file($p)||is_link($p)){$errors[]=$rel.':missing';continue;}$got=hash_file('sha256',$p)?:'';$allowed=[$expected];if($source&&isset($alts[$rel])&&is_array($alts[$rel]))$allowed=array_values(array_unique(array_merge($allowed,$alts[$rel])));if(!in_array($got,$allowed,true))$errors[]=$rel.':sha';}return ['ok'=>$errors===[],'errors'=>$errors,'checked'=>count($manifest)];}
    private static function runtime(string $root): array {$f=rtrim($root,'/').'/app/.runtime.php';if(!is_file($f)||is_link($f))throw new RuntimeException('Installed runtime pointer is missing.');$x=include $f;if(!is_array($x)||empty($x['data_dir'])||empty($x['db_file'])||empty($x['config_file']))throw new RuntimeException('Installed runtime pointer invalid.');return $x;}
    private static function dbVerify(string $db): array {if(!extension_loaded('pdo_sqlite'))throw new RuntimeException('PDO_SQLITE is required.');$p=new PDO('sqlite:'.$db,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$p->exec('PRAGMA foreign_keys=ON');$p->exec('PRAGMA busy_timeout=5000');$integrity=strtolower((string)$p->query('PRAGMA integrity_check')->fetchColumn());$fk=$p->query('PRAGMA foreign_key_check')->fetchAll();$head=(string)$p->query("SELECT COALESCE(MAX(version),'') FROM schema_migrations WHERE status='success'")->fetchColumn();if($integrity!=='ok'||$fk||$head!==self::TARGET_SCHEMA)throw new RuntimeException('Database verification failed.');return ['integrity'=>$integrity,'foreign_key_errors'=>count($fk),'schema'=>$head];}
    private static function snapshotDb(string $db,string $dest): void {$p=new PDO('sqlite:'.$db,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$p->exec('PRAGMA wal_checkpoint(FULL)');$q=str_replace("'","''",$dest);$p->exec("VACUUM INTO '$q'");@chmod($dest,0600);}
    private static function restoreDb(string $snapshot,string $db): void {if(!is_file($snapshot))throw new RuntimeException('Rollback database snapshot missing.');@unlink($db.'-wal');@unlink($db.'-shm');self::writeExact($db,(string)file_get_contents($snapshot),0640);}
    private static function backupFiles(string $root,string $stage,array $paths): array {$meta=[];foreach($paths as $rel){$rel=self::rel((string)$rel);$src=rtrim($root,'/').'/'.$rel;$exists=is_file($src)&&!is_link($src);$meta[$rel]=$exists;if($exists)self::writeExact($stage.'/source/'.$rel,(string)file_get_contents($src),0600);}return $meta;}
    private static function restoreFiles(string $root,string $stage,array $meta): void {foreach($meta as $rel=>$existed){$rel=self::rel((string)$rel);$dst=rtrim($root,'/').'/'.$rel;$src=$stage.'/source/'.$rel;if($existed){if(!is_file($src))throw new RuntimeException('Rollback source snapshot missing.');self::writeExact($dst,(string)file_get_contents($src),0640);}else{@unlink($dst);}}}
    private static function removeTree(string $p): void {if(!file_exists($p))return;if(is_file($p)||is_link($p)){@unlink($p);return;}foreach(scandir($p)?:[] as $n){if($n==='.'||$n==='..')continue;self::removeTree($p.'/'.$n);}@rmdir($p);}
    private static function journalPath(array $rt):string{return rtrim((string)$rt['data_dir'],'/').'/updates/p01-atomic-transaction.json';}
    private static function recoverInterrupted(string $root,array $rt): bool {
        $journal=self::journalPath($rt);if(!is_file($journal))return false;if(is_link($journal))throw new RuntimeException('Atomic transaction journal cannot be a symlink.');$j=json_decode((string)file_get_contents($journal),true);if(!is_array($j)||($j['target_version']??'')!==self::TARGET_VERSION)throw new RuntimeException('Atomic transaction journal invalid.');
        $udir=rtrim((string)$rt['data_dir'],'/').'/updates';$stage=(string)($j['stage']??'');if($stage===''||strpos($stage,$udir.'/.atomic-')!==0||!is_dir($stage))throw new RuntimeException('Atomic recovery stage invalid.');$meta=json_decode((string)@file_get_contents($stage.'/source-meta.json'),true);if(!is_array($meta))throw new RuntimeException('Atomic recovery source metadata missing.');$cfg=$stage.'/config.bin';$dbs=$stage.'/database.sqlite';if(!is_file($cfg)||!is_file($dbs))throw new RuntimeException('Atomic recovery snapshot incomplete.');
        self::restoreFiles($root,$stage,$meta);self::restoreDb($dbs,(string)$rt['db_file']);self::writeExact((string)$rt['config_file'],(string)file_get_contents($cfg),0600);$s=self::verifySource($root);if(!$s['ok'])throw new RuntimeException('Interrupted Atomic source recovery verification failed.');self::dbVerify((string)$rt['db_file']);@unlink($journal);self::removeTree($stage);return true;
    }
    public static function selfTest(): array {if(PHP_VERSION_ID<80000)throw new RuntimeException('PHP 8.0+ required.');$src=self::decode(self::SOURCE_MANIFEST);$tar=self::decode(self::TARGET_MANIFEST);$pay=self::decode(self::PAYLOAD);$removed=self::decode(self::REMOVED);if(!$src||!$tar||!$pay)throw new RuntimeException('Atomic metadata empty.');foreach($tar as $rel=>$hash){if(!isset($pay[$rel]))throw new RuntimeException('Atomic payload misses target file: '.$rel);$b=base64_decode((string)$pay[$rel],true);if($b===false||!hash_equals((string)$hash,hash('sha256',$b)))throw new RuntimeException('Atomic payload hash mismatch: '.$rel);}foreach($removed as $rel)self::rel((string)$rel);return ['ok'=>true,'source_files'=>count($src),'target_files'=>count($tar),'payload_files'=>count($pay),'removed_files'=>count($removed),'php_min'=>'8.0.0','global_barrier'=>true,'interruption_recovery'=>true];}
    public static function verifySource(string $root): array {return self::verifyManifest($root,self::decode(self::SOURCE_MANIFEST),true);}
    public static function verifyTarget(string $root): array {return self::verifyManifest($root,self::decode(self::TARGET_MANIFEST),false);}
    public static function run(string $root): array {
        self::selfTest();$root=rtrim(realpath($root)?:$root,'/');if(!defined('VF_ROOT'))define('VF_ROOT',$root);if(!class_exists('VfMaintenanceBarrier',false)){require_once $root.'/app/Platform/Barrier.php';}if(function_exists('vf_request_global_barrier_release'))vf_request_global_barrier_release();$global=VfMaintenanceBarrier::globalExclusive();$stage='';$journal='';$sourceMeta=[];$rt=[];$configBytes='';$dbSnap='';
        try {
            $rt=self::runtime($root);$recovered=self::recoverInterrupted($root,$rt);$v=trim((string)@file_get_contents($root.'/VERSION.txt'));
            if($v===self::TARGET_VERSION){$t=self::verifyTarget($root);if(!$t['ok'])throw new RuntimeException('Target version files are inconsistent.');$dbv=self::dbVerify((string)$rt['db_file']);return ['ok'=>true,'already_current'=>true,'interrupted_recovered'=>$recovered,'schema'=>$dbv['schema'],'integrity'=>$dbv['integrity'],'fk'=>$dbv['foreign_key_errors']];}
            if($v!==self::SOURCE_VERSION)throw new RuntimeException('Unsupported source version: '.$v);$s=self::verifySource($root);if(!$s['ok'])throw new RuntimeException('Source verification failed: '.implode(',',$s['errors']));
            $data=rtrim((string)$rt['data_dir'],'/');$db=(string)$rt['db_file'];$config=(string)$rt['config_file'];if(!is_file($db)||!is_file($config))throw new RuntimeException('Installed database/config missing.');$udir=$data.'/updates';if(!is_dir($udir)&&!@mkdir($udir,0750,true)&&!is_dir($udir))throw new RuntimeException('Cannot create update directory.');
            $stage=$udir.'/.atomic-'.self::TARGET_VERSION.'-'.bin2hex(random_bytes(5));if(!@mkdir($stage,0700,true)&&!is_dir($stage))throw new RuntimeException('Cannot create Atomic stage.');$journal=self::journalPath($rt);$dbSnap=$stage.'/database.sqlite';$configBytes=(string)file_get_contents($config);self::writeExact($stage.'/config.bin',$configBytes,0600);self::snapshotDb($db,$dbSnap);
            $payload=self::decode(self::PAYLOAD);$removed=self::decode(self::REMOVED);$all=array_values(array_unique(array_merge(array_keys($payload),$removed)));$sourceMeta=self::backupFiles($root,$stage,$all);self::jsonWrite($stage.'/source-meta.json',$sourceMeta);self::jsonWrite($journal,['target_version'=>self::TARGET_VERSION,'source_version'=>self::SOURCE_VERSION,'stage'=>$stage,'phase'=>'prepared','created_at'=>gmdate('c')]);
            foreach($payload as $rel=>$b64){$bytes=base64_decode((string)$b64,true);if($bytes===false)throw new RuntimeException('Payload decode failed.');self::writeExact($root.'/'.self::rel((string)$rel),$bytes,0640);}foreach($removed as $rel){$p=$root.'/'.self::rel((string)$rel);if(is_file($p)||is_link($p))@unlink($p);}self::jsonWrite($journal,['target_version'=>self::TARGET_VERSION,'source_version'=>self::SOURCE_VERSION,'stage'=>$stage,'phase'=>'source_applied','created_at'=>gmdate('c')]);
            if(getenv('VF_ATOMIC_TEST_HARD_EXIT_AFTER_APPLY')==='1'){fwrite(STDERR,"Injected hard interruption after source apply.\n");exit(97);}if(getenv('VF_ATOMIC_TEST_FAIL_AFTER_APPLY')==='1')throw new RuntimeException('Injected failure after source apply.');
            $cfg=json_decode((string)file_get_contents($config),true);if(!is_array($cfg))throw new RuntimeException('Config JSON invalid.');$cfg['version']=self::TARGET_VERSION;$j=json_encode($cfg,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($j===false)throw new RuntimeException('Config serialize failed.');self::writeExact($config,$j."\n",0600);$target=self::verifyTarget($root);if(!$target['ok'])throw new RuntimeException('Target verification failed: '.implode(',',$target['errors']));$dbv=self::dbVerify($db);self::jsonWrite($journal,['target_version'=>self::TARGET_VERSION,'source_version'=>self::SOURCE_VERSION,'stage'=>$stage,'phase'=>'commit_ready','created_at'=>gmdate('c')]);@unlink($journal);self::removeTree($stage);$stage='';
            return ['ok'=>true,'already_current'=>false,'interrupted_recovered'=>$recovered,'schema'=>$dbv['schema'],'integrity'=>$dbv['integrity'],'fk'=>$dbv['foreign_key_errors'],'source_checked'=>$s['checked'],'target_checked'=>$target['checked'],'rollback_supported'=>true];
        } catch(Throwable $e) {
            if($stage!==''&&is_dir($stage)&&$rt){try{$meta=$sourceMeta;if(!$meta&&is_file($stage.'/source-meta.json')){$meta=json_decode((string)file_get_contents($stage.'/source-meta.json'),true)?:[];}if($meta)self::restoreFiles($root,$stage,$meta);if($dbSnap!==''&&is_file($dbSnap))self::restoreDb($dbSnap,(string)$rt['db_file']);if($configBytes===''&&is_file($stage.'/config.bin'))$configBytes=(string)file_get_contents($stage.'/config.bin');if($configBytes!=='')self::writeExact((string)$rt['config_file'],$configBytes,0600);$after=self::verifySource($root);if(!$after['ok'])throw new RuntimeException('Rollback source verification failed.');self::dbVerify((string)$rt['db_file']);if($journal!=='')@unlink($journal);self::removeTree($stage);}catch(Throwable $rb){throw new RuntimeException('Atomic failed and rollback verification failed.',0,$e);}}throw new RuntimeException('Atomic failed; source, config and database were restored: '.$e->getMessage(),0,$e);
        } finally {if(isset($global))$global->release();}
    }
}
if(defined('VF_ATOMIC_LIBRARY_MODE')&&VF_ATOMIC_LIBRARY_MODE)return;
if(PHP_SAPI==='cli'){try{if(in_array('--self-test',$argv,true)){echo json_encode(VfAtomicPackage::selfTest(),JSON_UNESCAPED_SLASHES)."\n";exit(0);}foreach($argv as $a){if(strpos($a,'--verify-source=')===0){$r=VfAtomicPackage::verifySource(substr($a,16));echo json_encode($r)."\n";exit($r['ok']?0:1);}if(strpos($a,'--verify-target=')===0){$r=VfAtomicPackage::verifyTarget(substr($a,16));echo json_encode($r)."\n";exit($r['ok']?0:1);}if(strpos($a,'--run=')===0){echo json_encode(VfAtomicPackage::run(substr($a,6)),JSON_UNESCAPED_SLASHES)."\n";exit(0);}}fwrite(STDERR,"Use --self-test, --verify-source=PATH, --verify-target=PATH or --run=PATH\n");exit(2);}catch(Throwable $e){fwrite(STDERR,$e->getMessage()."\n");exit(1);}}
$root=__DIR__;require_once $root.'/app/bootstrap.php';vf_security_headers(true);header('X-Robots-Tag: noindex,nofollow,noarchive');vf_start_session();if(!vf_is_admin()){http_response_code(403);echo '<!doctype html><meta charset="utf-8"><title>VF Start 升级</title><p>需要管理员登录后再执行升级。</p>';exit;}$csrf=vf_csrf_token();$result=null;$error='';if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){try{if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('请求已过期。');$result=VfAtomicPackage::run($root);}catch(Throwable $e){$error=$e->getMessage();}}?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VF Start V<?=htmlspecialchars(VfAtomicPackage::TARGET_VERSION)?> 升级</title></head><body><main><h1>VF Start 升级</h1><?php if($result):?><h2>升级完成</h2><p>版本：V<?=htmlspecialchars(VfAtomicPackage::TARGET_VERSION)?></p><p><a href="./">打开 VF Start</a></p><?php elseif($error!==''):?><h2>升级失败</h2><p><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></p><?php else:?><p>将从 V<?=htmlspecialchars(VfAtomicPackage::SOURCE_VERSION)?> 升级到 V<?=htmlspecialchars(VfAtomicPackage::TARGET_VERSION)?>。执行前会建立数据库、配置和源码恢复点。</p><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><button type="submit">执行原子升级</button></form><p><a href="./">返回 VF Start</a></p><?php endif;?></main></body></html>
'''
    return template.replace('@@SOURCE_MANIFEST@@',b64json(src_manifest)).replace('@@TARGET_MANIFEST@@',b64json(target_manifest)).replace('@@PAYLOAD@@',b64json(payload)).replace('@@REMOVED@@',b64json(removed)).replace('@@ALTERNATES@@',b64json(alternates))

m.build_repair=build_repair
if __name__=='__main__': m.main()
