'use strict';
const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright'),{cli,load,state,setSettings,base}=require('./common');
(async()=>{
 const b=await chromium.launch(),c=await b.newContext(),p=await c.newPage(),tests=[],observed=[];const pass=n=>tests.push(n);
 cli('update_option("permalink_structure","/%postname%/");flush_rewrite_rules(true);foreach(["seo-native","seo-other"] as $slug){$id=wp_insert_post(["post_type"=>"page","post_status"=>"publish","post_name"=>$slug,"post_title"=>"Synthetic ".$slug,"post_content"=>"Synthetic ordinary WordPress content, not a projection fixture."]);if(is_wp_error($id)){throw new Exception("native fixture failed");}update_option("vf_fixture_".$slug,$id);}');
 const row={routeId:'route_seo_native',pageFamily:'content',pathPattern:'seo-native',resolver:'vf_theme_url_resolver',canonicalPolicy:'self',hreflangPolicy:'paired',indexability:'index_follow',staticPathPolicy:'required'};
 const set=changes=>setSettings({virtualRoutePolicy:[{...row,...changes}]});
 const inspect=async pathname=>{const r=await p.goto(base+pathname),h=await p.locator('head').evaluate(n=>({canonical:Array.from(n.querySelectorAll('link[rel=canonical]')).map(n=>n.href),hreflang:Array.from(n.querySelectorAll('link[hreflang]')).map(n=>({code:n.hreflang,href:n.href})),robots:Array.from(n.querySelectorAll('meta[name=robots]')).map(n=>n.content),schema:Array.from(n.querySelectorAll('script[type="application/ld+json"]')).map(n=>n.textContent)}));const x={path:pathname,status:r.status(),headers:r.headers(),head:h};observed.push(x);fs.writeFileSync('proof/public-output-observed.json',JSON.stringify(observed,null,2));return x;};
 set({});let h=await inspect('/seo-native/');assert.equal(h.status,200);assert.deepEqual(h.head.canonical,[base+'/seo-native/']);assert.equal(h.head.hreflang.length,0,'unpaired content must not invent translations');pass('actual native page has one self Canonical and no invented language pairing');
 const resolved=()=>JSON.parse(cli(load+'vf_theme_bootstrap_require_many(["services/url-resolver-service.php"]);echo wp_json_encode(vf_theme_url_resolver_resolve(["route"=>"seo-native","language"=>"en"]));'));
 let r=resolved();assert(r.known&&r.existsOrExpected);assert.equal(r.canonicalUrl,base+'/seo-native/');assert(r.staticPath.includes('seo-native'));assert.equal(r.sitemapUrl,base+'/seo-native/');pass('real URL Resolver finds existing native page / Canonical / Sitemap / static required path');
 set({canonicalPolicy:'none'});h=await inspect('/seo-native/');assert.equal(h.head.canonical.length,0);assert.equal(resolved().canonicalUrl,'');pass('saved Canonical none suppresses actual public Head and Resolver');
 for(const [policy,expect] of [['noindex_follow',['noindex','follow']],['noindex_nofollow',['noindex','nofollow']],['index_follow',['index','follow']]]){set({indexability:policy});h=await inspect('/seo-native/');const robots=h.head.robots.join(',').replace(/\s/g,'');assert(expect.every(x=>new RegExp('(^|,)'+x+'(,|$)').test(robots)),policy+': '+robots);r=resolved();assert.equal(r.sitemapUrl==='',policy!=='index_follow');const xml=await(await c.request.get(base+'/sitemap.xml')).text();const included=xml.includes('<loc>'+base+'/seo-native/</loc>');assert.equal(included,policy==='index_follow',policy+' actual sitemap inclusion');pass('actual Robots / XML Sitemap / Resolver respond to '+policy);}
 set({staticPathPolicy:'exclude'});assert.equal(resolved().staticPath,'');set({});assert(resolved().staticPath.includes('seo-native'));pass('actual existing-route static path excluded and restored by canonical option');
 setSettings({searchIndexability:'noindex_follow'});h=await inspect('/?s=synthetic-check');assert(h.head.robots.join(',').includes('noindex'));assert.equal(h.head.canonical.length,0);assert.equal(h.head.hreflang.length,0);assert.equal(h.head.schema.length,0);pass('actual search edge default robots and technical Head suppression');setSettings({searchIndexability:'index_follow'});h=await inspect('/?s=synthetic-check');assert(/(^|,)index(,|$)/.test(h.head.robots.join(',').replace(/\s/g,'')));pass('search global index toggle reaches actual WordPress request');
 for(const pathname of ['/not-existing-synthetic-path/','/seo-native/?preview=true']){h=await inspect(pathname);assert(h.head.robots.join(',').includes('noindex'));assert.equal(h.head.canonical.length,0);assert.equal(h.head.hreflang.length,0);assert.equal(h.head.schema.length,0);assert((h.headers['x-robots-tag']||'').includes('noindex'));pass('actual fixed noindex / Head suppression / response headers: '+pathname);}
 set({});const widths=[];for(const width of [1920,1440,1319,1024,768,390]){await p.setViewportSize({width,height:1000});h=await inspect('/seo-native/');assert.deepEqual(h.head.canonical,[base+'/seo-native/']);const overflow=await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert(overflow<=1);widths.push({width,status:'PASS',overflow});await p.screenshot({path:'proof/seo-public-'+width+'.png',fullPage:true});}pass('actual public outputs and no overflow at six widths');
 assert.equal(JSON.parse(cli(load+'echo wp_json_encode(vf_theme_seo_owner_manifest());')).themeStoresPolylangRelations,false);assert.equal(JSON.parse(cli(load+'echo wp_json_encode(vf_theme_seo_owner_manifest());')).themeStoresRankMathMeta,false);pass('existing technical owner boundary without copied content metadata or translation storage');
 fs.writeFileSync('proof/public-output.json',JSON.stringify({status:'PASS',environment:'REAL_ISOLATED_WORDPRESS',fixtures:'ordinary published WordPress pages and actual HTTP Head/XML endpoints, no rewritten SEO output',hreflang_scope:'unpaired native content suppressed; third-party translation creation not changed or claimed',tests,widths,observed},null,2));await b.close();console.log('SEO_ACTUAL_PUBLIC_OUTPUT=PASS cases='+tests.length);
})().catch(e=>{console.error(e);process.exit(1)});
